### PR TITLE
[Ready] Medical voidsuit resprite

### PR DESCRIPTION
**Pull request by AnalWerewolf**
## About The Pull Request

Resprites current ALL current medical voidsuits with an updated design voted by the community. This PR also standardizes all medical voidsuits across species AND removes all uses of the red cross symbol on voidsuits, instead replacing them with a blue cross.

See below for examples of my changes:

Original:
https://puu.sh/DCowb/5cc4c330df.png
New sprite:
http://puu.sh/DCHPo/3c688d1635.png

## Why It's Good For The Game

Improved aesthetics, avoids potential legal trouble, not like the Red Cross would care about SS13 anyway.
It just looks better.

## Changelog
:cl:
imageadd: Resprites medical voidsuits and standardizes their designs.
/:cl:

### CODE REVIEW

**Comment by VarkaSelyn** [comment]
Wait, did you get the hardsuits as well? The medical_rig and medical_rig_sealed have the red cross too.

(PS: looks like your changes are conflicting with the vulp hardsuit sprite changes I made in #1386)

**Comment by AnalWerewolf** [comment]
Nope, only changed the voidsuits.

**Comment by AnalWerewolf** [comment]
@kevinz000 Need another review.

**Comment by AnalWerewolf** [comment]
@BlackMajor Kevinz is a lazy cat, need a review and maybe a merge.

**Pull request merged**
