### PR TITLE
Species Major Update #1: Cultures, factions, and more oh my!

### PR DESCRIPTION
**Pull request by Zandario**
## About The Pull Request

Ported content originating from Baystation12/Baystation12/pull/22722

This reworks species to now appear in modules/species instead of that endless folder.
Languages are no longer directly inherited for just being a certain species, they get them from their available cultures.
Fundamentally this is still somewhat of the same as before but this adds great starter information which should help
uncreative (ME), and newer players have a better grasp of the environment before they even press join.

## Species Lore Progress

- [x] Adherent
- [ ] Akula
- [ ] Alarune
- [x] Apidaen
- [ ] Auril
- [ ] Custom_Species
- [ ] Diona
- [ ] Dremachir
- [ ] Golem - Minor*
- [ ] Harpy*
- [ ] Human
- [x] Monkey (Don't ask, it's Monkey Business)
- [ ] Nevrean*
- [ ] Phoronoids
- [ ] Prometheans
- [ ] Protean
- [ ] Replicant - Minor*
- [ ] Sergal*
- [ ] Shadekin
- [ ] Shadekin (Black-Eyed)
- [ ] Shadow - Minor*
- [ ] Skeleton - Minor*
- [ ] Skrell
- [x] Tajara
- [ ] Teshari
- [ ] Unathi
- [ ] Vasilissan
- [ ] Vox
- [ ] Werebeast*
- [ ] Xenochimera
- [x] Xenomorph - Minor
- [x] Xenomorph Hybrid
- [ ] Zaddat
- [ ] Zorren*

## Another Note

This is Part 1 of a line of major refactors and updates I plan to do regarding species. A lot of my future work will rely on some of the foundations that this PR sets in stone.

## Changelog
:cl:
add: Culture Subsystem
add: Background Menu in the Character Creation Process
fix: fixed a all the Wikilinks and commented out the missing ones.
code: Massive restructure to Species
refactor: MASSIVE REFACTOR TO HOW SPECIES INHERENT STUFF
/:cl:

### CODE REVIEW

**Comment by Zandario** [comment]
Do note that this is currently up as a draft due to needing the lore team to help me fill in information.

**Comment by FreeStylaLT** [comment]
holy frickin' cow batman.

anyway, quick notes:

- Inconsistent language counts (Chimera / Proteans are now 3 each, used to be 5. May be intentional?)

Runtimes:
- `[2022-03-27T12:59:58] Runtime in _culture.dm, line 31: type mismatch: "Canilunzt" -= "Galactic Common"
proc name: New (/decl/cultural_info/New)
src: Temp Werebeast Culture (/decl/cultural_info/culture/temp/werebeast)
call stack:
Temp Werebeast Culture (/decl/cultural_info/culture/temp/werebeast): New()
Culture (/datum/controller/subsystem/culture): Initialize(467988)
Master (/datum/controller/master): Initialize(10, 0, null)`
(repeated *least* for these, but likely for everyone)
image
- `proc name: is alien whitelisted (/proc/is_alien_whitelisted)
src: null
call stack:
is alien whitelisted(IAmCrystalClear (/mob/new_player), Vox-Pidgin (/datum/language/vox))
Languages (/datum/category_item/player_setup_item/background/languages): rebuild language cache(IAmCrystalClear (/mob/new_player))
Languages (/datum/category_item/player_setup_item/background/languages): sanitize alt languages()
Languages (/datum/category_item/player_setup_item/background/languages): sanitize character()
Background (/datum/category_group/player_setup_category/background_preferences): sanitize setup()
/datum/category_collection/pla... (/datum/category_collection/player_setup_collection): sanitize setup()
/datum/preferences (/datum/preferences): sanitize preferences()
IAmCrystalClear (/client): New(null)
IAmCrystalClear (/client): New()
IAmCrystalClear (/client): New()`
- `[2022-03-27T13:23:32] Runtime in string.dm, line 3: Cannot read "Vespinae".len`

**Comment by TheLordME** [comment]
1. Suggestion: Maybe put the cultures together with species into one folder? I can see arguments for both, just an idea I had.
2. Fact: It was decided that Nameing conventions are enforced via admins, not with mechanics, so players can use special characters and number in their names, even when they arent cyborgs. https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/3401 See here
3. Fact: I am opening a PR to your branch hopefully today, with some lore bits for xenohybrids

**Comment by TheLordME** [comment]
Vox look pretty done to me

**Comment by TheLordME** [comment]
For dionas, id PR it but lazy:

> /decl/lore_info/religion/diona
> 	name = "The Gathering"
> 	description = "We are on a journey to gather information, so we may preserve it until the end of time. Our journey seems simple, leave, learn, return, but we face millions of dangers on our way, may the stars sing with us."

With that diona lore should be done

**Pull request closed without merging**
