### PR TITLE
Tether Re-Map Part 1 of X: Centcomm and the Tram

### PR DESCRIPTION
**Pull request by CharlesWedge**
## Making CentComm and Tram Better for Gameplay and RP Alike

Currently CC and the Tram feel like hollow facades of what should be functional locations. 

The Tram big as it lacks any facilities for doing anything but transporting passengers, mind you this is the thing we escape too when the Tes-Looses and the Supermatter Super-Irradiates the entire station. It also lacks no facilities for the transport of prisoners or wounded staff, leaving medical in a hard spot when it comes to treating the injured. CC currently consists of a small security checkpoint accessible form the back of the bar, said bar, and an alright medbay that lacks some key features. 

In light of these lackings I have remapped both the Tram and CC to fit many more features. The Tram is now much more functional, seating 34 regular passengers, 4 security officers, 3 prisoners, and up to 5 doctors and patients. CC has had so many changes I will simply list them in the Changelog.

## Changelog
:cl:
CC Sec: Added a break room, evidence storages, 2 prison cells and a processing room. Moved Sec to the former location of Hangar 1.
CC Bar/Restraunt: Has been moved right alongside the station itself and can now be accessed directly from the station. A coffee maker has been added along with some seating in the station area itself along with a barsign.
CC Medical: Added Blood Vendor, Organ Printer and Morgue with both cremator and autopsy table.
CC Bathroom: Is now in between medical and bar.
Escape Pod Landing Pad: Is now "Above" the tram station, rather than next to the elevators, with a hallway connecting the two where the former "cryopod" Teleporters used to be.
CC Teleporters: Are now at the end of the hall, like all the other "cryopods".
CC General: More potted plants to make things look nice.
/:cl:

### CODE REVIEW

**Comment by Keekenox** [comment]
I'm really not a fan of how large the medbay and brig parts of the tram are, especially since it's just a tram and shouldn't really need medical and brig facilities since it's just colony transit. 

That being said I am also on the fence about adding more to the centcomm/colony z level. I am all for adding it where it matters but I don't want to go to where we had it before where this is just mass areas full of weird things that literally never ever get used. I don't want to add a bunch of bloat and lag to a map that may only ever get used like once.

**Comment by CharlesWedge** [comment]
> I'm really not a fan of how large the medbay and brig parts of the tram are, especially since it's just a tram and shouldn't really need medical and brig facilities since it's just colony transit.
> 
> That being said I am also on the fence about adding more to the centcomm/colony z level. I am all for adding it where it matters but I don't want to go to where we had it before where this is just mass areas full of weird things that literally never ever get used. I don't want to add a bunch of bloat and lag to a map that may only ever get used like once.

Yes the Tram is colony transit but its also an emergency escape vehicle (Keep in mid Cit's version of the Frontier is a dangerous place with cultists, pirates and monsters oh my), it needs space for people potentially wounded in a disaster and for prisoners that security is required to transfer. The Tram even if its primarily used for transit is no longer a civilian transporter but a corporate one. As is leaving security to transfer prisoners and medical to transfer wounded personelle out in the open is rather stupid. I know they appear large but really are not and only appear large because of the Tram's rather awkward to work with shape.

As for CC, very little has actually been added to it things have mostly just been moved around. Most of the additions are in security which now actually has cells for transferred prisoners, so security can put them in the cells rather than simply dragging them around an empty hall until round end. The only addition to medical was a morgue for the bodies medical for whatever reason cannot resleeve, and the organ printer which seems like an oversight not to have considering the bodyprinter is right there. You do not have to worry about bloat since there really is no bloat to speak of. All the areas added are at least somewhat necessary or are there to serve the function of making CC feel like a believable place rather than the waiting room where our characters our stored at the end of the round.

**Comment by nik707** [comment]
I'd like to add that this changes will do absolutely nothing to any form of performance, lag, or bloat

**Comment by Hjorthorn** [comment]
> 
> 
> > I'm really not a fan of how large the medbay and brig parts of the tram are, especially since it's just a tram and shouldn't really need medical and brig facilities since it's just colony transit.
> > That being said I am also on the fence about adding more to the centcomm/colony z level. I am all for adding it where it matters but I don't want to go to where we had it before where this is just mass areas full of weird things that literally never ever get used. I don't want to add a bunch of bloat and lag to a map that may only ever get used like once.
> 
> Yes the Tram is colony transit but its also an emergency escape vehicle (Keep in mid Cit's version of the Frontier is a dangerous place with cultists, pirates and monsters oh my), it needs space for people potentially wounded in a disaster and for prisoners that security is required to transfer. The Tram even if its primarily used for transit is no longer a civilian transporter but a corporate one. As is leaving security to transfer prisoners and medical to transfer wounded personelle out in the open is rather stupid. I know they appear large but really are not and only appear large because of the Tram's rather awkward to work with shape.
> 
> As for CC, very little has actually been added to it things have mostly just been moved around. Most of the additions are in security which now actually has cells for transferred prisoners, so security can put them in the cells rather than simply dragging them around an empty hall until round end. The only addition to medical was a morgue for the bodies medical for whatever reason cannot resleeve, and the organ printer which seems like an oversight not to have considering the bodyprinter is right there. You do not have to worry about bloat since there really is no bloat to speak of. All the areas added are at least somewhat necessary or are there to serve the function of making CC feel like a believable place rather than the waiting room where our characters our stored at the end of the round.

I'm not against the presence of a medbay and holding cells, but I think they're entirely too large for the tram. I'd personally push it back to the absolute bare minimum of space required by either, and cut down on their equipment if necessary. The bottom line is that it's a _tram_ above all else, not a space shuttle, and these facilities are excessive for a 3 minute trip to the station where must better equipped facilities are already present. It should be like the back of an ambulance and a paddy wagon, not a small holding area and clinic.

**Comment by nik707** [comment]
@Hjorthorn Can you provide an example of how you'd accomplish that given the shape of the tram?

**Comment by Hjorthorn** [comment]
> 
> 
> @Hjorthorn Can you provide an example of how you'd accomplish that given the shape of the tram?

Sure if Captain would teach me to map already

**Pull request merged**
