### PR TITLE
Fluff item for Lectronyx - The Mind Electric

### PR DESCRIPTION
**Pull request by lectronyx**
## About The Pull Request
I got a little too excited to wait, and decided to try adding my fluff item for Citadel RP's patreon. Let's see how this goes, ja?

## Why It's Good For The Game
Patreon baybeeeeeeeeeeeeeeeeeee

## Changelog
:cl:
add: Added item "The Mind Electric"
imageadd: Icons for "The Mind Electric"
/:cl:

### CODE REVIEW

**Comment by Funkeronipasta** [comment]
That reminds me - I'll get back to work on it on my end lol

**Comment by lectronyx** [comment]
Hold up, what's it complaining about??

**Comment by lectronyx** [comment]
Is it because of the indigestible code snippet?

**Comment by Funkeronipasta** [comment]
Nah, there's like, 4 files that need changing for it to work iirc

**Comment by Funkeronipasta** [comment]
I'm most of the way through, just on the troubleshooting/tweaking fun pit so it all clicks together

**Comment by Funkeronipasta** [comment]
Apparently there's also like 2 different custom clothing locations
I'll need to see if the one you used is right, since I'm having sprite-appearance issues on my end that may be related to that.

**Comment by Funkeronipasta** [comment]
Oh ye, I like the sprites btw c:

**Comment by lectronyx** [comment]
> Oh ye, I like the sprites btw c:

Thank you! I'm really excited to get this up

**Comment by lectronyx** [comment]
As Crazy Frog, himself, once said...

_**What's going on?**_

no, seriously, wtf is up with the locations of stuff for fluff items? closed in favor of better PRs

**Pull request closed without merging**
