### PR TITLE
Exploration Shuttle Tweaks: GPS, Shutters, etc.

### PR DESCRIPTION
**Pull request by KillianKirilenko**
## About The Pull Request

Adds a hidden GPS marker to the shuttle, and a set of shutters to the excursion shuttle's exterior windows. Also adds lightswitches. MapDiffs doesn't show it but there's a lightswitch and a shutter control on the front panel, which can be accessed from both pilot seats.

The airpump and spaceheater have been moved out of the cargo bay and into the hangar.

## Why It's Good For The Game

In the event that you get lost on the beach or in other exploration zones, you can now use GPS trackers to find your way back.

As for the shutters, they start closed and can be used for privacy or in the event of broken windows. Lightswitches are more of a "why not".

I've never personally seen there be a need for the pump/heater, so moving them out into the hangar means more room for cargo but that they're also there if they're ever actually required.

## Changelog
:cl:
add: Added a GPS marker, blast shields, and light switches to the Exploration Shuttle
tweak: Moved the space heater and airpump out of the cargo bay and into the main hangar
/:cl:

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Active edges again with railings z-level 18. Lovely.

**Comment by KillianKirilenko** [comment]
Fairly sure Z18 is the V4 caves this time. Once again not my problem, 'cause I didn't touch it.

**Comment by KillianKirilenko** [comment]
Small update to add lightswitches, also fixes the travis issue.

**Comment by KillianKirilenko** [comment]
Retiring this PR in favor of a newer one that I'm currently working on.

**Pull request closed without merging**
