### PR TITLE
Ports multi directional dogborg rest sprites from virgo.

### PR DESCRIPTION
**Pull request by BlackMajor**
Also adds animations to some others, and adds sit sprites for cit exclusive dogborgs.

Example sits.

Doggos

Edit: Oh right I forgot to mention, also moved the modular_citadel widerobot stuff to widerobot_vr. We're not downstreamed like that anymore so there's no need for them to be in seperate files.

### CODE REVIEW

**Comment by BlackMajor** [comment]
Diff bot ded

**Comment by KillianKirilenko** [comment]
Has the alt. sechound's flank badge changing colors been fixed? You can even see it here where the badge is white on the standard rest pose but cyan on the sitting pose (and, I think, regular standing pose). Might want to square that away before final merge.

**Comment by nik707** [comment]
can we rename it from widerobot who's idea was that wtf

**Comment by BlackMajor** [comment]
> Has the alt. sechound's flank badge changing colors been fixed? You can even see it here where the badge is white on the standard rest pose but cyan on the sitting pose (and, I think, regular standing pose). Might want to square that away before final merge.

I did yeah

**Pull request merged**
