### PR TITLE
Early Assets, Lateloaded Assets, and Debugging Tools

### PR DESCRIPTION
**Pull request by Zandario**
## About The Pull Request
Various asset systems I want in before more TGUI work. and also byond-tracy support... and also light update debugging...
## Changelog
:cl:
tweak: Chem Master UI has been reworked slightly.

### CODE REVIEW

**Review by silicons — DISMISSED** [review]

**Comment by Zandario** [comment]
tfw I was devin' on the wrong branch all day

**Comment by Zandario** [comment]
Finally

**Review by TheLordME — APPROVED** [review]

**Comment by TheLordME** [comment]
this should be like 5 PRs if we are being honest

**Comment by TheLordME** [comment]
maybe more

**Pull request merged**
