### PR TITLE
Ports a few clothes from main.

### PR DESCRIPTION
**Pull request by GrayRachnid**
Grey HoS skirt added and placed in the HoS's gear locker
~'Formal'(slutty) captain outfit added and placed in his wardrobe.~
Green and Pink stripper outfits added, can be found in the trash with the same probability as the latex dress. Two spawn by default in the sex dungeon on Surface 2.

### CODE REVIEW

**Comment by GrayRachnid** [comment]
No idea why it's failing.

**Comment by improvedname** [comment]
Can you not add the formal suit thats orginally intented to be my rp server donator item

**Comment by GrayRachnid** [comment]
It's on main publicly though

**Comment by GrayRachnid** [comment]
Yeah I have no idea why travis is being a dick i'll wait until someone helps me figure this out

**Comment by NopeMcHaltman** [comment]
I really, *really* suggest ignoring Travis if it's doesn't point out the real error.

**Comment by GrayRachnid** [comment]
I give up, i'll try this again sometime else.

**Pull request closed without merging**
