### PR TITLE
[DNM] Sec Pistols: The respritening

### PR DESCRIPTION
**Pull request by peeesh**
## About The Pull Request

ports "eris" mk58 sprites (i rejigged them slightly to fit with the style more) for use in a new security 45, aptly named gun/secnew instead of just gun/sec. includes sectech vendors, which vend pistols loaded with flash rounds (like the old ones)

## Why It's Good For The Game

variety is the spice of life, plus the old sprites pretty much consist of 2 bricks put together. no, i didnt delete the old ones. did i mention i actually modularised this time? like, proper?

## Changelog
:cl:
add: GUN, respritable
add: the sprites
tweak: sectech vends new pistols
/:cl:

### CODE REVIEW

**Comment by peeesh** [comment]
FUCK, THE COINS
REE

**Comment by peeesh** [comment]
KEEEEV how do i delete commits

**Comment by Andromeda-K22** [comment]
#841 probably interferes with this.

**Comment by GrayRachnid** [comment]
I already ported their sprites in my PR.

**Comment by peeesh** [comment]
ebic

**Pull request closed without merging**
