### PR TITLE
[Ready to Merge] [MDB IGNORE] [DNM] NLV Euthenia

### PR DESCRIPTION
**Pull request by ktoma36**
## About The Pull Request

A new ship map. Still very WIP but its easier to keep track of my progress with an actual pr :D

image
image
image

## Why It's Good For The Game

Variety is the spice of life and ship maps are fun. This is not intended to replace the rift (at some point we will have a map rotation system). As well this is very WIP

## Changelog
:cl:
add: A new ship map
/:cl:

### CODE REVIEW

**Comment by TheLordME** [comment]
converted to draft to 
(1) represent the WIP nature additionally
(2) I hoped it wouldnt show up for testmerges and clutter the interface even more

**Comment by ktoma36** [comment]
Oh xenoarch, how we love random integration test fails

**Comment by AllCorruptingWyrm** [comment]
please please merge this branch so other contribs can add to it, I can probably finish mapping of certain z levels in 2-3 days.

**Comment by ktoma36** [comment]
This is good to merge, I don't know how to take it out of draft

**Comment by TheLordME** [comment]
WOAH

**Pull request merged**
