### PR TITLE
[RFM] Readds the Human Subspecies (Space/Grav-adapted, Vatgrown)

### PR DESCRIPTION
**Pull request by TheLordME**
Name is just to meme, actually it reenable the human subspecies for selection.

## About The Pull Request
Reeenables the human subspecies, its really minorly varied version of humans.

## Why It's Good For The Game
Variaty I guess

## Changelog
:cl:
add: Space-Adapted Humans are avaiable as a playable species
add: Grav-Adapted Humans are avaiable as a playable species
add: Vatgrown humans are avaiable as a playable species
/:cl:

### CODE REVIEW

**Comment by TheLordME** [comment]
Gonna give those subspecies some love before we fully merge them

**Review by Captain277 — CHANGES_REQUESTED** [review]
Please add the following lines below the icobase variable for every race. Their skin coloration isn't functioning properly and I believe this fixes it.


spawn_flags = SPECIES_CAN_JOIN
	appearance_flags = HAS_HAIR_COLOR | HAS_SKIN_TONE | HAS_LIPS | HAS_UNDERWEAR | HAS_EYE_COLOR

	color_mult = 1
	appearance_flags = HAS_HAIR_COLOR | HAS_SKIN_COLOR | HAS_LIPS | HAS_UNDERWEAR | HAS_EYE_COLOR
	base_color = "#EECEB3"

**Comment by Kraseo** [comment]
why are these species whitelisted when they're literally minor changes to the baseline human numbers?

**Comment by Captain277** [comment]
There's no plan to keep the races whitelisted, as far as I'm aware. I believe ME made them WL while they're being tested? Couldn't say.

**Comment by TheLordME** [comment]
They are whitelisted because I am working on them, feel free to grant players the whitelist, but tell them that mechanics surrounding the species may change at any time
And no. the title stays, we dont enforece proper commit messages, why should we enforce PR titles?

**Comment by Captain277** [comment]
What are you talking about? You're supposed to use proper commit messages.

**Comment by TheLordME** [comment]
grafik

**Comment by TheLordME** [comment]
grafik

**Comment by TheLordME** [comment]
want more examples?

**Comment by TheLordME** [comment]
Once the Spacer changes have been tested we can remove the Whitelist for them, and ill continue with the gravadapts

**Comment by Captain277** [comment]
Oh *commit* messages. I thought we were talking about changelogs. Don't conflate commit messages with PR titles. No one's looking this shit up using a commit message.

**Comment by TheLordME** [comment]
Basicly only waiting on player feedback now.

**Comment by Kraseo** [comment]
expecting player feedback
with whitelisted species.
🤦

**Comment by TheLordME** [comment]
@Kraseo if you are just here to shitpost
here are some doors, pick one and leave: https://www.door-systems.de/

**Comment by TheLordME** [comment]
whitelist was removed three days ago

**Comment by Kraseo** [comment]
then upgrade the changelog

**Review by Captain277 — APPROVED** [review]

**Pull request merged**
