### PR TITLE
Re-adds EAL language implants.

### PR DESCRIPTION
**Pull request by avabee**
They now cost double the points to purchase, because apparently VORE had issues with them, and I'm assuming in good faith they had at least somewhat of a decent reason for removing them.
(Though it is rather ironic that Virgo removed a widely-liked feature for balance issues.)

### CODE REVIEW

**Comment by avabee** [comment]
Ah, I used the web UI. Good catch, though.

**Comment by Mewchild** [comment]
The translator earpiece was also removed at the same time as the EAL implant. Removal reason was wanting to make languages more niche, and make it so people couldn't understand everything.

**Comment by jakeramsay007** [comment]
@Mewchild translator earpieces can be produced in RnD

**Comment by Mewchild** [comment]
They used to be selectable in the loadout, for 4 points.

**Pull request merged**
