### PR TITLE
Fixes the chirp emote for human mobs

### PR DESCRIPTION
**Pull request by yourdoom9898**
## About The Pull Request

Turns out copy pasting code from non human mobs into human code might bork things, who'd've thunk

## Why It's Good For The Game
Allows people to chirp to their heart's content without it stating their name twice.

## Changelog
:cl:
fix: fixed the chirp emote saying a human mob's name twice
/:cl:

### CODE REVIEW

**Comment by VailTheWolf** [comment]
Teshari have this problem too if you haven't fixed it already.

**Comment by yourdoom9898** [comment]
@VailTheWolf This works for all the roundstart crew species types. I also tested Teshari specifically to make sure it worked, and it did.

**Comment by nik707** [comment]
Why did you change the wording? All these emotes having the same shitty writing is bad. Put that back and then it's good.

**Comment by yourdoom9898** [comment]
I should probably make a pass at some point to make the other emotes less shit then. Give me a sec

**Pull request merged**
