### PR TITLE
[READY] Giant Teshari Update: Cleans out Seromi, New Sprites, and More!

### PR DESCRIPTION
**Pull request by Zandario**
## About The Pull Request
Mainly started with scrubbing out Resomi/Seromi with Teshari while respriting the tesh cloaks to match human cloaks, color scheme and all which resulted in respriting the Teshari Undercoats to match... etc. etc. Now there is several selections of additions including the porting of the re-addition of hooded cloaks done by CHOMPstation

## Why It's Good For The Game

Muh Tesh Content sooo mmmmph yes

## Changelog
:cl:
add: customizable choker in loadout for both Teshari and Humans (ported)
add: Teshari Collars and Harnesses for those certain people (ported)
add: Hooded Teshari Coats, they're pretty hot if you ask me (ported)
add: 2-3 new sets of prosthetics for various species including Teshari and even Diona Nymphs! (ported)
imageadd: Teshari Collars (You asked for em, you're welcome) (ported)
imageadd: Resprited Teshari Cloaks (by me)
imageadd: Resprited Teshari Department Cloaks (by me)
imageadd: New Teshari Department Dresses (by me)
imageadd: Probably more things (fugg if I know)
code: Every. Single. Instance. of Resomi/Seromi has been thoroughly replaced with the proper name. Teshari.  (by me)
del: Duplicate Teshari markings/tails which were well, identical, but broken as it was legacy content. (delet'd by yours truly)
/:cl:

### CODE REVIEW

**Comment by Zandario** [comment]
Behold the long list of Additional Diffs because seromi

**Comment by Nethaufer** [comment]
Removed the CE undercoat?

**Comment by Zandario** [comment]
No, removed the unnecessary gold button variants and gave all cmd undercoats gold buttons to stand out from other undercoats
In this case what we didn't have before is: RD, HOP, and HOS
image

**Comment by Nethaufer** [comment]
Yeah but in the code you changed the define for the CE undercoat to the HoS one

**Comment by Nethaufer** [comment]
Disregard the one you changed was a ce sub type

**Comment by Enzo-Leon** [comment]
Is this safe to test-merge yet, or do we need to apply a DNM tag on this?

**Comment by Zandario** [comment]
> Is this safe to test-merge yet, or do we need to apply a DNM tag on this?

This has a WIP tag on it and no

**Comment by Zandario** [comment]
ree, I'll finish this tomorrow

**Comment by Zandario** [comment]
👌

**Comment by ThatOneTeshari** [comment]
Heya, so did a little looking into this since I was curious. When trying to use this on Cit13 RP's server, I end up getting this following issue. I think there may be a biiiit of a whoops in the code somewhere. Picture relating to the issue: 
Hehoo

**Comment by Zandario** [comment]
> Heya, so did a little looking into this since I was curious. When trying to use this on Cit13 RP's server, I end up getting this following issue. I think there may be a biiiit of a whoops in the code somewhere. Picture relating to the issue:
> Hehoo
> Edit: Cropped the picture a tad.

Yeaaaah Looking into it my dude, definitely something wonky somewhere.

**Comment by Zandario** [comment]
Fuck Travis, I now finally understand.

**Comment by Greenjoe12345** [comment]
what do the new cloaks look like?

**Comment by Zandario** [comment]
> what do the new cloaks look like?

Which ones? The resprites I did on the old undercoats/cloaks? Or...

**Comment by Zandario** [comment]
Just gonna mass post some images, better safe than sorry 🤷 

image
dreammaker_5rJkMlAtY0
dreammaker_8dCslaQsW6
dreammaker_aqx5ULT2rt
image

**Comment by Greenjoe12345** [comment]
yeah I meant the resprites

**Comment by Zandario** [comment]
Yeah I resprited them to fit the style of the human cloaks as I felt that fit in-game better, even have the little subtle squid thing on the back like the normal ones have

**Pull request merged**
