### PR TITLE
Bar Fixes

### PR DESCRIPTION
**Pull request by Tename**
Fixes some issues with the bar

## Changelog
:cl:
fix: Lack of hiders in the bar backroom
fix: Lack of Guest pass terminal
fix: Some weird looking windows
fix: Observer spawn
/:cl:

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
You also need to fix the req_access values on the bar backroom door and the bar windoor. Right now anyone can walk in and make off with the shotgun + beanbag rounds. If someone actually managed to put together a lathe somewhere, they'd even be able to make lethal ammo.

**Comment by Tename** [comment]
> Secondary protection windows removed from the bar backroom? Any reason why? The rest of the bar in the renderings seem to have the double set of full windows in addition to external single panes.

They are still there.

**Comment by Tename** [comment]
There that should make them more visible

**Comment by TheFurryFeline** [comment]
Last render had shown they were removed, but this newest commit shows them back now. 👍

**Pull request merged**
