### PR TITLE
Xenolove: One Size Fits All

### PR DESCRIPTION
**Pull request by JennaSilverShark**
Adds all the sprites needed for protean RIGs to be worn on any species that can.

### CODE REVIEW

**Comment by JennaSilverShark** [comment]
I'm crying and screaming right now

**Comment by JennaSilverShark** [comment]
This is the cleanest file addition I have ever done, I have absolutely no way of fixing it right now.

**Comment by Zandario** [comment]
I mean Protean rigs aren't even merged, so this wouldn't do much

**Comment by JennaSilverShark** [comment]
Well the idea was that files could be there so the original pr would just have to code them in

**Pull request closed without merging**
