### PR TITLE
Another reason for a getting mallet

### PR DESCRIPTION
**Pull request by NopeMcHaltman**
:cl: Anonymous
add: Service hounds. Codewise, they're service borgs, but being dogborgs.

I'm failing at IRL and i don't think i will succeed in the code front either.

### CODE REVIEW

**Comment by NopeMcHaltman** [comment]
@deathride58 Please re-review the changes, because i force-pushed commit.

**Comment by deathride58** [comment]
Did you test these changes on a local server?

**Comment by NopeMcHaltman** [comment]
Some basics, including interaction with vendor machines and glass, but so far nothing out of unusual.

**Comment by NopeMcHaltman** [comment]
One thing is, however, i commented out K9 sleeper/dogborg belly.

**Pull request merged**
