### PR TITLE
Adds pepperballs. 

### PR DESCRIPTION
**Pull request by Andromeda-K22**
Adds pepperballs. Because flashrounds are pretty retarded.

These work exactly like pepperspray but in bullet format, with some minor muckery.

### CODE REVIEW

**Comment by CameronWoof** [comment]
Can you say how effective this is? On a plainclothes target, what does one round of this do?

**Comment by Andromeda-K22** [comment]
You ever use pepperspray?

Just as effective.

**Comment by CameronWoof** [comment]
That's insanely overpowered for a ranged weapon. Pepperspray is close-range for a reason.

**Comment by Andromeda-K22** [comment]
Pepperspray is close-ranged because it's a chemical weapon.

Take a look at the survival kit you start with:
*goggles*. And *a breathmask*. Covers eyes, covers mouth.

Pepperspray and pepperballs rendered instantly ineffective.

**Comment by Tename** [comment]
Can't chemistry or science just make chemical rounds? Or is that only for shottys.

**Comment by CameronWoof** [comment]
Creating an objectively more powerful version of something that already exists is powercreep. Security doesn't need to be stronger.

**Comment by Andromeda-K22** [comment]
@Tename Nope. Not even for shotguns, as far as i am aware.

It's not 'objectively more powerful' when it's countered literally almost the same as something that already exists.
Stop being dull about this.

**Comment by CameronWoof** [comment]
Tool with a very small (four?) shot count and limited range that can only be reloaded at specific wall mounts vs. an identical tool with seven shots and a much longer range that can be hotswapped on the go.

Or, could be, but you forgot to put these anywhere a player can access them.

**Comment by Andromeda-K22** [comment]
i m a g i n e t h a t 

Maybe it's because i know they have different uses. It's an implementation and not an addition.
Said tool is literally countered by having glasses and a breathmask.
Same as these. I don't know what your point is aside from 'reee, powercreep.'

Can you clarify it? Please? You're making no sense.

**Comment by CameronWoof** [comment]
I'm saying this is a straight upgrade from pepperspray cartridges. You're making something that's _just_ better.

**Comment by Andromeda-K22** [comment]
It's not really a straight upgrade, when pepperspray never misses but bullets do.

But okay, i'l change how it works and remove the instant stun to please you.

**Comment by CameronWoof** [comment]
Without the stun, what does the new effectiveness look like? How many shots to down an unmasked target?

**Comment by Andromeda-K22** [comment]
Going purely off agony ...?

30 agony with no mask ... 

rubbers do 40 agony and require 3 shots.

Four shots?

**Comment by CameronWoof** [comment]
At this point I would consider them fine, leaning underpowered. I'd seek guidance from maintainers before changing anything else, but bumping it to 40 agony would be fine by me to serve as a non-harmful (but not always as effective, and available from the sec vendor?) alternative to rubbers.

**Comment by Andromeda-K22** [comment]
Four shots unmasked is correct, from my testing just now. 
I will replace the secvendor's flash rounds with these soon.
I would not consider these underpowered due to the blinding effects, and the effects of blindness, like confusion, no matter how brief.

**Comment by CameronWoof** [comment]
You're right, I'd forgotten about that. Thirty seems fine.

**Comment by Tename** [comment]
Tbh I think this would be better as a special cargo order gun or something in the armory.

**Comment by Andromeda-K22** [comment]
This is intended as a drop-in replacement for an awful ammo type.

It's completely nonlethal, as well.

**Comment by Tename** [comment]
I don't know, I just think it is super weird for a .45 pistol to be shooting pepper.

**Comment by Tename** [comment]
I mean wouldn't it only work if they aimed for the eyes? And wouldn't that kind of defeat the purpose of non-lethal.

**Comment by CameronWoof** [comment]
I think the idea is that the rounds have a capsule of pepperspray in them that bursts on contact. The person is engulfed in a spicy cloud and the effects happen from there.

**Comment by Andromeda-K22** [comment]
That is the general idea, yes. When you get hit, the capsule bursts, doing minimal physical harm but disperses a cloud of condensed capscasin. It's not literally pepper.

**Comment by avabee** [comment]
[Just for anyone who thinks this is unrealistic.](https://en.wikipedia.org/wiki/Pepper-spray_projectile)

**Comment by Andromeda-K22** [comment]
More testing has revealed that pepperballs are about 0.5x as effective as rubbers. I'm going to buff them to bring them on par in terms of agony damage or increase their knockdown. 

They also don't work on synthetics.

**Comment by ForFoxSake** [comment]
Make sure it's also printable from an autolathed. (Hacked or unhacked depending on what ever the balance turns out to be.)

(I may want this in so that I can organize pepperspray paintball games with security.)

**Comment by Andromeda-K22** [comment]
I will make sure there's some way to acquire the bullets in game in bulk, be it a really cheap cargo order or something similar. It makes no sense that an autolathe can make pepperballs.

**Comment by ForFoxSake** [comment]
Personally I'd love to see flash and pepper shells be empty reagent containers that mix on impact, so they could be filled at pepper spray stations... Or chemistry for maximum griff.

But I can also see why that'd be a pretty bad idea.

**Comment by avabee** [comment]
Even after this buff, it's weaker than rubbers. Rubbers deal 40 agony damage, and pepperballs deal 30 but weaken. I think it's a fair tradeoff.

**Comment by Andromeda-K22** [comment]
https://citadel-station.net/forum/viewtopic.php?f=38&t=2371&p=8021#p8021

**Comment by Andromeda-K22** [comment]
ding

**Pull request merged**
