### PR TITLE
Buffs Dogborgs Lmao

### PR DESCRIPTION
**Pull request by CameronWoof**
A PR that buffs dogborgs? On Citadel? 

- Removes the water cost for medihound hyposprays. This served only to make them worse than regular cyborgs.

- All dogborgs now start with their water reserves full instead of needing to visit a sink at roundstart every single round. 

- Housekeeping, reduced the maximum water supply of brodogs down to everyone else's level. Since I was in the neighborhood.

### CODE REVIEW

**Comment by NopeMcHaltman** [comment]
:ok_hand:

**Comment by Wilchenx** [comment]
>All dogborgs now start with their water reserves full instead of needing to visit a sink at roundstart every single round.

mfw ripping out my pissing on fire roleplay

**Comment by C0rva1r** [comment]
Looks good

**Comment by nik707** [comment]
Closing due to inactivity, reopen if you'd like it reconsidered.

**Pull request closed without merging**
