### PR TITLE
fix for missing vulp pilot2+captain suit floor icons

### PR DESCRIPTION
**Pull request by VarkaSelyn**
## About The Pull Request

Fix for missing floor sprites in #1274 as noted by @Novacat 

## Why It's Good For The Game

Self-explanatory

## Changelog
:cl:
add: added missing floor sprites
/:cl:

### CODE REVIEW

**Comment by Novacat** [comment]
I just double checked, it looks like only Unathi and Teshari were missing pilot2 sprites. So, I can probably enable the alternate pilot option in the suit cycler, since explorer/pilot cyclers do not allow Teshari at the moment due to the complete lack of voidsuit sprites for those species.

**Comment by peeesh** [comment]
oh nice you actually did the sprites with the captain suit, big thankies

**Comment by VarkaSelyn** [comment]
Yeah I kinda forgot the cycler code would be needed too. I'll look into digging it up and tweaking it later today, shouldn't be hard.

As for the main suit sprite; it probably needs a bit more work/polish (I'm not great at more complicated detail stuff), but I figured it was better to have something that works in the event that it's needed.

**Comment by VarkaSelyn** [comment]
Now let's see if it clears the CI build or if that fucks up on mapgen again because that's 100% relevant _to a code/sprite edit._

**Pull request merged**
