### PR TITLE
Vchat

### PR DESCRIPTION
**Pull request by Zandario**
## About The Pull Request

Continuation/Redone version of #2195
Port of:
https://github.com/VOREStation/VOREStation/pull/6592
https://github.com/PolarisSS13/Polaris/pull/6761
## Why It's Good For The Game
A non-shit chat system thoroughly tested upstream by **both** Virgo and Polaris.

## Changelog
:cl:
add: Vchat
add: Dark Theme 😎 
code: \icon to bicon
/:cl:

### CODE REVIEW

**Comment by Zandario** [comment]
Next Stop on my pain train will be TGUI 4

**Comment by KasparoVy** [comment]
Insanity

**Comment by lolman360** [comment]
oh hey if you get tgui4/assetcache @LetterN can do tgchat/statpanel which is better than vchat

**Comment by Zandario** [comment]
@lolman360 I gave @LetterN **several** months to do this with radio silence. I'm doing things my way, I'm tired of waiting for empty promises to be filled.

**Comment by Zandario** [comment]
Gonna look into some alternatives.

**Pull request closed without merging**
