### PR TITLE
Updates NSB Atlas to use floor emergency shutters, adds a floor emergency shutter subtype 

### PR DESCRIPTION
**Pull request by Dedwolf**
## About The Pull Request

Updates parts of Atlas such as atmospherics and engineering entrances, and botany entryway.
Adds an emergency shutter subtype thats embedded in the floor for future map use and updates Atlas to use floor emergency shutters instead of full size doors.

## Why It's Good For The Game

As above

## Changelog

:cl:
tweak: NSB Atlas changes and improvements
/:cl:

### CODE REVIEW

**Review by TheLordME — CHANGES_REQUESTED** [review]
1. Atmoize this PR, its 2.5 changes in one(I am not sure what you are doing on the maps exactly, since map diff cant run with the issue mentioned in 3.)
2. I dont think there should be a animated icon state for cameras that phases them out of existance for a frame
grafik
3. You have some compiling errors on surface 2

**Review by TheLordME — CHANGES_REQUESTED** [review]
The floor shutters arent working
And whats your issue with the not rectangleness of hydroponics?

**Review by TheLordME — CHANGES_REQUESTED** [review]
grafik

**Review by timothyteakettle — CHANGES_REQUESTED** [review]
yeah uh can we have firelocks facing the right way

**Pull request closed without merging**
