### PR TITLE
Ports Nanako Cooking from Aurora

### PR DESCRIPTION
**Pull request by avabee**
Oh, boy. This is a doozy.
Adds Aurora's cooking system. I'm too lazy to write a proper PR description but I can answer any questions people have.
Credit: NanakoAC for the cooking system.
Lohikar for some miscellaneous fixes, and probably a few other people too.
Synnono for a bunch of the foods, as well as their sprites and a good amount of coding.

This could only be modularised so much without causing issues. :woman_shrugging: I tried my hardest.

### CODE REVIEW

**Comment by CameronWoof** [comment]
A general overview of what Nanako Cooking is would be nice. Is this a bunch of new recipes, a new way of cooking?

**Comment by avabee** [comment]
It's both. Ovens and fryers now work like the microwave, but also have special trays/baskets that can be inserted and removed with things on them. There's also a crapton of new recipes.

**Comment by avabee** [comment]
Note that you can still use the oven to just bake things, or produce variable food items, to my knowledge. This was specifically kept in when it was originally implemented, IIRC.

**Comment by nik707** [comment]
So being this is  a fairly large change, I'd really like to have some kind of concise list of the changes for players who play cook so they can easily see what they need to relearn

**Comment by avabee** [comment]
- Cooking now uses several machines to make recipes. Microwave, oven, deep fryer.
- Recipes have been redone to reflect this.
- Adds a reagent called Space Spice (used in Synnono's food recipes mostly, prevents recipe conflicts)
- New foods! Lots of them.
- You can cook using held mobs. Also, mouse/ratburgers.

I can dump the recipes if you'd like.

**Comment by avabee** [comment]
Not ready, need to fix reagent issues.

**Comment by avabee** [comment]
Ready for review. All features work and are ready to be added.

May want to hold off on merging until I get permission to port some of these food items/sprites from the person who made them.

**Comment by avabee** [comment]
image
List of all (should be all) recipes in alphabetical order, including where/how they're made. Tell me if anything important is missing.

**Comment by avabee** [comment]
Wiki is ready to be updated as soon as this is merged.

**Comment by avabee** [comment]
Merge-ready.

**Comment by lbnesquik** [comment]
Lot of work man. Nicely done

**Pull request merged**
