### PR TITLE
Livin' In a Box/Adds Large Cardboard Box.

### PR DESCRIPTION
**Pull request by Jaybirdnerd**
## About The Pull Request

Adds a craftable closet shaped like a large cardboard box so now you can hide in the box. The sprite is sourced from the box closet on main, but the code was completely re-written by myself and Grins so it's a craftable locker.

## Why It's Good For The Game
You can make a box and also hide in it, it's more or less just a minor fun thing.

## Changelog
:cl:
add: Added Large Cardboard Box/ported cardboard box *(kinda)* from Main.
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
allow movement in the box or no balls

**Comment by Jaybirdnerd** [comment]
> allow movement in the box or no balls

You don't know how bad I want to, but I have like zero idea how to.

**Comment by deathride58** [comment]
inject knowledge of the entire citrp source code into your veins and Learn how to,

**Comment by Jaybirdnerd** [comment]
> inject knowledge of the entire citrp source code into your veins and Learn how to,

TIME TO MAINLINE THE DRUG THAT IS THIS CODEBASE

**Pull request merged**
