### PR TITLE
Fatigues & Jackets Fashion Tweak/Additions

### PR DESCRIPTION
**Pull request by VarkaSelyn**
## About The Pull Request

Enables plain grey fatigues for loadout selection as they no longer have armor values and the department variant fatigues are grey, adds grey and tan military jacket recolors to match, and changes the military jackets to use a selector to save a little space. This _will_ break any existing loadouts that use them, but I doubt that'll be a huge dealbreaker (and is easily disabled).

## Why It's Good For The Game

I'm one of those people that always strongly supports more fashion options, so my opinion is inherently biased, but allowing for more consistency (now you can have tan fatigues + tan jacket, etc.) _and_ customization is always good.

## Changelog
:cl:
add: Added grey fatigues to loadout choices
add: Added grey and tan military jacket options
tweak: Changed military jacket selection to use a selector
tweak: Renamed the badged + dark green military jackets for selector compatibility
/:cl:

### CODE REVIEW

**Comment by Novacat** [comment]
Why not toss these upstream?

**Comment by VarkaSelyn** [comment]
The jackets and selector could be changed, but the grey fatigues have 10 melee armor (same as Sec uniforms) _except_ on Citadel. Adding them to loadouts _everywhere_ would give _everyone_ access to that.

**Comment by Novacat** [comment]
Perhaps just push the sprites and code upstream, without adding them to loadout?

**Comment by VarkaSelyn** [comment]
You're implying I have any clue what I'm doing with github half the time and can figure out how to do that. :v

**Comment by peeesh** [comment]
uhh i think grey fatigues exist as a separate name iirc. utility uniform grey?

**Comment by Novacat** [comment]
Just need to make a repository for either Virgo or Polaris, depending on how far you want to push it upstream. Works the same as here. Then just copy-paste your changes from your CitadelRP repository into that, minus code/modules/client/preference_setup/loadout/loadout_suit.dm

**Comment by VarkaSelyn** [comment]
@peeesh I thought that was just the standard greytide jumpsuit, but you're right. they're the same in terms of appearance but have different names for whatever reason. weird.

I'll probably close this for now and roll back to just the jackets + selector, then. Maybe see if I can get this navy jacket looking good as well.

**Pull request closed without merging**
