### PR TITLE
reasserts that chemical dispensers shouldn't be walked through

### PR DESCRIPTION
**Pull request by silicons**
density = 1

### CODE REVIEW

**Comment by lolman360** [comment]
intended, it's a feature so that you can put em' on tables

**Comment by silicons** [comment]
@lolman360 they're literally the size of normal machines, this for soda/booze dispensers or?

**Comment by VailTheWolf** [comment]
Dispenser 2 is the dm for Soda/booze dispensers. You can't phase through the medical chem dispensers at this time, so this PR isn't needed.

**Comment by VailTheWolf** [comment]
I stand corrected on the files, but either way chemical dispensers are not passable, soda/booze are, in-game at this time.

**Comment by silicons** [comment]
why the fuck...

**Pull request closed without merging**
