### PR TITLE
Species Id rather than Name for checks

### PR DESCRIPTION
**Pull request by TheLordME**
## Why It's Good For The Game
should have no impact on the game

## Changelog

:cl:
code: changed a bunch of species checks to use ID rather than name
/:cl:

### CODE REVIEW

**Comment by TheLordME** [comment]
No functional tests have been done

**Review by Zandario — APPROVED** [review]
Code looks correct, just needs testing.

**Comment by TheLordME** [comment]
tested Emotes, adherent pylon and vox clothing superficially should be good to merge

**Review by Captain277 — APPROVED** [review]
Files haven't changed since initial approval.

**Comment by TheLordME** [comment]
> Files haven't changed since initial approval.

It also didnt discard zands review afaict

**Pull request merged**
