### PR TITLE
AFW: Summer Catalog

### PR DESCRIPTION
**Pull request by Captain277**
_The **Azure Fashion Warehouse** is proud to announce its summer catalog! Enjoy a nice swim in the cow print bikini! It pairs perfectly with our cowbell collar! It may be summer, but space is always cold, so be sure to purchase your very own Ronin jacket. If simple leather is more your style, enjoy our tailored jackets. Equipped with the latest consumer grade nanotech, all of our clothes are a guaranteed fit, no matter the size! Thanks to your enthusiastic purchasing of our chromatic underclothes, the **AFW** is proud to announce our foray into the more complex field of chromatic outerwear! Try out a leotard that truly expresses how you feel, or flaunt what you've got with a freshly dyed miniskirt! For the discerning client, the Verglas dress has been crafted from long forgotten blueprints, brought to you straight from the Eridani Sector! No one has worn a dress like this in over half a decade! Very avant-garde!
In partnership with the **Cyan Consumables Corporation**, we are also proud to announce the introduction of a splash of color to your summer fun! Bring the rainbow with you without ever needing the rain when you try out one of the new Crayon Burger recipes! If you'd like to cool off with a nice drink, the **Cyan Cowgirl** proudly attests that a sabotage attempt by the **Snake Oil Salesman** has been sussed out and corrected, and it is now safe to mix and drink The Best Boy and Outlaw drinks once again! We hope to see you again in the Fall, and remember, here at the **Azure Fashion Warehouse**, everything's a perfect fit!_

---

1. _Adds two new jackets: A slim brown leather jacket, and the heated Ronin jacket._
**Why:** The current leather jacket sprites are offset to a very strange degree. After testing, the slim jacket should establish a baseline for better leather sprites. The Ronin jacket is based on a solid aesthetic design, but also has functionality built in for the coming snow map. As with the slim jacket, eventually different styles/logos based on this jacket's "skeleton" should be rolled out.

2. _Adds one new swimsuit (cow print bikini), two colorable cosmetic clothing items (colorable leotard and fashionable miniskirt), and one new dress (Verglas dress)._
**Why:** In the interests of broadening player customization, I am continuing to experiment with colorable clothes options, such as this version of the leotard and the new miniskirt. The dress was a requested reconstruction based on an old SS13 screenshot. The swimsuit has no utility, beyond the obvious cosmetic reasons.

3. _Adds one requested Donator Item._
**Why:** The Donator mentioned that they had the requisite tier, but had either never asked for their item, or had never asked to have it implemented. I crafted the sprite and have included it in the relevant files. Please confirm Donator status is up to date before merging.

4. _Adds crayon hamburgers._
**Why:** This recipe requires one crayon of any traditional color (Meaning all crayons except for the Mime's), including the rainbow crayon, be added to the standard burger recipe. The result will be a burger with a colored patty. This request comes from Tiake, regarding similar colorable burgers existing on Main. Trent assisted me in locating Main's sprites, but I opted instead to take the sprites in a different direction, as can be seen here.

5. _Fixes two broken drink recipes._
**Why:** Reports regarding two of the drinks from my prior PR: 'The Best Boy' and 'The Outlaw' not working have been addressed and rectified.

### CODE REVIEW

**Comment by Zandario** [comment]
Always great to have more spicy clothes! (even tho no Tesh/Vox sprites :< )

**Comment by Captain277** [comment]
Oof. Trying to leave a reply via mobile is weird. Don't worry on the Tesh front. I have a map update I'm working on as well this week, but after it clears and some of the active PRs get merged, I'll have the air warmer sprites for the Vox and Tesh to do, so I'll be in a good spot to do Tesh outfits.

**Comment by Ghostcoffeee** [comment]
The uniform and suit sprites that you've added have no side facing or back facing sprites, only the front facing ones

**Comment by Captain277** [comment]
Upon further review, the sprite states for the relevant .dmis were swapped. It will be corrected shortly.

**Pull request merged**
