### PR TITLE
Hardsuit-Mounted Armblades

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
Hardsuit-mounted arm-mounted blades. Forcediv 0.4, blockchance 30 (against melee only).
Sprites borrowed from CEV-Eris, God bless.
Module:
image
Item:
image
On Mob:
image

Also readds the buckknife sprite for combat knives that was rolled back in the hardsync.
Also also makes whetstones have their kinda sorta bad sprite. Because otherwise they wouldn't have one.
Also also also readds the fancy kevlar upgrade kit sprites that were lost in the sync. Thanks, @Michiyamenotehifunana.
## Why It's Good For The Game
haha funny knife hand
## Changelog
:cl:
add: Arm-mounted blades! Requires a hardsuit and the arm-mounted blade module.
fix: Whetstones, combat knives, and kevlar upgrade kits have their funky sprites again.
/:cl:

### CODE REVIEW

**Comment by BobJogaIsForkinBanned** [comment]
Honestly better than the one i did on Skyrat. Good!

**Comment by yourdoom9898** [comment]
Any chance we can get a "deluxe hardsuit machete" or should we just use whetstones

**Comment by Captain277** [comment]
The ability to swap out the blades would be exciting. Maybe even some ability to make it an energy weapon. I'm just happy to see this idea executed at all.

**Comment by Hatterhat** [comment]
> 
> 
> Any chance we can get a "deluxe hardsuit machete" or should we just use whetstones



> 
> 
> The ability to swap out the blades would be exciting. Maybe even some ability to make it an energy weapon. I'm just happy to see this idea executed at all.

yeah just use sharpening kits that'll work for giving you a fancier (read: more harmful) blade

**Pull request merged**
