### PR TITLE
[DONE] Plasmemes/Phoronoids

### PR DESCRIPTION
**Pull request by peeesh**
likely my biggest project yet.

the goals:
 - plasmamen functioning mechanically, with containment suits and internals, plus their own language
 - plasmaman lore (not here)

sprites will come from paradise, since they're pretty comfy.

whats done, mechanically
- [x] selection in character setup
- [x] species traits/language 
- [x] atmosphere combustion (credit to @Andromeda-K22 for the lovely work on this)
- [x] suits, and stopping the combustion
- [x] final check over, testmerge?

all jobsuits done. if theres any sprite issues notify me, i was half awake doing them

CHEATSHEET FOR CHANGING ICONS WITH VAREDIT
helmet - plasmaman_helmet(jobname) without the brackets. no capitals
suit - plasmaman_suit(jobname)

**EXPLORER PLASMEME README:
!!!
DONT GO TO V2
YOU WILL BAKE
I CANT FIND A WAY TO FIX THAT
!!!**

### CODE REVIEW

**Comment by peeesh** [comment]
im like 80% these boys are ready for a testmerge now, unless you REALLY need me to do the special suits with armor and shit

**Comment by peeesh** [comment]
am i a big boy yet

**Comment by peeesh** [comment]
WAIT NOT YET

**Comment by realbuffalowing** [comment]
hey, that's pretty good

**Comment by pireamaineach** [comment]
Why did you port /vg/'s suits instead of /tg/'s uniforms?

**Comment by pireamaineach** [comment]
Ah fuck you used the skinbone model too.

**Comment by pireamaineach** [comment]
I mean the skinbone model directly contradicts plasmamen having their own language. It's a relic from the original /vg/ lore that they're human survivors of "phoron" fires.

**Pull request merged**
