### PR TITLE
Replaces the merc heavy armor vest in a null crate with a plate carrier and helmet

### PR DESCRIPTION
**Pull request by Hatterhat**
Green vest has no fashion. Tacticool plate carrier and associated helmet does. Literally my only excuse for this dumbass PR.

### CODE REVIEW

**Comment by Keekenox** [comment]
Fake and gay

**Comment by Keekenox** [comment]
Can you show pictures of the two? I'm curious

**Comment by Hatterhat** [comment]
eventually (tm)

**Comment by Hatterhat** [comment]
image
dumb asshole man shows off contraband
image
helmet + platecarrier (arm/leg guards are removable due to modularity)
image
green vest (does not have cool helmet)

**Comment by Hatterhat** [comment]
im retarded

**Comment by NopeMcHaltman** [comment]
And a fucking Travis claims yet another victim.

**Pull request closed without merging**
