### PR TITLE
Tether Remap Part 3 of X: Surface Tether: Attempt 2

### PR DESCRIPTION
**Pull request by CharlesWedge**
## Time to give the surface some love.

With the Tether consolidated down to 6 Z levels finally. I can go ahead and add in the improvements for the Surface Tether Map. Where Tether was once surrounded by a boring flat plain it is now surrounded by significant mountains, that contain several small static points of interest to help make tether feel like a real place. Included is the tram line leading to the tram tunnel, and an abandoned construction tram on the tracks. In addition several changes have been made to help encourage mobility in the exterior of the tether map. Fullish changelog below.

## Changelog
:cl:
Mountains: Tether is now surrounded on 3 sides by rocks much like how the Tether plains, Solar and Mining Z levels already are. You can climb to the second Z level of these mountains using stairs around the map. Z level transition areas are now flavored as tunnels through these mountains. A few static POIs have also been added in these areas.
Tram Line: The tram line no longer magically come from a secret underground tunnel to get to and from tether. Now it has explorable tracks outside the tether that lead into a tunnel. Included with is stairs allowing people to easily cross the tracks by going above them.
Virology: Has been downsized to make room for the tram line. Viro's waste vent has been fenced off with warning signs around it so crew know it hazardous.
Cafe: Now has more apparent access to the Tram Station, creating yet another Tram Cafe. It also has more glasses then it one did.
Changing Room: Now has two lockable changing rooms with mirrors.
Surface 1 Maint: modified to remove many 1 wide halls. Added maint access to tram station. Added Maurice to Trash pit. Added Bottle of Nothing to the Mime's Office.
Heads of Staff Meeting Room: Now has a visible table. 
Former Chapel: Now has the remnants of some furniture. Noddle has been removed from old chapel in preparation for his move to explo.
Atmos: The Station 2 catwalk formerly only accessible from main can now be reached from atmos itself.
Security Substation: Enlarged to avoid the 1 wide hall between it and medica.
Xenobio Exterior: A system of stairwells and catwalks now provide easy access from the level 1 surface to the large empty area of exterior space near the pool. This should hopefully make walking around that area easier.
Bar Backroom: Removed Ugly half assed buggy, out of place Eris Floor, added ATM and Cig machine, tweaked table to be accessible without having to comb over the table.
Service Hall: Has been removed where it stock out into botany. The Kitchen's animals now reside in a glass ben and botancy has more green space. including 3 more plantable soil patches.
Sauna: Redesigned. It no longer has windows facing the exterior and is only accessible from the Showers. It is also now its own area.
Deck 3 Stairwell: Now has a glass door facing security rather than a maint one.
General: Disposals in some areas have been despaghettified.
General: Enforced Area Sanity (You will no longer find pockets of "Outside Surface" in areas  surrounded by maint.
/:cl:

### CODE REVIEW

**Comment by QRQ-2817** [comment]
But the important question - did you add steam to the ENTIRE sauna room and not just over the water?

**Comment by Captain277** [comment]
Sauna turfs are exterior, meaning it rains on them. There are also two turfs on the Z1 cafe next to the tram station - underneath two windows - which count as exterior for weather purposes as well.

**Comment by Keekenox** [comment]
I am really not that big of a fan of the sauna redesign, and the design seemed like it made a lot more sense the way it was. It had tintable windows and it seemed cozy to have it round. Also currently how it is, the steam in the air is covering more than the water tiles in a way that looks weird.

**Comment by nik707** [comment]
> I am really not that big of a fan of the sauna redesign, and the design seemed like it made a lot more sense the way it was. It had tintable windows and it seemed cozy to have it round. Also currently how it is, the steam in the air is covering more than the water tiles in a way that looks weird.

That and now the sauna is just a fucking steel box. It feels like a prison cell. Tintable windows are waaaay better.

**Comment by Captain277** [comment]
I also dislike the new sauna, in comparison to the old one.

**Comment by nik707** [comment]
Moreover, the glass on the tram line that gets magically deleted is lazy and a bit un-needed. If people abuse the tram lines they can simply be punished for it. If you're gonna babyproof it, use windoors and put the windows on the right side so we don't have to somehow justify why the tram literally smashes through 15 panes of glass

**Comment by CharlesWedge** [comment]
> Moreover, the glass on the tram line that gets magically deleted is lazy and a bit un-needed. If people abuse the tram lines they can simply be punished for it. If you're gonna babyproof it, use windoors and put the windows on the right side so we don't have to somehow justify why the tram literally smashes through 15 panes of glass

Its not so much a matter of abuse as there have been multiple incidents of people simply lagging or mem-leaking into it. Nevertheless I made the changes you suggested.

**Comment by Keekenox** [comment]
> > Moreover, the glass on the tram line that gets magically deleted is lazy and a bit un-needed. If people abuse the tram lines they can simply be punished for it. If you're gonna babyproof it, use windoors and put the windows on the right side so we don't have to somehow justify why the tram literally smashes through 15 panes of glass
> 
> Its not so much a matter of abuse as there have been multiple incidents of people simply lagging or mem-leaking into it. Nevertheless I made the changes you suggested. As for the Sauna, it was made in consultation with people who actually gave me feedback on the Mapping RP channel, who by in large didn't enjoy the windows and preferred the current design now in use.

The thing is, the previous design with the windows was never an issue because you could tint them. Moreover this allowed you to tell when the sauna was in use by seeing that it was tinted. Also the previous design of having the square pool in the corner worked a lot better.

**Comment by nik707** [comment]
I'll come out and be the bad guy by saying those people are fucking wrong. Tintable windows look better, feel better, give the same use, and MORE utility on top of that.

**Pull request merged**
