### PR TITLE
[RTM] Language Flags Clean up, _vr merging and speech_verbs can be lists now

### LINKED ISSUE #2940: ,t for vernal is not working
## Round ID:
whatever the round was on as of writing this, the ID is gone from status tab

## Testmerges:
#2937: 'fixes lavaland ' by silicons at commit dd88eb15a7
#2936: '"the codebase never ceases to amaze me with its amazing ideas and piss-poor implementation": air injectors.' by silicons at commit ae59d0f413
#2930: 'powercreeps engine smes to have 3 more normal coils and a transmission coil so it isn't literal suicide to try to run R-UST without being a tryhard and rewiring another SMES' by silicons at commit d4a6e79be2
#2929: 'Adds a message for everyone around you when you examine something. Also adds a preference to not show other people looking at the booba.' by FreeStylaLT at commit 0e88d47534
#2927: 'Spaceproofs Cap Armor' by Nepnya at commit 311e66005f
#2924: 'Captains have pockets too' by Nepnya at commit 9527095c1f
#2922: 'fixes microwave cleaning' by silicons at commit 3813065398
#2921: 'fine you can have your sizechems back (given that this optimizes size fetish mechanics enough to not literally have people killing the server with their erp)' by silicons at commit 7d624f817a
#2919: 'unedited webedit change - you can no longer telekinetically will tesharis onto people' by silicons at commit 31693d5530

## Reproduction:
just try to speak in vernal without setting it up as a default language

### PR DESCRIPTION
**Pull request by TheLordME**
## About The Pull Request
As the title says, changes flags to improve readability
Merges two _vr files.
speech_verbs can be lists now instead of just one string

## Why It's Good For The Game
Refactoring of code, increases readability
resolves #2940

## Changelog
:cl:
spellcheck: Fixed a typo in the squeakish desription.
fix: Pan-Slavic is no longer the language of a non existant fraction.
code: Language Prefixes differate between upper and lower case
code: Language 'verbs' can be lists now.
refactor: Language Flags are bit shift style now.
refactor: Two language related _vr-files merged into their respective Parents.
/:cl:

### CODE REVIEW

**Comment by TheLordME** [comment]
The PR is ready for Testmerge

**Comment by TheLordME** [comment]
Current TODO:
Gibberish protection needs prefix removal.

**Comment by TheLordME** [comment]
Its still fine to test merge,
just dont merge fully until I get that todo done

**Comment by TheLordME** [comment]
All updates/todos completed

**Comment by nik707** [comment]
Ok a few things here.
1: This seems to break radio emotes. [Common] Ty Clarke !snibbers. Notice the exlamation.
2: What's with the changing of machine understands vars and whitelist vars with no explanation in the PR text

**Comment by TheLordME** [comment]
The machine understand flags were changed due to the _vr file merge

**Pull request merged**
