### PR TITLE
the funniest PR i have ever made

### PR DESCRIPTION
**Pull request by nik707**
## About The Pull Request

adds pickles as a simple mob alongside a smite to pickleize a player

## Why It's Good For The Game

it's honest to god the funniest shit i've ever seen

## Changelog
:cl:
add: pickle
add: picklesmite
/:cl:

### CODE REVIEW

**Comment by buffyuwu** [comment]
he turned himself into a pickle

**Comment by silicons** [comment]
why?

**Comment by nik707** [comment]
Captain didn't say no

**Comment by buffyuwu** [comment]
todo: call me to sit down with you and fix this @nik707

**Pull request closed without merging**
