### PR TITLE
adds a new lounge to station level 1

### PR DESCRIPTION
**Pull request by nik707**
## About The Pull Request

This adds a new pretty lounge to the first level of the station. This means there's now a proper eatery on the upper section, meaning you don't have to elevator down to the rather bare bar. It's a little more comfy, including some private tables and a nice stage for... performances. It's had some minor testing but all bugs should be reported here or to me on discord nicc#3604 thanks

[https://i.imgur.com/qrHwi49.png](url)

## Why It's Good For The Game

No more going to the surface to get food that isn't from a vending machine.

## Changelog
:cl:
add: Added a new lounge and areas to go with it

/:cl:

### CODE REVIEW

**Comment by Keekenox** [comment]
Needs a stripper pole.

**Comment by nik707** [comment]
then add one 4head

**Comment by GrayRachnid** [comment]
Cold room APC unpowered.
No lights in hallway leading up to lounge
You removed a wire knot that was going to the z-level above in the maint tunnel.
No fire alarm/newscaster/intercoms.

**Comment by nik707** [comment]
> Cold room APC unpowered.
no it isn't, the shit isn't charging cus it's on a  fresh local server
> No lights in hallway leading up to lounge
thank
> You removed a wire knot that was going to the z-level above in the maint tunnel.
it's still there
> No fire alarm/newscaster/intercoms.
minor but sure why not

**Comment by KillianKirilenko** [comment]
guess it works as a concept, but not sure I'm sold on this particular location as that space might be more useful for exploration reworks

for a more drastic rework, why not move the library down to station 1 where the abandoned library is, move hydroponics/botany over the fire shelter (maybe removing that entirely, because it's basically useless and I doubt most people even know it *exists*), and then put this lounge in where the current library is?

**Comment by nik707** [comment]
Library and RND changes are already in the works, and tbh exploration could just use much of the dead space to the right

**Comment by nik707** [comment]
To Do Tomorrow:
Disposals bin, add something to the hallway end

**Comment by nik707** [comment]
This is RTM, One known issue: The southern status display shows on both sides of the wall, I'm leaving it this way so the hallway also has a status display

**Comment by Zellular** [comment]
The place itself is nice, but depending on its intended use it may be a bit too gloomy.
Windows to space or some thing other to open up the room slightly could make it miles better.

**Comment by nik707** [comment]
There isn't a place to window to space, it's sandwiched between engineering and the hangar. The idea of it is that sorta "seedy" dark backroom of a night club where the "fun" stuff happens. Generally not gonna want windows there

**Pull request merged**
