### PR TITLE
adds 9 new bedsheets to the game (and loadout)

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
image

sprites made by DJKouta

## Why It's Good For The Game
i really like bedsheets

## Changelog
:cl:
add: adds 9 new bedsheets
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
my editor did a thing
ill fix it soon

**Comment by timothyteakettle** [comment]
what crime did i commit to the linters

**Comment by TheLordME** [comment]
I personally find bedsheets in the loadout to LRP to approve this PR

**Comment by timothyteakettle** [comment]
not sure i agree, it's uh, just a bedsheet lol
.. people lay under them.

**Pull request closed without merging**
