### PR TITLE
Voidsuits & Jackets, Round 3

### PR DESCRIPTION
**Pull request by VarkaSelyn**
## About The Pull Request
1) Adjusts the visors and colors of the Vulp Construction and HAZMAT Voidsuit Helmets to be consistent with the suits and each other. Also patches a big hole on the back of the neck.
2) Recolors the industrial hardsuit helmet to blend better with the suit body. Note that the voidsuit helmets need to be refitted seperately from the suit in order to change colors if you're refitting type *and* species at the same time.
3) Adds a white version of the military jacket to the selector (as previewed in current icon) this will probably be the last variant unless anyone requests one specifically.
4) Finally, there's also new vulp helmet for security's hazard hardsuits. It's just a modified security rig helmet and I'm not a huge fan of it, but it's better than clipping, kinda.

Preview images:
helmet-comp (industrial hardsuit helmets)
HAZ/CON Helmets changed (see further down)
vulphazard (new security 'hazard' hardsuit helmet)

## Why It's Good For The Game
Additional fashion, and a couple of fixes for things that were bugging me.

## Changelog
:cl:
add: added a white version of the military jacket to the selector.
add: added custom vulp security hazard hardsuit helmet.
tweak: tweaked sprites for vulp hazmat+construction voidsuit helmets.
tweak: minor sprite tweaks to a couple other voidsuit helmets to fix minor mistakes.
tweak: tweaked sprites for vulp industrial hardsuit helmet, will now blend better with the main suit.
fix: fixed refitted exploration suits turning into the wizard style in-hand.
/:cl:

### CODE REVIEW

**Comment by AnalWerewolf** [comment]
Can't say I'm a fan of the hazard hardsuit helmet. Looks far too much like angry eyes, kind comes off as a bit goofy.

**Comment by VarkaSelyn** [comment]
Yeah I'm not exactly sold on it either, but the standard human helmet model has a kind of horizontal "bar" that isn't easy to replicate on a muzzle-adapted helmet and I wanted to avoid it being red and edgy as with the security void/hard suit helmet. It doesn't help that I'm not the best artist; I'm mostly just kind of... bashing shit together, really.

If you (or someone else) wants to take a shot at making an alternative I can roll it into this PR.

**Comment by Tename** [comment]
I like the original engineering hazmat and construction hsrdsuitd more, the eyes just look strange.

**Comment by VarkaSelyn** [comment]
@Tename ...you know, looking at it again, this is even more headache-inducing. The HAZMAT suit's side-on sprites have a more consistent visor design compared to the front-on sprites but don't match at all color-wise (the suit body is yellow, the helmet body is a mismatched bronzeish color), and the Construction suit's side-on sprites have really weird visors but colormatch the suit perfectly.

I'm going to see if I can blend the two together more elegantly to construct better versions with consistent colors and visors.

**Comment by VarkaSelyn** [comment]
Hokay. This ought to work better on both counts.
con-suit-shazmat-suit-s
con-suit-ehazmat-suit-e

It's still kind of incongruous with the standard engineering voidsuit helmet, but it's more distinct and coherent.

**Comment by Tename** [comment]
Perhaps making the eyes for the side sprites a bit bigger, it looks like it would be difficult to see out of

**Comment by VarkaSelyn** [comment]
Hmm... it doesn't fit the head very well anyway, needs to be extended for the muzzle a bit. I'm going to need to make a couple more adjustments.

**Pull request merged**
