### PR TITLE
Fixes the default Mapmerge2 config

### PR DESCRIPTION
**Pull request by Tename**
## About The Pull Request
Fixes the maps file path changing it from _maps to maps
Disables convert to TGM

## Changelog
:cl:
fix: Changes the map path on the Mapmerge2.bat files from /_map/ to /map/
fix: Disables convert to TGM format by default.
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
Why disable TGM conversion?

**Comment by Tename** [comment]
> Why disable TGM conversion?

I'm pretty sure we don't use it on RP considering Virgo doesn't even use map merge and the original map files from them, I just wasnt sure if it would cause issues or not.

**Comment by KillianKirilenko** [comment]
Uhhh no. #1519 updated mapmerge - it should already have fixed this, and TGM is now **MANDATORY** or else MapDiffBot will reject all of your changes.

**Comment by Tename** [comment]
Alright

**Pull request closed without merging**
