### PR TITLE
why are there 3 fucking donator locations but the unmarked one is right smh my head

### PR DESCRIPTION
**Pull request by Funkeronipasta**
## Changelog
:cl:
add: Added LectroNyx's donator fluffitem
imageadd: Added icons for LectroNyx's donator fluffitem
/:cl:

### CODE REVIEW

**Comment by lectronyx** [comment]
Tried to fix the off pixels, but... I don't think I have permissions to edit this PR. Shit. The 2 dark gold pixels should be the same yellow they are on the upward facing one.
image

**Comment by Funkeronipasta** [comment]
Oh yeah, give me a moment

**Comment by Funkeronipasta** [comment]
Ding

**Comment by lectronyx** [comment]
> Ding

I see you fixed it here, but... it's not showing at all on the server. Wtf?

**Comment by Funkeronipasta** [comment]
It should be in the Suits and Overwear tab.. It was working fine on the local, and your ckey matches, so I'm not sure

**Comment by lectronyx** [comment]
looks like the testmerge wasn't updated...?

**Comment by Funkeronipasta** [comment]
Nah, it shouldn't really have affected it - the latest commit just fixes the colour and positioning

**Pull request merged**
