### PR TITLE
Map Adjustments for Surface 3 & Station 1

### PR DESCRIPTION
**Pull request by Enzo-Leon**
## About The Pull Request

Adding and adjusting locations on the map
Asterioid-1 Library: https://cdn.discordapp.com/attachments/483788016977182740/731613633653506128/unknown.png
Surface-3 Bridge/Sauna/Lounge - https://cdn.discordapp.com/attachments/697679518630019133/731619142309904514/unknown.png

## Why It's Good For The Game

QOL and hang out areas. Also something not combat for once.

## Changelog
:cl:
add: Sauna on Surface-3 w/ bridge & lounge
add: Library back to Asteroid-1
/:cl:

### CODE REVIEW

**Comment by Enzo-Leon** [comment]
This is also removing a lost of posters that I noticed were causing runtimes when testing local builds. Seeing if removing these helps the server out somehow 🤔

**Comment by Zandario** [comment]
Big thonk indeed, though it's weird posters would do that? But knowing BYOND, I wouldn't be surprised...

**Comment by yourdoom9898** [comment]
Hooray, a second bridge for when the first one is qdel() by a Tesloose

**Comment by Enzo-Leon** [comment]
TO-DO BEFORE FULL MERGE: Update nanomaps for station once layout is good to go.

**Comment by yourdoom9898** [comment]
Suggestion/Nitpick for the sauna:

1: Could we get more bench seats, you could make a U shape starting at the top and bottom parts of the right side of the pool, and it would vastly increase the number of seats, since 4 gets cramped quickly unless people start lap sitting
2: Can we make the benches wood instead of metal? Entirely a nitpick, but metal benches in a room designed to get hot sounds like a great way for crew injury, even if not mechanically represented

**Comment by Enzo-Leon** [comment]
Both points have been added to the sauna as these were good points (and make sense in a HRP setting). U shape bench is added, but with tables on the corners for placing stuff down.

Areas have been added. Once layout has been set for a day+. Nanomaps will be updated and full merge good to go.

**Pull request merged**
