### PR TITLE
Changes to engine templates

### PR DESCRIPTION
**Pull request by Auris456852**
## About The Pull Request
Adjusts the engine templates so that certain bugs are no longer present. Namely, everything wrong with the R-UST and duplicate radiator windows. Now it isn't just the SM that has radiator window shutters, as well.

## Why It's Good For The Game
Now, I know there was a ban on changing the layout of the map, so changing the layout of the pipes in the R-UST might be a bit of a stretch, but hear me out. Fixing the R-UST by means that you rightfully shouldn't need to take ICly every round fucking sucks.
The other things are just a bit of icing on the cake. Feel free to yell at me if something breaks, though.
## Changelog
:cl:
fix: R-UST's hot loop now is set in the right direction and the wiring works.
fix: No more duplicate borosilicate engine windows.
tweak: Every engine submap now has radiator window shutters.
tweak: Removes the rogue button in the middle of the R-UST pipes.
/:cl:

### CODE REVIEW

**Comment by Captain277** [comment]
The Linter checks say Map Merge wasn't run on this, please give it a look.

**Comment by Auris456852** [comment]
Think that's that out of the way... But now we have another issue.

**Comment by LetterN** [comment]
```
[2021-04-19T14:48:39] Runtime in reader.dm,352: list index out of bounds
  proc name: parse grid (/dmm_suite/proc/parse_grid)
  src: /dmm_suite (/dmm_suite)
  call stack:
  /dmm_suite (/dmm_suite): parse grid("\n", "Jm", 66, 34, 13, 0, 2, /list (/list))
  /dmm_suite (/dmm_suite): load map impl(_maps/submaps/level_specific/c..., 66, 34, 13, 1, null, null, 2)
  /dmm_suite (/dmm_suite): load map(_maps/submaps/level_specific/c..., 66, 34, 13, 1, null, null, 2)
  Research Facility (/datum/map_template/submap/level_specific/class_h/AuxiliaryResearchFacility): load(the low desert (66,34,13) (/turf/simulated/floor/outdoors/beach/sand/lowdesert), 1, 2)
  seed submaps(/list (/list), 140, /area/poi_h/unexplored (/area/poi_h/unexplored), /datum/map_template/submap/lev... (/datum/map_template/submap/level_specific/class_h))
  ExoPlanet - Z2 Planet (/datum/map_template/triumph_lateload/away_h_world): on map loaded(13)
  ExoPlanet - Z2 Planet (/datum/map_template/triumph_lateload/away_h_world): load new z(0, 2, /list (/list))
  Mapping (/datum/controller/subsystem/mapping): loadLateMaps()
  Mapping (/datum/controller/subsystem/mapping): Initialize(533024)
  Master (/datum/controller/master): Initialize(10, 0, null)
  ```

**Comment by LetterN** [comment]
it probably turned into null? Dunno how to banaid that

**Pull request merged**
