### PR TITLE
NanoTrasen Ship Order: NSV Triumph 2565 Budget Adjustment Phase 1

### PR DESCRIPTION
**Pull request by Enzo-Leon**
## About The Pull Request
//Lore Notes
To whom it may concern,

Due to costs and consistent re-fitting fees incurred from consistent issues to the Triumph we'll be cutting back department funding (gear & supplies) from the ship. In return, we'll be retro-fitting some exterior maintenance additions to deck three around the medical and rear section of the ship. Due to constant programming issues we have removed the medical escape shuttle for the time being while we look into future use cases and attempts to fix the faulty logic behind the shuttle craft.

Thank you,
Enzo Leon
NDV Marksman - CCO
//End Lore Notes

//General Information
The PR here is a roll-back on some over supplied areas in medical and Exploration that felt it was giving TOO much to some people, while hindering the effectiveness of others as well as making the difficulty of certain jobs/tasks WAY too easy and without risk of danger/death. This is the first phase of an unknown count to balance and adjust the setting for the facility and prep for the next map coming in the "Soon tm" future.

## Why It's Good For The Game

QOL and needed adjustments to bring jobs more in line to what they're expected to do and what they'd be limited to in all honesty. Certain jobs should not be able to perform certain tasks unless "trained" or on-board as the respective job. The adjustments to gear it to give Science and Medical core actual work and stuff to do for their job rather than Exploration, and EMTs able to one man hospital an entire group of people with no real prepwork/difficulty and have little to no danger during expeditions or station alerts.

## Changelog
:cl:
add: Added more maintenance areas & loot to the Deck 3 area.
tweak: Exploration Medbay gutted of chem supplies
tweak: FM starting gear nerfed of RIGs & Overpowered chems.
tweak: EMT gear gutted of RIGs and reduced starting gear. Machete kept due to job line having them run into actual danger to help.

/:cl:

### CODE REVIEW

**Comment by peeesh** [comment]
what does this achieve, enzo "anthony" leon, citadel station 13 head admin (formerly)

**Comment by Captain277** [comment]
Yo Enzo, can you resolve whatever conflict is tripping this for me?

**Comment by Enzo-Leon** [comment]
I'm unsure what's causing the conflicts on deck 4 @Captain277. I'll do some checking on the changes. Were there any recent merges to Deck 4 that might of caused this?

**Comment by Enzo-Leon** [comment]
Found the issue. Someone edited Deck-4 without a proper note in a previous PR. Needing to re-do all of deck 4 changes and then resubmit.

**Comment by Captain277** [comment]
I hate to do this to you, but the vorestation .dme change here removes a lot of magical stuff. I need you to go in and check those files for me.

**Pull request merged**
