### PR TITLE
Messy Space Chatter Rewrite

### PR DESCRIPTION
**Pull request by KillianKirilenko**
## About The Pull Request

I got bored of seeing the same rote spacechatter every time one came up, so I took the system and did my typical brand of Horrifying Code Surgery on it to do stuff.

Also, I stripped out some outright references to other media.

Main points:
1) Includes several new events for space chatter, including docking requests, navigation hazard warnings, travel advisories, and "routine inspections". Certain events are initiated by Control rather than a ship.
2) The various details and phrasings of each event are randomized from a small pool of possibilities to reduce repeats. Ideally you will never see the exact same ship or event twice in a single shift.
3) Destinations and missions have also been tweaked; orgs now pull from their own destinations list as originally intended (according to the comments) rather than almost never visiting their own sites. Existing emergency & wrong frequency events remain, with slightly adjusted probabilities.
4) Restores independent spacers and Major Bill's, and adds the FTU, PCRC, Focal Point, Aether, and Grayson. Also adds Antares Robotics (from #1438) as a TSC, with appropriate lore. Also adds a pair of generic-ass PMCs as placeholders. Due to the way the system works, this also adds them to the Traveler's Guide!

Barring new events and orgs this is mostly done.

## Why It's Good For The Game

More chatter, more interestingness, less references.

## Changelog
:cl:
add: Added new chatter events for spacecomms, and new factions.
del: Removed media references in the form of factions and ship names.
tweak: Restored removed TSCs.
/:cl:

### CODE REVIEW

**Comment by AnalWerewolf** [comment]
Not a fan personally on the removal of the 'space' adjective in Space Control. The map I am making relies on it for the ATC chatter to make sense. With this change it'd be, "Rift Control." rather than "Rift Space Control."

**Comment by KillianKirilenko** [comment]
Restored spacecon. This one also clears up something stupid with destinations, adds a new 'travel advisory' event, and makes some indentation consistent.

**Comment by KillianKirilenko** [comment]
All good to go. Quite possibly my most extensively-tested PR to date; this one has been run through the wringer to make sure none of the events would cause issues.

On average, space traffic should fire twice per hour, for a total of six to ten times per shift depending on length. There's a total of sixteen(!) distinct 'events' with varying degrees of randomness, pulling from a list of up to twenty possible organizations, each of which has around a dozen ship names and destinations at minimum.

**Comment by KillianKirilenko** [comment]
Sounds good to me. It should be good to go whenever.

**Pull request merged**
