### PR TITLE
induceable SMESes

### PR DESCRIPTION
**Pull request by lolman360**
allows you to inducer smeses
untested because i hate testing shit on rpcode

## Changelog
:cl:
fix: inducers can charge SMESes now
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
y

**Comment by lolman360** [comment]
@silicons you can do it on main you should be able to do it here

**Comment by lolman360** [comment]
this is more useful for the battery rack cell units which are subtypes of `/smes` so i put the functionality on `/smes`

**Comment by lolman360** [comment]
if you're asking why haven't i tested it i'm testing it rn

**Comment by lolman360** [comment]
also: if you're worrying about thermodynamics abuse it literally takes an hour to charge the main smes on tether, 15 minutes to charge a single-coil smes, and you need to change the cell every minute at least

**Pull request merged**
