### PR TITLE
Comments out Daemon(demon) and Enochian(angel) languages, removes a reference to an angel

### PR DESCRIPTION
**Pull request by AnalWerewolf**
## About The Pull Request

Comments out demon and angel languages. They're unused, not lore friendly in the slightest, and we all know it's a silly thing left over from VORE.

## Why It's Good For The Game

Demon and angels as they were, were in no way, shape, or form lore friendly. What part of a biblical angel in a perfect society with perfect morals, perfect laws, perfect everything is lore friendly? Likewise for their demon counterparts. 

## Changelog
:cl:
del: Temporarily removes Demon and Angel languages
/:cl:

### CODE REVIEW

**Comment by CameronWoof** [comment]
This essentially removes the races from the game entirely, which I don't support. Angels and demons have not been an issue on the server and we do have a (small, admittedly) number of players who play them.

**Comment by pireamaineach** [comment]
In a roleplay server, a completely unbelievable, mary sue race isn't exactly something you want. If you want to be a human with wings, just use gene mods.

I understand it's a furry server but at least have some standard.

**Comment by Tename** [comment]
Angles and demons shouldn't be canon, it is insane that they are, yes please.

**Comment by ForFoxSake** [comment]
I have three issues with this PR, and I feel they're both fairly substantial.
The first is that this clearly doesn't have the backing of any of the lore team, much less any actual grounding on merged lore.
I would strongly recommend you speak to the lore team and find who's currently responsible for our official stance on this matter, to see if they can help you bring the code in line with the actual lore as opposed to blindly cutting loose things you personally dislike.
Secondly, the demon language so far, has effectively become an unofficial stand in for the whitelisted gutter language. I've found, much to my delight, most of the darker, shadier characters on this server speak the demon language. Removing it is going to create more fragmentation between those characters as they all go and choose different languages.
At this stage, it's basically no longer just a language for demons.
Finally, and to be frank, I came to this server because it has a vague policy of no official judgement from staff in regards to personal character lore. I can make whatever dumb snowflake I want, and so long as I don't shove it down everyone else's throat, there's no real problem with that.
This PR however, isn't just a marked diversion from that, judging by the branch title (and previous PR title), this PR seems like a specific, targeted snipe at certain characters already on the server.
That, in my opinion, is a rather unbecoming attitude to have. Especially for an administrator.

So, I guess what I'd like to see cleaned up in this PR is:
1. Some backing from the lore team, in some form.
2. A contingency in place for characters using these languages - especially for characters using them for other purposes (*coughopengutterapplicationscough*)
3. Attempt to be a little less rude towards current server players, too.

**Comment by AnalWerewolf** [comment]
> lore team

Already have. The lore team seems adamant that the angels and demons should exist, have their own society, language, and for all intents and purposes be as significant as an alien race like a vulp. This is just rediculous and I have no idea what led them to think this was a good idea. It's not at all lore friendly to have full blown religious figures, REAL LIFE RELIGIOUS FIGURES existing as a basically more advanced human race. Even if they wanted to be biblical about it, they're certainly not sticking to Bible canon. It's just an absolute circus I swear.

As for your second point, I think that's equally rediculous, the demon language is not supposed to be spoken in public according to its own description, not only that, but I hate the idea of 'meta' languages where if you don't choose this one language you're gonna miss out on a certain group's communications or be excluded the moment two start speaking it. The idea that demon should be a standin for gutter is a testament to how ass backwards this community is with its lore, no run of the mill shady character should know demon just because it sounds edgy, that's absolutely rediculous justification for choosing a language. I have another PR up that removes the gutter whitelist, hopefully it will mark a step towards better characters.

I can have whatever opinion I want regarding the community or how to go about improving it, seems you only put that last part in as 'a targeted snipe' at my trial administrator status. That status has no bearing over this repository or my ability to put fourth ideas or changes to this codebase. And I in fact find it quite silly you're targeting me on such a thing, seeing as there is evident and voiced support for this PR, your accusation holds no grounds. If this is rejected or changed, so be it. I saw a complaint among the community regarding angels and demons and went about proposing a change, simple as that.

**Comment by ForFoxSake** [comment]
You seem to have missed the purpose of my third point entirely.
I'm sorry if you took offence to it, however I felt it needed wording strongly that this _entire pr_ is a targeted snipe against both the lore team and the players who play angels or demons.
Your rebuttal to my first point only confirms this.

Honestly, finding that the lore team disagrees with you, and then having an absolute baby rage over it and trying to go over their heads by pushing prs to align the code with your own lore views is both petty and toxic.
And just to be clear about my own position here, I don't care if angels and demons are in or out of the code. That part makes no difference to me, personally.
I'm taking a strong stance against this PR however, as if this is pulled in it's current state then it sets the precedent that if you lose an argument, you can still get your own way by writing a line of code, throwing up a PR and begging Kevinz to pull it for you.
In that regard, you're taking the circus out of the lore team, and bringing it here instead, and burying legitimate development under your own failed arguments.

There's probably not a lot more I can contribute to this thread beyond this without making things worse, so I'm going to bow out now. 
I'm going to close with a request, however. @AnalWerewolf **please** resolve issues and disputes _before_ bringing them to the repository.

**Comment by AnalWerewolf** [comment]
>Honestly, finding that the lore team disagrees with you, and then having an absolute baby rage over it and trying to go over their heads by pushing prs to align the code with your own lore views is both petty and toxic.

>And just to be clear about my own position here, I don't care if angels and demons are in or out of the code. That part makes no difference to me, personally.
I'm taking a strong stance against this PR however, as if this is pulled in it's current state then it sets the precedent that if you lose an argument, you can still get your own way by writing a line of code, throwing up a PR and begging Kevinz to pull it for you.
In that regard, you're taking the circus out of the lore team, and bringing it here instead, and burying legitimate development under your own failed arguments.

I didn't consult the lore team before making this PR, this is me consulting the lore team. The entire idea behind pull requests is to review and discuss changes to the codebase, my PR here is a suggestion. Is it petty to suggest a solution to an issue?

I'm just really quite confused here, you're putting up a strawman in a way I haven't quite seen before. More power to you if its your opinion I guess. 

Kevinz was not consulted at all during this period, he assigned himself and the tags for this PR. At least he could clearly see that the intent was for discussion. 

>There's probably not a lot more I can contribute to this thread beyond this without making things worse, so I'm going to bow out now.
I'm going to close with a request, however. @AnalWerewolf please resolve issues and disputes before bringing them to the repository.

The idea behind this PR is to discuss our disputes about how Angel and Demon lore should be handled :P

**Comment by ForFoxSake** [comment]
I don't actually have time to fully respond, I have to leave like, as I'm writing this.

I'm really not sure where you think I was strawmanning, everything I've said was said in regards to this PR, and the way it was _presented_. 
As for the point about Kevinz, he's the only maintainer, it doesn't matter who gets "assigned" to what, he's the only person who finally decides what does or does not get pulled.

I'd like to go into a lot more detail here, but again, my time is painfully scarce.
"This isn't a request, it's a suggestion" - I'm going to drop my previous points about the fact the entire tone of everything until this point is contrary to that, so that we can move on faster.
So, assuming this is just a suggestion then here are my points for the discussion as it stands:
I stand behind the lore team with this, since this should be their decision, further more, cutting content that we have lore for is just terrible.
If this isn't resolved by the time I get back in a couple of days, and if the person who's responsible for angel and demon lore is reading this, then I'd like to reach out and offer an alternative that fits with our lore as opposed to virgo's.

**Comment by AnalWerewolf** [comment]
> I'm really not sure where you think I was strawmanning, everything I've said was said in regards to this PR, and the way it was _presented_.
> As for the point about Kevinz, he's the only maintainer, it doesn't matter who gets "assigned" to what, he's the only person who finally decides what does or does not get pulled.

No worries, perhaps we're just not understanding eachother correctly then, that's fine. Also Kevinz is no longer the only RP maintainer, BlackMajor just recently was made a maintainer, though like I said this was very recently so it's understandable that you didn't know.

>"This isn't a request, it's a suggestion" - I'm going to drop my previous points about the fact the entire tone of everything until this point is contrary to that, so that we can move on faster.

Yeah I don't like GitHub's nerd jargon for that exact reason. It may be called a pull request but functionally it is a suggestion. 

>I stand behind the lore team with this, since this should be their decision, further more, cutting content that we have lore for is just terrible.

Yeah perhaps it may be, but I am of the opinion that it was a poor addition in the first place. I stand by the idea of improving content rather than removing it, but in this case I believe removing it would be an improvement.

>If this isn't resolved by the time I get back in a couple of days, and if the person who's responsible for angel and demon lore is reading this, then I'd like to reach out and offer an alternative that fits with our lore as opposed to virgo's.

Feel free to suggest it here, that's what the PR is for. @CameronWoof is the lore maintainer and responsible for Angel and Demon lore.

**Comment by CameronWoof** [comment]
Please alter the title to specify that this PR actually comments out *all* references to angels and demons from the code.

**Comment by Keekenox** [comment]
I'm going to be that guy and say that angels and demons are no more unbelievable than literally walking cats and dogs and lizards, and yet here we are. Also a whole ton of people play demon characters, less so angels though (unfortunately :c).

**Comment by Snownbloodyflowers** [comment]
@AnalWerewolf  I feel this would have been better if your justification (Or it so appears) was something rather than "I don't like it so let's remove it." At least when I was planning protean reworks, I  asked the people who played proteans what they thought of the current state and my plan . I want to inquire if you had at least consulted the players before this.

Regarding Daemon being the gutter replacement. That is an issue with the playerbase. Instead of removing both languages perhaps we could just solve this by non-whitelisting gutter.

Finally, mechanically angels are custom species humans with wings. The language gives them only a minor difference and they are not innately different from humans (and neither are daemons.... Resprited humans). It is not like Vox, Xenochimera, Aluane, or  Proteans who have wildly different base stats, (some) have abilities that the base human race does not possess, and (some) require a white list. Angels are none of those, neither are Daemons.

I kindly ask you to reconsider the implications this has before proceeding if you truly still wish to push this PR.

**Pull request closed without merging**
