### PR TITLE
[WIP] Rift added freezing over airlocks that malfunction and ice axes

### PR DESCRIPTION
**Pull request by pixelkitty286**
## About The Pull Request

This adds freezing over airlocks to rift that freeze and malfunction when a blizzard hits.

This also adds a ice axe and a ice pickaxe that is standard issued in departments that normally spend lots of time EVA on the planet.

## Why It's Good For The Game

This is done to give rift some more fluff along with some real showings that we are indeed on a frozen tundra of a planet.

Ice pickaxes were in the game already they just had no practical use what so ever, so I changed the existing Ice pickaxe to be a sorta deluxe Ice axe that can be use as multiple tools, like a pickaxe and a axe that can provide some form of defense a long with climbing cliffs a three in one if you will.

Ice axes are standard issued ice chipping tools to chip the ice off the airlocks. This is so the user don't get stuck outside when a blizzard hits. However they can clear the ice still with out an ice axe, but this will take longer depending on the item you use to chip the ice away.
## Changelog

:cl:
add: Added new freezing over airlocks that malfunction on rift.
add: Added Ice axe and Ice pickaxe, and added them to the mining vender since they are considered a survival tool.
tweak: tweaked existing ice pickaxe to be a 3 in one ice axe
fix: fixed some overlapping turfs, fixed also some random area/space holes, and fixed science outpost's airlocks to use map helper airlocks instead.
imageadd: added ice axe sprite from Yawn wider.
code: Added rift frozen airlocks in rifts' misc.dm file, coded in ice axe and ice pickaxe, and coded them into the mining vender.
/:cl:

### CODE REVIEW

**Review by Captain277 — CHANGES_REQUESTED** [review]
I'd prefer if this ran a variable on airlocks themselves and didn't rely on bespoke mapped-in airlocks to work! Please consult Kevin and I about how to get airlocks to passively detect temperature. I think this would be an interesting feature to just put on airlocks intrinsically.

**Comment by pixelkitty286** [comment]
Hey it's gonna be a little bit before I can rewrite how the doors detect when to freeze using temperatures, maybe this weekend? Depending on how much time I get. If you'd like me to convert this to a draft since I don't have time to work on this I can do so.

**Comment by pixelkitty286** [comment]
As it is right now this is very poorly coded and I will need more time to rewrite the other issues with this.

**Comment by pixelkitty286** [comment]
I'm closing this PR for the reason of: Scheduling error

**Pull request closed without merging**
