### PR TITLE
Comments out Burn Chamber and Fission

### PR DESCRIPTION
**Pull request by yourdoom9898**
## About The Pull Request

Exactly what it says on the tin, comments out Burn Chamber and Fission from the randomly picked engine

## Why It's Good For The Game

Both of these engines are both overly complex, and _incredibly_ poorly documented, if even at all (Try to find the ONE fission guide which is also outdated), and only serve to drive anyone new to Engineering away as they struggle to make sense of the spaghetti they're looking at.

## Changelog
:cl:
del: Removed poorly documented engines from generation
/:cl:

### CODE REVIEW

**Comment by yourdoom9898** [comment]
obligatory isaltpr

**Comment by TheLordME** [comment]
why not, while we are at it, remove the medical system, mining, and the need to do RnD, just have everything unlocked at round start

**Comment by yourdoom9898** [comment]
Guide to Medical: https://citadel-station.net/wikiRP/index.php?title=Guide:_Medicine, https://citadel-station.net/wikiRP/index.php?title=Guide:_Chemistry, https://citadel-station.net/wikiRP/index.php?title=Guide:_Surgery

Guide to RND: https://wiki.vore-station.net/Destructive_Analyzer, https://pastebin.com/XpT0KNHb (if you want a path to be able to complete levels easily)

Guide to mining: https://citadel-station.net/wikiRP/index.php?title=Guide:_Mining (It's missing copper, which was recently added, but doesn't generate yet)

Guide to Burn Chamber: A piece of paper on the ground telling you how to get it started, but not why it's done that way, or what any part of the engine actually does

**Comment by TheLordME** [comment]
If we go by that logic we can just disable Atmos and give every substation a magic SMES, remove the first deck all together

**Comment by yourdoom9898** [comment]
You're continuing to make bad faith arguments commenting out two engine variants with 0 documentation, and things that actually have documentation ( https://wiki.vore-station.net/SMES_Manual ). And yes, Atmos does need it's documentation completely redone, that's part of the problem here.

**Comment by silicons** [comment]
no
i made a config for a reason
stop trying to impose this silliness on the git

bug captain

**Pull request closed without merging**
