### PR TITLE
[PLAYTESTING REQUIRED] NSV Endeavour - Endeavouring Onwards

### PR DESCRIPTION
**Pull request by Andromeda-K22**
## About The Pull Request
Fixes up the Endeavour map, with multiple changes to suit Citadel. I have probably missed a number of things, and so playtesting is required to catch what I missed.

The NSV Endeavour is a mobile science vessel, designed to move between systems and study new worlds. It is currently stationed within PME-15C, a mid-life yellow star, otherwise known as the 'Odin' System. Fitted with a state of the art exploration shuttle and facilities, the ship was recently retrofitted once more to support a crew for short-duration stays, with the intent to rotate personnel from other Nanotrasen facilities, such as the Adephagia in Virgo. 

## Why It's Good For The Game

TETHER CAN FINALLY FUCKING DIE.

## Changelog
:cl:
Endeavour Updated and Modified
/:cl:

- [ ] - Command Remap [IN PROGRESS]
- [ ] - Medical Remap
- [ ] - Security Audit
- [ ] -  Maint De-diagonalizing
- [ ] - Fix Cargo Shuttle
- [ ] - Various Fixes
- [ ] - Fix D4's detailing.
- [ ] - Deal with the dummy thicc elevator.

### CODE REVIEW

**Comment by ArgonianVampirey** [comment]
This map is too small and boring for citadel. Maps that are bigger with more fun nooks and crannies are much more interesting to play on, especially for new players.

**Comment by Andromeda-K22** [comment]
Please reserve matters of opinion for Discord or the forums, Github is specifically for mechanical issues or feedback.

**Comment by Andromeda-K22** [comment]
#1496 #1499  #1495 #1501 #1493 Resolved

#1500 #1494 Addressed/Resolved

**Comment by Andromeda-K22** [comment]
- [ ] - Command Remap [IN PROGRESS]
- [ ] - Medical Remap
- [ ] - Security Audit
- [ ] -  Maint De-diagonalizing
- [ ] - Fix Cargo Shuttle
- [ ] - Various Fixes

**Comment by Andromeda-K22** [comment]
Someone else can work on this. I don't care to contribute to this community anymore.

**Pull request closed without merging**
