### PR TITLE
Chemmaster workflow streamlining

### PR DESCRIPTION
**Pull request by TheLordME**
## About The Pull Request
When creating multiple bottles of chems on the chemmaster the dialog opens with 10 as a default value, this PR changes that to 2.

## Why It's Good For The Game
The standard large beaker can fill two bottles, so it speeds the process of creating chems in large quantities slightly.

## Changelog
:cl:
tweak: Creating multiple bottles in the chemmaster is slightly less annoying.
/:cl:

### CODE REVIEW

**Comment by Captain277** [comment]
Please update this/merge the master into it.

**Comment by TheLordME** [comment]
@silicons something broke in contact with lights and bots, see integration test for details...

**Comment by Captain277** [comment]
On mobile. Please review and repair conflicts.

**Comment by TheLordME** [comment]
No, because I already did this in another PR, because linters didnt fix

**Pull request closed without merging**
