### PR TITLE
Adds the pet treat! Includes new admin verbs, mask sprites, oh my!

### PR DESCRIPTION
**Pull request by AnalWerewolf**
## About The Pull Request

Adds the ability to summon treats instead of cookies to those who pray!
The treat is identical to the cookie, however it has a different flavour and can also be worn in the mask slot. 

Mainly an admin thing. ~~You can't get the treat through any other means, though this may change int he future.~~ You can get a box of the treats through the loadout menu, the box costs two points. Requested by an admin.

## Why It's Good For The Game

It's heckin' cute! 

image

## Changelog
:cl:
add: Added a pet treat! It can only be obtained through asking the gods above very nicely, or, by being a good boye/grill
imageadd: Added appropriate mask icons and spritework
admin: Added the ST verb when responding to prayers, use this to summon a treat!
/:cl:

### CODE REVIEW

**Comment by VarkaSelyn** [comment]
Need a box of these as a loadout option to give to all the good doggo SARs imo.

**Comment by AnalWerewolf** [comment]
> 
> 
> Need a box of these as a loadout option to give to all the good doggo SARs imo.

And done!

**Comment by VarkaSelyn** [comment]
Minor issue, btw; in your admin.dm defines, the full href for spawn treats is the same as spawn cookies, so it's going to appear as two instances of 'SC' which may be confusing.

**Comment by AnalWerewolf** [comment]
> 
> 
> Minor issue, btw; in your admin.dm defines, the full href for spawn treats is the same as spawn cookies, so it's going to appear as two instances of 'SC' which may be confusing.

Nice, didn't catch that, thanks for letting me know.

**Comment by AnalWerewolf** [comment]
@kevinz000

**Pull request merged**
