### PR TITLE
Makes collectors dense again, and climbable

### PR DESCRIPTION
**Pull request by TheLordME**
## About The Pull Request
this is a web edit, merge at your own risk

## Why It's Good For The Game
Its stupid that they arent dense, making them climbable kinda makes sense and still allows the utility of easy access

## Changelog
:cl:
tweak: Tweaks how atlas engine can be accessed
/:cl:

### CODE REVIEW

**Comment by yourdoom9898** [comment]
They were made not dense so the Atlas's engine wouldn't be ass to set up, and I see 0 point in adding tedium exclusively to add tedium

**Comment by TheLordME** [comment]
> They were made not dense so the Atlas's engine wouldn't be ass to set up, and I see 0 point in adding tedium exclusively to add tedium

the fact that they are not dense makes them pretty silly, making them climbable is not that big of a deal, you need to climb onto or over them a total of 5 times to reach all collectors, thats a total of 15 seconds to setup the engine

**Comment by TheLordME** [comment]
If you do it smart you can get away with 4 climbs

**Comment by yourdoom9898** [comment]
> > They were made not dense so the Atlas's engine wouldn't be ass to set up, and I see 0 point in adding tedium exclusively to add tedium
> 
> the fact that they are not dense makes them pretty silly, making them climbable is not that big of a deal, you need to climb onto or over them a total of 5 times to reach all collectors, thats a total of 15 seconds to setup the engine

And yet, what does adding the inconvenience _add_ to the game, besides for being mildly annoying for the sake of being mildly annoying?

**Comment by TheLordME** [comment]
Realism, why bother having delays on airlocks opening, or when unwrenching pipes, other than create inconveniences for the players, why not remove the game entirely because it is an inconvenience to my presence on the server where I have to bother and set up the engine

**Comment by silicons** [comment]
i only did the non-dense in the first place because of atlas
the clause is 'if someone finds a better way we'll do that instead' my 'fix' was never meant to be permanent

**Pull request merged**
