### PR TITLE
[WIP] Pireamáineach's Phoronoid Rework:tm:

### PR DESCRIPTION
**Pull request by pireamaineach**
## About The Pull Request

It's up so soon because  I wanted to give people a platform for criticism during development, currently it doesn't do much but in the end it ought to be fairly great. 

## Why It's Good For The Game

/tg/ plasmeme base mechanics function a lot better than Goon or /vg/, and a port is relatively intuitive to pull off.

## Changelog
:cl:
add: Suits now auto-extinguish.
add: Plasmamen can now wear any space suit if they have both a pressure proof suit and helmet.
/:cl:

### CODE REVIEW

**Comment by pireamaineach** [comment]
Wait https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/1426 already did one of these.




Eh I'll compare code and decide which one's better letter.
@peeesh You're probably going to want to comment on this as I update it.

**Comment by pireamaineach** [comment]
Okay so I'm basically just going to add to Peeesh's code so that items which aren't TECHNICALLY space suits, but still protect from space, are included.

**Comment by peeesh** [comment]
goddamn ok you actually got extinguishing bullshit working

**Comment by peeesh** [comment]
though i did uh, copypaste this onto my own branch. didnt seem to work. did you actually test this

**Comment by pireamaineach** [comment]
Few things about current code are fucky wucky. I got banned from the Cit discord without warning and am feeling a little disenfranchised right now, you'll have to forgive me.

**Pull request closed without merging**
