### PR TITLE
Replaces stamp icons with new ones

### PR DESCRIPTION
**Pull request by NopeMcHaltman**
Should go well with #460 
stamps_time2

~~many nerves have been sacrificed to make these sprites~~

### CODE REVIEW

**Comment by CameronWoof** [comment]
I don't personally think these are an upgrade over the current stamp sprites, even considering the new stamp sounds.

**Comment by king5327** [comment]
You're not allowed to complain about this PR if you have your own with your own stamps.

**Comment by CameronWoof** [comment]
To be fair, I didn't have my own PR when I made the original comment. I wouldn't make it now.

**Comment by NopeMcHaltman** [comment]
image
Here lies my broken nerves.

**Pull request closed without merging**
