### PR TITLE
pteric flight bad

### PR DESCRIPTION
**Pull request by lolman360**
non-wing flight is good and possible. flying already isn't amazing (HUGE nutrition drain, slam into airlocks and walls) so this isn't that significant of a change

### CODE REVIEW

**Comment by Nethaufer** [comment]
Why though

**Comment by yourdoom9898** [comment]
Slight note, it is called Winged Flight in species creation over at code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm . Might want to fix that

**Comment by lolman360** [comment]
@Nethaufer there's no invisible wings sprite so here we are

it opens up flight to characters who don't have wings. flight isn't really that good of an ability because it drains a shitload of nutrition so *shrug

**Comment by nik707** [comment]
Honestly I'm okay with this because it allows for fun roleplay like synths with fucking rocket boots xd

**Pull request merged**
