### PR TITLE
Introducing the all new kitchen gun!

### PR DESCRIPTION
**Pull request by ForFoxSake**
## About The Pull Request
See this informational video about the proper use of a kitchen gun:
https://www.youtube.com/watch?v=6-7NDP8V-6A

## Why It's Good For The Game
Chefs are often required to call the janitor in order to clean out dirty microwaves or other filthy things and the janitor never likes having to do it, so now the chef gets a thematically appropriate tool to clean the kitchen.
(Yeah, it's a joke item. Potentially controversial too, idk. I coded it for fun, and that's about it.)

## Changelog
:cl:
add: Added a kitchen gun to the chef's closet.
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
>Not making it an actual gun like it is on Main

smh my head

**Comment by ForFoxSake** [comment]
I might try making it an actual gun after hardsync, if it allows for fun guns.
As it stands, my knowledge of polaris gun code, it'd probably be a very real and very dangerous gun that'd sooner blow someone's head off than actually clean anything.

**Comment by realbuffalowing** [comment]
all you had to do was add a spray bottle spawn in the kitchen

**Comment by realbuffalowing** [comment]
also would this even functionally work? the reagent in it is 'plantbgone', and not 'cleaner'

**Comment by ForFoxSake** [comment]
Kev asked me what to do with this pr and I told him close it. Since he hasn't and I've finally bothered to log on, I'll be doing it so that no one accidentally pulls it.

Before I close it though: Yes it works, yes I stopped it from sounding like a gun. When I tested it, that seemed like it was immediately going to cause shit. Could you imagine a chef running around cleaning people up and sec hears gunshots? (Even if they are hilariously over the top sounding. Seriously that deagle sound is hilarious.)
But as it's defined, it does contain space cleaner, and not plantbgone. The plantbgone belongs to the previous item in the file.

Personally I'm not happy with a couple of things here, hence why I'm going to close it and give up for now because the meme isn't worth it. If I suddenly change my mind, then round 2 will come with a lot more polish.
(That said, the switch over to the usesound var is a pretty neat modernization even if it's not used at all, so I might attempt a stealth merge of that at some point, if no one objects.)

**Pull request closed without merging**
