### PR TITLE
[ReadyforTestMerging] Swapping the Tether for Polaris's Southern cross.

### PR DESCRIPTION
**Pull request by GrayRachnid**
To-do List.

- [x] Fix Dir on all consoles.
- [x] fix medical intercoms
- [x] fix sec intercoms
- [x] fix medical in general
- [x] resleeving lab
- [x] resleeving lab for synth
- [x] trashpiles
- [x] add mice everywhere
- [x] bigger dorms
- [x] even bigger dorms on sif
- [x] holodorms
- [x] body re-design
- [x] department nif disks
- [x] nif vendors
- [x] captain's omnihud/translocator
- [x] heads of staff lockers
- [x] timeclocks
- [x] up explorers to 4, add pathfinder spawn.
- [x] (easy) add weapon permits to hos office
- [x] some other stuff that i'll add later, probably.

This is for everyone to get a preview and for feedback.

Pictures: Keep in mind they're from Polaris, so they still don't have all the shit i'm adding. I'll update them once i'm done.
image
https://i.imgur.com/jWZQQQv.jpg (File too big, this one's a link.)
image
image
image

### CODE REVIEW

**Comment by GrayRachnid** [comment]
I'm guessing my work-around the mapmerger not working was not appreciated

**Comment by GrayRachnid** [comment]
bleh, i'll come back to this once I finish work.

**Comment by deathride58** [comment]
When this is ready for testmerge, ping me.

**Comment by nik707** [comment]
Closing due to inactivity, reopen if fixed.

**Pull request closed without merging**
