### PR TITLE
Add 2 new shuttle / Makes the Nebula pad bigger

### PR DESCRIPTION
**Pull request by DeltaDav**
## About The Pull Request

This adds the multiple ideas for more shuttles in the Nebula Gas Station.

One, the Udang, is a civilian open acces shuttle, that traders and people who spawns off station can use. Still linked to nebula, andd carry people and stuff
 The second, the Scoophead, is a smaller trading ship.
 
Capture d'écran 2024-07-06 223615

Capture d'écran 2024-06-28 160155

## Why It's Good For The Game
More liberties for off-station spawns and the Traders

### CODE REVIEW

**Comment by DeltaDav** [comment]
Working on some modification on the rift pads, to accomodate the 2 new shuttles. A under construction pad for the Udang, and the pirate pad has been divided in 2 to accomodate the scoophead. 

Badass Trader Ship parked near Badass Pirate ship, fitting eh ? (Its also close to the station) 

image

On Triumph, the Udang will get a extra dock, on the docking arm. The Scoophead can dock on docking arm 1. 

image

**Comment by DeltaDav** [comment]
should be good for test merge

**Review by TheLordME — DISMISSED** [review]
please either delete the changelog section in the PR, or fill it out, leaving it on default is gonna cause problems with the changelog (I deleted it this time)

**Review by TheLordME — DISMISSED** [review]

**Review by TheLordME — APPROVED** [review]

**Comment by DeltaDav** [comment]
This PR will be put in the bigger nebula rework PR. All 2 added shuttle and Bigger pads will be added over there.

**Pull request closed without merging**
