### PR TITLE
The Vegan Vampire Update

### PR DESCRIPTION
**Pull request by CrystalClearCC**
## About The Pull Request

Adds Bludbox(TM)es to the station! These cute little cartons come in four flavours and help satisfy the midnight cravings of our undead friends.

There's two distinct versions to be found. MAX and regular.

Bludbox MAX contains O- blood. (I need someone to confirm this, please)
Bludbox MAX Light contains synthblood (which is also O-).

Both the MAX variants can be found in the Bood-Onator

Bludbox and Bludbox Light cartons contain a unique new reagent called Blud (and Blud Light). Blud is edible by all, and provides nutrients to vampiric characters at a rate of 0.5 per unit. This means it should be a decent stopgap between having to actually feed, while not actually fully replacing the mechanic.

The update also contains a bit of backend changes to how vampires work, alongside introducing a new variable called blood_content to drinks and alcoholic beverages.

blood_content is at default set to zero, but can be applied to any drink to allow vampires to feed from it. Currently, the equation is `units_digested * blood_count` where blood_count is intended to be a 0.9 or less value.

Drinks that vampires can feed from include:
- Blood Meridian
- Devil's Kiss
- Red Ale
There may be more that I forgot, but if it's got blood in it, it probably has a blood_count above 0.

## Why It's Good For The Game

Bloodsucking crew no longer have to break into departments or actively hunt down prey in order to sustain themselves on quiet shifts. Some of the code has been cleaned around them, too.

## Changelog
:cl:
add: Introducing Bludbox(TM)! These cute little cartons come in multiple flavours and help satisfy the midnight cravings of our undead friends.
add: Medical now has access to Blud Max! These are little snacc boxes for the hungry undead who come to raid your Blood-Onator.
add: Alcoholic beverages that contain blood now also feed vampires! The framework for this can be implemented to any new drink.
spellcheck: Fixed a typo in the description of the A- bloodbags found in medical.
tweak: A bunch of backend stuff around vampires has been cleaned.
/:cl:

### CODE REVIEW

**Comment by TheLordME** [comment]
maybe change it to AB+, so medical cant powergame them?
0- is universal donor blood, and vampires dont care about the type(for nutrition at least)

**Comment by TheLordME** [comment]
For dionas, id PR it but lazy:

> /decl/lore_info/religion/diona
> 	name = "The Gathering"
> 	description = "We are on a journey to gather information, so we may preserve it until the end of time. Our journey seems simple, leave, learn, return, but we face millions of dangers on our way, may the stars sing with us."

**Comment by CrystalClearCC** [comment]
> maybe change it to AB+, so medical cant powergame them? 0- is universal donor blood, and vampires dont care about the type(for nutrition at least)

synthblood is automatically O- so that can't be changed. (though i may add some neat flavoured options?) The cartons come in 30u at 50 thaler a pop, compared to medical's 200u bags it's really not that worth it imho.

**Comment by deathride58** [comment]
>Not calling it Bludlight(tm)
Pun game 0/10

On a more serious note though: It'd probably be much cleaner to handle blood-based drinks by having them add blood during metabolization, and handle everything related to vampire mechanics within the blood reagent itself, rather than the current method of hackily spreading it out across reagents (currently, alcoholic drinks and the blood reagent itself both lack the warning for consuming low amounts of blood when at low nutrition, among other maintainability concerns)

Also, bludboxmax doesn't contain O- blood. Matter of fact, it doesn't contain blood of any particular type, as nowhere in its code does it define a bloodtype within the reagent's data; it spawns with null blood. Easy to fix though! Bludlight max, on the other hand, properly contains O- synthblood, as synthblood properly defaults to O- when bloodtype isn't defined.

**Pull request merged**
