### PR TITLE
Slightly buffs tier 2 darksight

### PR DESCRIPTION
**Pull request by Ghostcoffeee**
## About The Pull Request

Buffs tier 2 darksight to have a 180 degree angle
I'd have done them all, but the balance people would lynch me.

Also buffs proteans, because super nanotech constructs should be able to see in the dark.
Why the hate?

## Why It's Good For The Game

Tiny bit of QoL for moffs and vampires.
And memeblobs.

## Changelog

:cl:
balance: Increased tier-2 darksight angle to 180.
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
can we tone down the unnecessary comments (you have added one to all 5 lines touched in this pr)

**Review by TheLordME — CHANGES_REQUESTED** [review]
Remove the comments please

**Review by TheLordME — COMMENTED** [review]
Much better

**Comment by timothyteakettle** [comment]
apparently nobody else wants to touch this and it has been open for quite a while
closing this with reason: proteans do not need a buff

**Comment by pixelkitty286** [comment]
The 180 night vision was great, I will greatly miss this now

**Comment by timothyteakettle** [comment]
they're free to re-open the PR with only the 180 night vision if they wish

**Pull request closed without merging**
