### PR TITLE
Some Fixes, Allows Taj Hair for More Species + Adds a Bunch of Virgo Markings, Ears, Tails & Taurclothes, Crushes a Shitload of VR Files

### PR DESCRIPTION
**Pull request by KasparoVy**
## About The Pull Request

~~CONFLICTS WITH https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/2357 -- naga dmi, I added the RIG sprite here and will sort out any issues that arize~~

Ports (includes all relevant fixes/changes -> **CHECK THESE OUT FOR PICS**):
https://github.com/VOREStation/VOREStation/pull/7951
https://github.com/VOREStation/VOREStation/pull/7075
https://github.com/VOREStation/VOREStation/pull/7472
https://github.com/VOREStation/VOREStation/pull/8314
https://github.com/VOREStation/VOREStation/pull/7602
https://github.com/VOREStation/VOREStation/pull/7899
https://github.com/VOREStation/VOREStation/pull/8794
https://github.com/VOREStation/VOREStation/pull/8058
https://github.com/VOREStation/VOREStation/pull/8684
https://github.com/VOREStation/VOREStation/pull/9074

**This PR also merged a bunch of _vr.dm files into the relevant regular files.**

**RENAMED FILES & DIRECTORIES (File/Dir, Old Name, New):**
```
File                     code\modules\mob\living\carbon\human\species\station\blank_vr.dm >R> custom_species.dm
File           code\modules\mob\living\carbon\human\species\station\station_special_vr.dm >R> station_special.dm
File code\modules\mob\living\carbon\human\species\station\station_special_abilities_vr.dm >R> station_special_abilities.dm
 Dir                      code\modules\mob\living\carbon\human\species\station\protean_vr >R> protean
 Dir                       code\modules\mob\living\carbon\human\species\station\traits_vr >R> traits
```

**MERGED FILES & DIRECTORIES (Old File, New File):**
```
                                                code\__HELPERS\icons_vr.dm >M> icons.dm
                    code\game\objects\items\weapons\storage\backpack_vr.dm >M> backpack.dm
                        code\game\objects\items\weapons\storage\belt_vr.dm >M> belt.dm
                       code\game\objects\items\weapons\storage\boxes_vr.dm >M> boxes.dm
                    code\game\objects\items\weapons\storage\firstaid_vr.dm >M> firstaid.dm
                     code\game\objects\items\weapons\storage\toolbox_vr.dm >M> toolbox.dm
                                     code\modules\client\preferences_vr.dm >M> preferences.dm
               code\modules\client\preference_setup\preference_setup_vr.dm >M> preference_setup.dm
                                      code\modules\clothing\clothing_vr.dm >M> clothing.dm
                     code\modules\clothing\spacesuits\rig\rig_pieces_vr.dm >M> rig_pieces.dm
                   code\modules\clothing\under\accessories\accessory_vr.dm >M> accessory.dm
                     code\modules\clothing\under\accessories\holster_vr.dm >M> holster.dm
                     code\modules\clothing\under\accessories\permits_vr.dm >M> permits.dm
                       code\modules\clothing\under\accessories\torch_vr.dm >M> torch.dm
                          code\modules\mob\living\carbon\human\death_vr.dm >M> death.dm
                          code\modules\mob\living\carbon\human\emote_vr.dm >M> emote.dm
                        code\modules\mob\living\carbon\human\examine_vr.dm >M> examine.dm
               code\modules\mob\living\carbon\human\human_attackhand_vr.dm >M> human_attackhand.dm
                  code\modules\mob\living\carbon\human\human_defines_vr.dm >M> human_defines.dm
                  code\modules\mob\living\carbon\human\human_helpers_vr.dm >M> human_helpers.dm
                  code\modules\mob\living\carbon\human\human_species_vr.dm >M> human_species.dm
                          code\modules\mob\living\carbon\human\human_vr.dm >M> human.dm
                           code\modules\mob\living\carbon\human\life_vr.dm >M> life.dm & code\modules\mob\living\carbon\carbon_movement.dm
                   code\modules\mob\living\carbon\human\update_icons_vr.dm >M> update_icons.dm
         code\modules\mob\living\carbon\human\species\species_attack_vr.dm >M> species_attack.dm
        code\modules\mob\living\carbon\human\species\species_getters_vr.dm >M> species_getters.dm
     code\modules\mob\living\carbon\human\species\species_shapeshift_vr.dm >M> species_shapeshift.dm
                code\modules\mob\living\carbon\human\species\species_vr.dm >M> species.dm
         code\modules\mob\living\carbon\human\species\station\monkey_vr.dm >M> monkey.dm
    code\modules\mob\living\carbon\human\species\station\prometheans_vr.dm >M> prometheans.dm
        code\modules\mob\living\carbon\human\species\station\station_vr.dm >M> station.dm
code\modules\mob\living\carbon\human\species\station\xenochimera_hud_vr.dm >M> station_special.dm
                              code\modules\mob\new_player\new_player_vr.dm >M> new_player.dm
                       code\modules\mob\new_player\preferences_setup_vr.dm >M> preferences_setup.dm
                      code\modules\mob\new_player\sprite_accessories_vr.dm >M> sprite_accessories.dm
                            code\modules\vore\appearance\preferences_vr.dm >M> code\modules\mob\living\carbon\human\human_defines.dm
```

:cl:
add: Tajaran hairstyles can now be selected by Vulpkanin, Sergals & Zorren (allowed species copied from Vulpkanin hair)
fix: Updates taur clip-masking to correct logical issues and improve performance
fix: Accessories attached to Taurized suits will be centered properly now
fix: Fixes a bug causing accessories to inherit the colour of what they're attached to
add: Adds support for secondary wing colour (spriters go wild)
tweak: Merged a bunch of _vr files into the regular files, file bugreport if anything is busted
imageadd: Ports all taurclothes from Virgo, namely aprons & old poncho
imageadd: Adds a few Nevrean tails
imageadd: Adds Vulp Alt. face, Vulp Short Nose, Talons, Claws, Tajaran Nose Alt., Equine Snout & Equine Nose markings
imageadd: Adds Donkey, Vulp Short + dual-colour & Vulp Jackal ear styles
imageadd: Adds Ward-Takahashi cybernetic tail with dual-colour support
imageadd: Adds darkened Teshari hair sprites ported to Virgo from Arkstation. More flexible colouration.
/:cl:

## Why It's Good For The Game

Ports over a handful of good fixes to accessories and taurized clothing while adding a bunch of new character customization-related content.

This also cleans up a bunch of _vr files, merging them with the real deal and tagging changes with //CitRP edit.

### CODE REVIEW

**Comment by Zandario** [comment]
Bless you, though could I possibly request that you merge the _vr files? We're trying to slowly phase those out with each PR

**Comment by KasparoVy** [comment]
Will do, marking as draft

**Comment by Zandario** [comment]
Thank you, you have no idea how much I appreciate it! ❤️

**Comment by Zandario** [comment]
Also I'm going to merge #2357, so you can get those files all sorted here instead of going back and doing even more work than necessary

**Comment by KasparoVy** [comment]
Great - cheers

**Comment by KasparoVy** [comment]
Conflicts resolved, will merge VR edits as time permits

**Comment by KasparoVy** [comment]
It uh... It compiles

:B

Need to do testing.

**Comment by Zandario** [comment]
Oh uh no need to mark citRP edits. We're trying to become a solid codebase

**Comment by KasparoVy** [comment]
NP, no cit edits-- understood

**Comment by KasparoVy** [comment]
Conflicts resolved, more VR files crushed, still somehow compiles

More testing to do

**Comment by Zandario** [comment]
Doin' the work of the gods my lad

**Comment by KasparoVy** [comment]
Alright @Zandario I've gone thru it all, looks alright - think it'd be OK for a testmerge? Will keep eyes and ears out in case someone finds something I missed

**Comment by KasparoVy** [comment]
Updated desc documenting every file rename/merge

**Comment by Zandario** [comment]
Oh definitely, I'll look into it when avaliable

**Comment by Zandario** [comment]
I didn't expect you to clear out so much, though now it's going to be a pain to get merged in

**Comment by Zandario** [comment]
Actually think I got a plan set

**Comment by KasparoVy** [comment]
Happy to deconflict every step of the way, this can wait for other PRs

**Comment by Zandario** [comment]
Ugh

**Comment by KasparoVy** [comment]
Sweet OK, merge most recent protean_vr file back into the non-VR'd version

**Comment by KasparoVy** [comment]
Rebased onto most recent version of master and updated the contents of `code\modules\mob\living\carbon\human\species\station\protean_species.dm` with the most recent version from PR #2351

**Comment by Zandario** [comment]
Yeah it's all good bro, I appreciate all the work ya did here

**Comment by Zandario** [comment]
Bumping due to conflicting file

**Comment by KasparoVy** [comment]
Thanks for the bump, will deconflict ears_vr.dm in about an hour

**Comment by KasparoVy** [comment]
Deconflicted @Zandario , cheers

**Comment by Zandario** [comment]
Ah thanks mate, I'll look into getting this stuff in soon

**Comment by KasparoVy** [comment]
NP take your time, can wait as long as it takes

**Pull request merged**
