### PR TITLE
adds a second elevator to tether

### PR DESCRIPTION
**Pull request by Mazianni**
## About The Pull Request

Adds a second elevator to Tether.

## Why It's Good For The Game

Alleviates the chokepoint.

### CODE REVIEW

**Comment by Mazianni** [comment]
dont merge / playtest yet, still some tweaks to be d one

**Comment by Mazianni** [comment]
good to go

**Comment by TheLordME** [comment]
68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f3133323337343330382f32303635323837313036362f6d2f6d6170735f7465746865725f6c6576656c735f73757266616365

**Review by TheLordME — APPROVED** [review]
does what it says it does

**Pull request merged**
