### PR TITLE
Buffs Morphium in line with its rarity

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

morphium is now good at research and is pretty durable, but it's less good at weapons now

## Why It's Good For The Game

rarity = power which is why bohs are diamondgated

## Changelog
:cl:
balance: morphium is strong now
/:cl:

### CODE REVIEW

**Comment by BlackMajor** [comment]
Against this tbh.
Durasteel already produces meme strong melee weapons. Powercreep man bad.

**Comment by lolman360** [comment]
@BlackMajor reduced hardness, is 80 ok

**Comment by BlackMajor** [comment]
Any reason you made Morphium give arcane 4?

**Comment by lolman360** [comment]
i forgot how rnd worked for a second, meant to give it 3 - it takes a significant investment to get, but you cal already get arcane 1/2 with the alden-sarasparova counter

**Pull request merged**
