### PR TITLE
Chief of operations

### PR DESCRIPTION
**Pull request by Zna12**
Adds 3 whole brand new alternate titles for Engineering Nerds.
Chief Of Operations - Chief Engineer
Operations Officer - Engineer
Life Support Technician - Atmospherics Technician.
Also adds one more job title for science.
Chief Science Officer
Yes i tested this yes it works

### CODE REVIEW

**Comment by Zna12** [comment]
Travis did a dumb and failed on its own, not my fault.

**Comment by nik707** [comment]
I still maintain life support doesn't make sense here, it's usually on a station/ship and we're neither.

**Comment by Zna12** [comment]
The top of the tether begs to differ, and considering all atmos outside of the tether's hostile, well, eh.

**Comment by Tename** [comment]
@nik707 I mean submarines have "life support", it's not that strange.

**Comment by ForFoxSake** [comment]
I don't wanna be a stick in the mud about alt titles because I want so many more of them.
But as a technical hitch here, "Operations Officer" doesn't fit, as standard engineers aren't actually officers of anything, iirc.
I could be wrong, though so some proof contrary would be appreciated.

**Comment by Zna12** [comment]
You're late.

**Pull request merged**
