### PR TITLE
In High Demand: More Mercenaries

### PR DESCRIPTION
**Pull request by CharlesWedge**
## The Sigmar Sector is a Dangerous Place: Everyone Needs Someone to Look After Them
_So why leave your safety up to amateurs or let alone yourself. Those Vox Pirates will kick your ass then eat you. Those Rodents, they got tanks you can't fight a tank. And as for the weirdo sadistic pirates with the swords, well less said about what they will do to you the better. In such a dangerous sector you need the best protection money can offer. We here at **Ironhammer Security** can provide you with the best protection money can offer. Our contracts are flexible so our soldier can fill a wide vareity of roles as needed. No task is beneath the soldiers of **Ironhammer**. Our soldiers are disciplined and experience, no red shirt mall cops here. Our equipment is some of the best on the market, rifles, pistols, machine guns, we don't cheap out on your protection so why should you? Sign a Contract with **Ironhammer Security** today._

_Tune your subspace communicators to: 8769.1998.247365.420.911 To get in contact with your nearest **Ironhammer** Contractor. Again that is 8769.1998.247365.420.911 and we can get an **Ironhammer** mercenary team to you in as little as a week. (Actual Travel Time may vary. Ironhammer is not responsible for damages occurred to contractors life or property while operatives remain in transit)._

## I think it is time Mercs got a good update.
In recent days mercs have lagged behind the newer more fancy mobs. Including my own cultists. I hope to rectify this and make combat against mercs more interesting and deadly. To this end I have added 7 new merc types and gave existing one a refresh. I have also added a new AI holder that will hopefully makes some mercs more challenging. In addition the new mercs also use a larger variety of weapons better integrating these weapons into gameplay then they were previously.

## Changelog
:cl:
add: 2 New Grunt Mercs: The Rifleman and the Officer Carrying a Garand and a Desert Eagle Respectively 
add: 5 New Space Mercs carrying: Combat Shotguns, Automatic Shotguns, FALs, L6 SAWs, and Tommy Lasers.
balance: Base speed of grunt mercs raised to 2 so the ones with E-swords may actually reach their target before they are swissed by explo.
fix: Ranged Space Mercs Finally have Armor in line with their Hardsuit. They also properly use the C-20R their sprite shows they carry.
imageadd: New.dmi for the mercs, so they are easy to find and add onto them (Why were **all** our mobs in animal.dmi anyway)
/:cl:

### CODE REVIEW

**Comment by Zandario** [comment]
Bumping for conflicts

**Comment by CharlesWedge** [comment]
Alright Conflicts Resolve Now we only need to fix Travis

**Comment by Zandario** [comment]
Ignore Travis. False positives that I'll need to fix

**Comment by Zandario** [comment]
Why you editing the changelog??? It's automatically compiled from the PR Changelog after every merge.

**Pull request merged**
