### PR TITLE
disruptor ammunition - closed because i'm not dealing with conflicts

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
fucks around with the formatting in autolathes to add a space in the printed item path. also uncomments 5.45 and 7.62 hunter ammunition.
but that's not why we're here.
### DISRUPTOR ROUNDS:
probably illegal or at least hard to obtain due to the unusual composition and manufacturing processes required for these rounds, they're markedly useful against animals, silicons, and, most importantly for some, xenomorphs (or other creatures tagged as aberrations)
they do however still embed into people rather solidly, so, don't shoot your buddy with it as a joke
or do

todo: add more disruptor round types, add a way to obtain them other than cargo (board and snowflaked production method? idk)
## Why It's Good For The Game
hunter rounds are underwhelming
## Changelog
:cl:
balance: if you're reading this this is still a WIP PR don't fucking merge it
/:cl:

### CODE REVIEW

**Comment by VailTheWolf** [comment]
I don't know what universe you're living in, or what version of the RP server you're playing, since Hunter rounds are definitely not "underwhelming." Your reasoning to removing entire ammo types and uncommitting ammunition from the Autolathe is "underwhelming."

**Comment by Hatterhat** [comment]
saw thing, uncommented thing, don't think i deleted any ammo types? if there was hunter ammo in the lathe already then damn i guess i didn't see it

**Comment by Hatterhat** [comment]
that reminds me the HP/AP ammo being in the lathe, even if it's just for the >funny burst rifle is kinda quirky and i should go take a crack at removing that

**Comment by VailTheWolf** [comment]
> saw thing, uncommented thing, don't think i deleted any ammo types? if there was hunter ammo in the lathe already then damn i guess i didn't see it

I'm sorry about last night. I was overly hostile and miss-read what this PR was doing. 
PR is good. New ammo is a bit too broken though. I don't think we need that 7.62 round to out perform the _14.5×114mm_ round by default. Make it have higher damage than 7.62 Hunter if you want, just don't make it outperform an anti-material round in the code. I don't know, just my opinion.

**Comment by CharlesWedge** [comment]
Just keep in mind that this will also buff the mobs that use 762 guns, two mercs of my design use in particular. Buffing the accuracy of the round itself will have a knock on effect there. This is simply something you should have in mind if you ever use my expanded mercs list. (Not that I mind the FAL being more of a beast)

**Pull request closed without merging**
