### PR TITLE
[WIP][SUGGESTIONS WANTED!] Adds new dreamtext

### PR DESCRIPTION
**Pull request by cebutris**
## About The Pull Request

Adds in more dreamtext!

Currently there's not much, but I'm very open to suggestions!

## Why It's Good For The Game

I killed virgo's dreams. Now I must add more, to restore the balance.

## Changelog
:cl: The Community
add: Diversified dreaming!
/:cl:

### CODE REVIEW

**Comment by EldritchSigma** [comment]
"submitting", "dominating", "A demotion", "stuck in the elevator", "a meteor", "a shadekin", "help maintenance", "only vendor food", "a blue ethereal figure", "an anomaly", "the RUST being bought", "a cold metallic surgery table", "reality warping time freezes", "a corrupted dogborg", "only dogborgs on the station..", "Phoron Clouds", "A red hardsuit", "a xenomorph", "a facehugger", "an evil presence", "blood soaking out of the walls", "strange glyphs in red on the floor", "a nice warm meal", "something sweet to drink", "a teleporter malfunction", "an interrogation", "expedition shuttle being stolen"

**Comment by Thalpy** [comment]
"petpatting", "wigglepurring", "meowing cats", "a basket full of kittens", "hugging", "picnicing", "condering the following:", "blowing up chem", "mewling", "crooning", "furranium", "baking", "seducing", "a cute plushie", "a painting of catgirls", "a painting of a happy wolfgirl saying awoo", "a painting of space supper", "a tasty bar of chocolate"

**Comment by yourdoom9898** [comment]
@Thalpy Did you accidentally end up on RP again, because we don't have furranium here.

**Comment by Thalpy** [comment]
Thinking about it porting furranium here might cause max drama

**Comment by yourdoom9898** [comment]
@Thalpy I mean, we don't really have the "smoke grenade in the bar" type posionings, so I don't know how much use it would get, but this is unrelated to the current PR

**Pull request merged**
