### PR TITLE
Debris Fields Updated: Something Rocky...

### PR DESCRIPTION
**Pull request by CharlesWedge**
**Brought to you by the Nanotrasen Department of Explorer Preparedness _(Now Defunct)_**

## It's Just Some Space Junk
_- The Last Words of Horace Crane, shortly before being ripped to Red Chunks by Hivebots._

Debris Fields can be one of the most dangerous environments you will be expected to work in. Though most commonly infested with the common space carp, it can also contain hazards like malfunctioning drones and defense systems. However debris fields also act as the hiding spot for dangerous galactic menaces, such as rogue silicons, pirates and raiders. Any damage you take to to your suit could become lethal as it exposes you to the vacuum of space. Make sure you take following steps when exploring these dangerous environments.
- Always Make sure you internals are read before you expose yourself to space
- Always keeps materials for emergency suit repairs ready
- Make sure to top up your jetpack.
- Max Sensors and stay close to your friends.
- Report Everything to your the Expedition Head.
- Always remember where you parked your shuttle.

By following these steps you are not only ensuring your safety but the safety of the rest of the expedition ensuring it is both successful and profitable, while reducing company medical expenses! Now get out there brave spacemen, all of space is yours to conquer!

_Nanotrasen is not liable for any damages that occur to Employee's body and property while on expeditions. Expenses incurred to explorer incompetence will have their cost of treatment deducted from Employee paychecks. All property retrieved by expeditionary teams is considered property of Nanotrasen. Nanotrasen does not approve of the conquest of sovereign government bodies including but not limited to recognized local governments and corporations._

## Debris Field Updated
The Debris Field is the oldest POI set still in rotation today. Though well liked by explorers, due to the richness of its POIs I decided to give it some love anyway. With 4 New POIs and with some older POIs given Touch-Ups, Explorers will have a bit more to explore. The nature of POI generation in the Debris field has also been changed. Some POIs now may be prevented from spawning in a given round. In compensation the overall budget for POIs has risen. The Debris Field map has also been touched up, the four Nav Points are now in the four corners of the map and surrounded by meteors making them a slight bit more interesting. The new locations also use some uncommon types of mob which should be good for variety's sake.

## Changelog
:cl:
add: 4 New POIs
tweak: some POIs have been edited, making them look generally nicer, Many have also had their "Explored" Edges trimmed so they don't prevent everything from spawning in a box around them
tweak: The Space RV, once a static spawn is now a POI (and is not included in new POIs)
balance: POI spawning has been worked on... slightly fewer high weight POIs should spawn per round but their is a greater variety between them. This should means the same POIs don't spawn every round.
code: repathed the areas in the debris field, now all debris field areas are area/debrisfield/X rather than a mix between that and area/space/debrisfield/X... This is why we have so many files changed...
/:cl:

### CODE REVIEW

**Comment by CharlesWedge** [comment]
I could use some help trying to figure out how to Mapmerge into .tgms since it did it automatically before...

**Comment by CharlesWedge** [comment]
Okay this should be ready to Testmerge. I want explo to run a few rounds in it in case I need to adjust the spawning weights any.

**Comment by Captain277** [comment]
TGS is flagging either this or another PR with an unidentified merge conflict. Your last commit doesn't seem to have run checks properly as well. Just update from Master for me to see if it shakes out.

**Comment by CharlesWedge** [comment]
Alright Let's hope that fixed the merge conflict.

**Pull request closed without merging**
