### PR TITLE
comments out shadekin

### PR DESCRIPTION
**Pull request by peeesh**
## About The Pull Request

title

## Why It's Good For The Game

yall mfs cant behave, shadekin privileges revoked

## Changelog
:cl:
del: shadekin.
/:cl:

### CODE REVIEW

**Comment by AnalWerewolf** [comment]
Aw no funny comments in the code mocking shadekin, missed opportunity. Anyway yeah nah what's wrong with shadekin even? They're adminspawn only so you can't even use the excuse that there's shitters abusing something or that something is OP.

**Comment by peeesh** [comment]
i mean.
we could start another hour long discord argument if you want. for the third(?) time this week? 
plenty of reasons have come from those, it just seems people dont listen.

**Comment by Ketrai** [comment]
Improve features rather than remove them I'd say :P

**Comment by Andromeda-K22** [comment]
you can't improve a snowflake fetish race without pissing someone off

**Comment by yourdoom9898** [comment]
This seems like a petty "REE shaedkin man bad isalt PR" ngl, and I don't even give a shit about about shadekin

**Pull request closed without merging**
