### PR TITLE
A serious teshari PR: removes their agility, halves their speed

### PR DESCRIPTION
**Pull request by peeesh**
## About The Pull Request

Title is self explanatory. If you're unaware what the agility is, its the reason all the railings on the map have windows. Because it makes them autohop it. And, despite there being a toggle, people are too stupid to use it. Speed is now on-par with vox, totalling a reduction by half (jesus fuck) to -0.5 slowdown.

also why the fuck my PRs registering it as making the entire file bruh
## Why It's Good For The Game

Makes it less shit.

## Changelog
:cl:
del: agility
tweak: speed
/:cl:

### CODE REVIEW

**Comment by VailTheWolf** [comment]
Just let people earn their Darwin awards. Tesh EMT will deal with them.

**Comment by VailTheWolf** [comment]
Addendum: Windows had a double use saving retard tesh and saving the Suface base from a 3 z-level phoron flood from one phoron leak.

Remove the windows, set agility to off by default, and let them earn their Darwin's award if they play hooky.

Hell make the species whitelisted just like Vox to discourage abuse. (And get the admin team to actually enforce it.)

**Comment by RMagnum** [comment]
Whitelisting would be cool but staff probably dont want to because extra work or something. I dont think speed should be nerfed to vox either. Less, but not halved.

**Comment by TheFurryFeline** [comment]
I agree with Vail about setting the thing off by default, not removing it outright as a whole. There's been a few good things removed because of certain issues with the players and not the mechanics that'd make RP more fun.

**Comment by RMagnum** [comment]
The teshari speed is a problem in some cases. A strict whitelist would make keeping everything as is viable. Otherwise nerfing speed and turning off autojump is the better option.

**Comment by AnalWerewolf** [comment]
Imo their speed should be slightly lowered and their agility should be set off by default, that way if they fall off of stairs or balconies it is their own fault.

**Comment by VailTheWolf** [comment]
Again, I don't think an entire species should be punished under the sole reason of "Tesh bad" and "They keep getting themselves hurt". 

By that logic we should buff alcohol poisoning damage tenfold because of how many drunks medical deals with on the by and by. "That'll teach them for playing the game!"

**Comment by AnalWerewolf** [comment]
> 
> 
> Again, I don't think an entire species should be punished under the sole reason of "Tesh bad" and "They keep getting themselves hurt".
> 
> By that logic we should buff alcohol poisoning damage tenfold because of how many drunks medical deals with on the by and by. "That'll teach them for playing the game!"

If the drunks that drink themselves to death complained about the game mechanics I would care, yes. Although bad shitty smelly Tesh players is mainly a Virgo issue and I haven't really seen any of this in Citadel yet, so hey. Still I reckon the agility should be off by default since falling down will DESTROY any Tesh.

Also as medical, I like when people get hurt because it gives me shit to do.

**Comment by TheFurryFeline** [comment]
> Although bad shitty smelly Tesh players is mainly a Virgo issue and I haven't really seen any of this in Citadel yet, so hey. 

I'm a long-time Virgo player and I can say this with relative certainty that there aren't any players that would fall into 'shitty Tesh players' and haven't been for a good while.

**Comment by kevinz000** [comment]
also get rid of the "fuck yourself tesh agility" comment this is one of the times i don't think it should be kept.

**Comment by EldritchSigma** [comment]
Teshs agility/under table hiding is one of the more creative abilities races get. The speed is super ridicolous, but cutting that in half.. that would make them slower than Unathi I think.. They should be slightly faster yeah.. about as fast as Vox are.

People shouldnt be punished because the same few teshari keep falling down the stairs. This is air cushioning. I have played medbay now myself. And I am kind of glad if a Tesh hurts themself by falling down stairs.

**Comment by kevinz000** [comment]
Teshari are keeping agility, movespeed will be nerfed in the future 

Some people have brought up good arguments other than "stop making everyone into humans" so I'm going to close this and leave the rebalancing for the future when I have other stuff in place to make this more reasonable like agility doing slowdown

**Pull request closed without merging**
