### PR TITLE
Ports wagging sharktails from Main

### PR DESCRIPTION
**Pull request by ForgetfulShork**
## About The Pull Request

Adds an animated version of the sharktail, just use *vwag! 

## Why It's Good For The Game

 Most other people with tails can wag with either *wag or *vwag, why should people with a sharktail be left out of the fun?

## Changelog

:cl:
add: Added custom sharktail (sharktail, animated) that can use the *vwag emote
imageadd: added "sharktail_w" (which is just the wag animation) and "sharktail_a" (unused idle for sharktail, animated(I am dumb))
code: changed akula.dm (tails)
/:cl:

### CODE REVIEW

**Review by TheLordME — APPROVED** [review]
Icondiff seems weird, but the icons checkout I guess

**Comment by pixelkitty286** [comment]
This PR interferes with this https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/5497

**Comment by pixelkitty286** [comment]
Disregard @TheLordME please look at the files there is a problem

**Comment by pixelkitty286** [comment]
@TheLordME Please re-review their PR I helped out fix something that was over looked over that would have issues.

**Review by TheLordME — APPROVED** [review]
looks much better now

**Pull request merged**
