### PR TITLE
adds logging, contraband loadout, fixes issue #1595

### PR DESCRIPTION
**Pull request by buffyuwu**
fixes issue #1595 

adds contraband loadout category

fixes renaming sys not having any logging outside of href; now easily and immediately shows name(ckey) renamed/described a door as (description/name they chose) at (coordinates in x,y,z format) for admins

### CODE REVIEW

**Comment by buffyuwu** [comment]
@yourdoom9898 <3 pls contribute code tho ily

**Comment by TheFurryFeline** [comment]
Keyword of `fixes`, `resolves`, or `closes` #issuenumber should be typed out if you want to have that issue closed when this is merged. :>

**Comment by buffyuwu** [comment]
@thefurryfeline

i think having “issue” between fixes and the issue number (fixes issue #123 vs fixes #123) doesn’t automatically close it! didn’t even realize i was adding the word. thank cat. & also since the contraband loadout was vetoed i’ll make another PR of just fixes anyhow <3

**Comment by TheFurryFeline** [comment]
What I meant is that it should be typed out with one of those keywords followed by whatever issue number you intend to close with a PR's merging.

**Comment by buffyuwu** [comment]
i know. i was adding the word issue between the keyword and the issue number, and i think my unconsciously doing that was the reason the keyword wasn’t working

**Comment by TheFurryFeline** [comment]
Fair nuff

On Jan 8, 2020 12:44, "buffyuwu" <notifications@github.com> wrote:

i know. i was adding the word issue between the keyword and the issue
number, and i think my unconsciously doing that was the reason the keyword
wasn’t working

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/1640?email_source=notifications&email_token=AJGMTY4V2XWXU5XL4DQYFYTQ4YGHRA5CNFSM4KDR4BG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEINMH7I#issuecomment-572179453>,
or unsubscribe

**Pull request closed without merging**
