### PR TITLE
[WIP] - UnderTether PvE Zone (Major Update)

### PR DESCRIPTION
**Pull request by Enzo-Leon**
## About The Pull Request

THIS IS A BETA TEST FOR THE NEW ZONE. ALL CONTENT IN THIS IS NOT FINAL AND SUBJECT TO CHANGE. Please provide any, and all, feedback to the #development-discussion-rp discord channel. Sending DMs for this *will* go unnoticed due to the volume of personal messages I get.

Large map for PvE content for the Tether map.

To-Do
More Mobs (Mob Types specifically)
Point of Interest zones (PHASE 1 DONE)
Expanded area 
More mining areas
~~Expanded Areas for more power/atmos interaction~~ (Scrapped to not give Engineering literal agony and pain)

FEEDBACK TO-DOs
- fix the loot spawns and reel it in a lot (DONE)
- adjust boss health and stats (DONE)
- Ensure #2147 gets full merged and then quickly fix this PR to ensure exploration stops getting oofed
- Make sure the config file for the map list gets updated so we stop getting the ZLEVEL 10/11 warning.
- fix holo map & station mini-map (DONE)
- fix health crew monitor (DONE)
- add access restriction to main entrances with either blast-doors or other multi-lock system. (Backburner)

## Why It's Good For The Game

QOL and more action to deal with during the game. This is a MAJOR WIP and sounds are in testing for ambiance and ensuring it's not a constant spam of sounds. PointOfInterests are on the TO-DO, but the static layout is set for now with adjustments expected for difficulty and risk/reward in general.

## Changelog
:cl:
add: New Under-Tether map below surface 1
tweak: shifted all existing maps up one z-level to reflect
/:cl:

### CODE REVIEW

**Comment by DiscordWizard** [comment]
Aight observed and oh boy does it look spooky and does it look fun. Unironically though, from the rewards and the enemies I've seen around, it needs to have more murder stuff rather than a sea of mice and some spiders for flavor, that way random visitors or bored people cannot unga through with a knife and get an smg without consequences

**Comment by Nethaufer** [comment]
There's a few issues brought on by the addition of a new zlevel. All the monitoring consoles are shifted by a zlevel as while you've named the new level 00-etc, it's still zlevel 1, now. Where before surface one was zlevel1, it's now zlevel2 with the undermaint being zlevel1. This throws off all the consoles with a map view (ex, camera monitor, atmos monitor, crew monitor, power monitor). The current zlevel map icons in nano/icons also need to be renamed to fit and actually be applied to the right level.
Further, the station holo maps have the new level printed on them, and due to its size, it overlaps with two of the maps:
dreamseeker_2020-06-30_08-02-52

Furthermore, the show-station-minimap maps also show the new level, and while not a huge issue like the holomaps, it shows the entire layout of the level for that round:
dreamseeker_2020-06-30_08-03-58

These really need to be addressed before this can reasonably be put into a full merge.

**Comment by Enzo-Leon** [comment]
The two above points for holo-map and minimap have been fixed <3

Working on other issues. TO DO will be added to master PR text

**Comment by Enzo-Leon** [comment]
Boss info changed (increased health / stats )
loot spawns heavily reeled back to not be omega stupid powerful (If still not good, we'll look to doing a special custom loot table for a weekend project)

**Comment by Enzo-Leon** [comment]
POIs (First Phase) are added and have a % chance to spawn in the POI tiles for players. More POIs and expanded zone will be added in a future phase of the beta for this.

**Comment by Enzo-Leon** [comment]
Project is on hold until further notice. Feedback taken is being worked on and re-addressed. ETA for this will possibly me a month+ out, or replaced with a different project. Thank you all for the feedback on the initial set-up, and we'll take this into consideration for future major changes.

**Pull request closed without merging**
