### PR TITLE
New Marksman Gunbox

### PR DESCRIPTION
**Pull request by VailTheWolf**
## About The Pull Request

Adds two new Marksman rifles intended for Exploration Crew. 

The Marksman Energy Rifle is set up to do reliable consistent damage, with an auto recharge, but it does not recharge too terrible fast. 
The Scoped Bolt Action comes with _Hitscan_ (but still misses because of the accuracy code) 7.62 hunter cartridges. What you get is what you get. Better RoF and potential DPS than the Energy Rifle, but limited "specialty" ammo that you can't resupply by any means at the moment. 

## Changelog
:cl:
add: Gunbox with two "new" rifles. 
add: Exploration Vendor selection for Gunbox
/:cl:

### CODE REVIEW

**Comment by yourdoom9898** [comment]
That's is _absurdly_ overpriced for that crate. For context, I could buy 6 regular Mosins or 2 of the regular energy rifles for the same price as one gunbox.

**Comment by VailTheWolf** [comment]
Closing this to change method of acquirement. 
New PR coming tonight.

**Comment by VailTheWolf** [comment]
> That's is _absurdly_ overpriced for that crate. For context, I could buy 6 regular Mosins or 2 of the regular energy rifles for the same price as one gunbox.

No longer relevant. @Captain277 has changed this to be a Explorer Vendor Item with a point price of 300. Nothing further.

**Comment by silicons** [comment]
> more guns for exploration

> hitscan and one that's autorecharging

**Comment by VailTheWolf** [comment]
> > more guns for exploration
> 
> > hitscan and one that's autorecharging

Field testing two new station locked sniper rifles. Working scopes. Been working this with Cap, as said before.

**Comment by silicons** [comment]
station locked doesn't matter it's still a hitscan gun with one being autocharging
300 exploration points is supposedly a lot until you realize you can multiply them by having multiple scanners/whatever they're called. 
exploration is already the most loot filled role to the point of being a paramilitary i do not see why they are now getting sniper rifles

also what does field testing even mean here? they will be removed after a while? @Captain277 i am not a fan of this at all when the role is already so combat driven in stark contrast to almost the entirety of the rest of the server.

**Comment by KasparoVy** [comment]
> i am not a fan of this at all when the role is already so combat driven in stark contrast to almost the entirety of the rest of the server.

Struth, hardly any creatures in beltmining and the dang dogborgs are always dead off the hop.

**Comment by VailTheWolf** [comment]
New Commits pushed. 
### Changed: 

- HV Hunter ammo is now simply a twice as fast as a normal ballistic projectile
- HV Hunter ammo damage values have been changed to keep it in relative terms to other 7.62 ammo, rather then getting shafted with no damage output
- You now get 9 stripper clips for a total of 50 rounds of HV Hunter ammunition (normal 7.62 can be used in this rifle if you seriously need more ammo in it)
- Choosing the Scoped Bolt Action now includes a Bandolier
- Both the Marksman Energy Rifle and the Scoped Bolt Action have had their scoped accuracy increased to 80 (does this var even work? IDK)

**Comment by VailTheWolf** [comment]
A new update has been pushed. 

### Change Logs:

- Added new M1A Garand rifle to replace the Scoped Bolt Action
- Increased Base and Scoped Accuracy to 100, because it seems like miss chance doesn't care
- Nerfed Hunter and Sniper Hunter ammo to 25 damage, 45 bonus damage (70 total)
- Buffed the Sniper Laser Beam damage to 60
- The Ballistic option of the Marksman Gunbox now comes with 7 spare clips (7*8=56 Don't spend it all on one Xeno)

**Pull request merged**
