### PR TITLE
Removes the .45 from the sec vendor.

### PR DESCRIPTION
**Pull request by GrayRachnid**
And adds in a new gun, the Variable Velocity Taser. The .45 has been moved into the armory with a new sprite.

The VVT has two modes, your good ol taser and the stun revolver. It has 20 taser shots and 10 stun revolver shots. This is subject for balance change. There are only 5 of this on the map. 2 in each vendor, and one in the warden's locker.

In order to compensate for the lack of ballistics for the hardcore sec mains, I've also added two netguns to the security equipment room.

I don't mind making the VVT acquirable elsewhere but I'll need suggestions on where and for what price.

Sprites should be visible with the icondiffbot.

This also reduces the agony on the stun revolver shot from 70 to 55, and gives the stun revolver 8 shots instead of 6.

All credit of the sprites goes to the folks at https://github.com/discordia-space/CEV-Eris/ All I did was change a few pixels.

### CODE REVIEW

**Comment by CameronWoof** [comment]
I like the new sprites. That said, the gun looks like a straight upgrade to the stun revolver _and_ taser, and the removal of the .45 from the security vendor will interfere with #832. 

I would suggest 16/8 shots instead of 20/10, or making this a research-locked gun. Giving security roundstart netguns seems iffy to me, as it's currently one of the few things security asks research for.

**Comment by GrayRachnid** [comment]
i'll switch it to 16/8 and make it acquirable with cargo. The netguns are there to compensate for lack of .45s.

**Comment by Andromeda-K22** [comment]
Netguns are absolutely useless. They do not compensate for the lack of ballistics in any way what-so-ever.

**Comment by avabee** [comment]
Netguns are horribly imbalanced and serve to act as a buff to the victim, making them immune to projectiles and being clicked on while allowing them to disarm and punch others within range.

**Comment by GrayRachnid** [comment]
That's why a new gun was added alongside the net gun.

**Comment by MarinaGryphon** [comment]
The fact remains that it conflicts with #832 which is, in my opinion, much more useful than the VVT. People already abuse major non-conductive to tank taser shots, and removing the ability to use pepperball shots (a suitable ranged alternative for anyone who isn't wearing a mask/goggles, etc, which isn't very common) isn't worth the marginal utility provided by this new gun.

**Comment by avabee** [comment]
The fact remains that it conflicts with #832 which is, in my opinion, much more useful than the VVT. People already abuse major non-conductive to tank taser shots, and removing the ability to use pepperball shots (a suitable ranged alternative for anyone who isn't wearing a mask/goggles, etc, which isn't very common) isn't worth the marginal utility provided by this new gun.

**Comment by DarkWolfInsanity** [comment]
If you fuck up my respritable .45 pistols in the sec sidearm cases, i'm gonna come to your house

**Comment by Andromeda-K22** [comment]
The sidearm cases are kinda useless anyway. And all this does is remove the pistols from the sec vendor?

Sidearm cases will be phased out (eventually) by me remapping the equipment room again.

**Comment by GrayRachnid** [comment]
I can't do anything about the conflict since it's a conflict of balance. That's up to the maintainers.

**Comment by Andromeda-K22** [comment]
We could sit here and argue balance all day i guess but @kevinz000

**Comment by GrayRachnid** [comment]
I'm not going to argue about it, i'm going to leave it to the decision makers.

**Comment by Andromeda-K22** [comment]
https://citadel-station.net/forum/viewtopic.php?f=38&t=2371&p=8021#p8021 Discussion in progress.

**Comment by kevinz000** [comment]
i caved but we're keeping roundstart ballistics *for now* until i have a plan in place to either fully keep them or axe them.

**Pull request closed without merging**
