### PR TITLE
Refactors Preference Colour Previews, Improves Marking & Hair Customization

### PR DESCRIPTION
**Pull request by KasparoVy**
Ports https://github.com/PolarisSS13/Polaris/pull/7215 from Polaris.

Refactors preference colour previews to use colour square from Paradise.

Adds buttons to navigate forward or backward in the list of hair & facial hair styles

Adds a button to put a marking in a specific order.

## About The Pull Request

Ports https://github.com/PolarisSS13/Polaris/pull/7215 from Polaris.

Refactors preference colour previews to use colour square from Paradise.

Adds buttons to navigate forward or backward in the list of hair & facial hair styles

Adds a button to put a marking in a specific order.

## Why It's Good For The Game

Significantly improves the experience of customizing a character's hair, facial hair and markings while cleaning up code.

## Changelog
:cl:
add: Added buttons to go forward or backward hair & facial hair styles.
add: Added a button to move a marking to a specific place in the order.
tweak: Markings are now properly aligned.
refactor: Ports Para's colour_square and improves customization colour previews.
/:cl:

ss13 improved hair and marking customization 20201009

### CODE REVIEW

**Comment by KasparoVy** [comment]
@Zandario https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/2423/commits/df2c4dfdaf2edacf37edfae046e4ae608f40bbf1 resolves the issue with custom species not able to use hair

**Comment by Zandario** [comment]
Aight, appreciated!

**Comment by Enzo-Leon** [comment]
Looks good so far! Thank ya!

**Comment by KasparoVy** [comment]
Wicked, cheers-- my pleasure, everything being aligned was requested by the kind reviewers at Polaris

**Pull request merged**
