### PR TITLE
Add safeties to guns

### PR DESCRIPTION
**Pull request by Shadowtail117**
## About The Pull Request

Guns now have safeties, implemented similarly to Baystation safeties (credit to them for sprites and general code structure). When holding a gun with a safety mechanism, a new overlay will appear on the gun detailing if the safety is on (a green S) or off (a red !). You can also examine the gun to see the status of the safety if you feel like it.

While a gun's safety is on, the trigger will not move, and attempting to fire it will prompt a visible_message detailing such. You can control-click on the gun to toggle the safety or use a new Toggle Gun Safety verb (defaults to C).

If you are on harm intent and try to fire a gun with the safety on, there is a 50% chance you will reflexively un-safety the gun. This chance also applies if you unholster a safetied gun on harm intent.

The intent preference for firing a gun has been removed as this system replaces it.

On the backend, guns have a flag variable that controls if they have a safety; the crossbow and zip gun have had theirs removed since they are improvised weapons. There is also an option to add a sprite for when the gun's safety is off, for example to add a red light indicating the status of the safety to the receiver of the gun.

Video showing how it works:

https://user-images.githubusercontent.com/25853190/162732286-f1a68166-3230-43cf-bc01-a123f4360eba.mp4

## Why It's Good For The Game

Adds more depth to gun handling and hopefully prevents accidental misfires because you forgot to switch hands before clicking on something.

## Changelog
:cl:
add: Guns now have safeties. You cannot fire a gun while its safety is on.
imageadd: Guns now have an overlay when holding them showing whether or not the safety is on.
add: You can control-click a gun in your hand to toggle its safety or use the new Toggle Gun Safety keybind. Unholstering it while on harm intent or attempting to fire it while on harm intent have a 50% chance to take off the safety reflexively in case you forget.
del: Removed the Gun Firing Intent Requirement.
/:cl:

### CODE REVIEW

**Comment by VailTheWolf** [comment]
This is a redundancy. Help/Harm intent safeties are already in the code. From the bottom of my heart I think this is cool, but it's ultimately unnecessary and doesn't need to be implemented in my opinion.

**Comment by Zandario** [comment]
Personally I am fine with this, but I would like to see the safety indicator to either be on the top or bottom of the right side of the holder

**Comment by Shadowtail117** [comment]
> Personally I am fine with this, but I would like to see the safety indicator to either be on the top or bottom of the right side of the holder

That sounds a bit funky to be able to see if a small switch on someone's gun is flicked up or down just by glancing at their body. If you want I could add something to the examine if you're adjacent showing if the safety is on/off?

**Comment by Shadowtail117** [comment]
The above was resolved over discord, the safety sprite was moved to the top right of the gun in the UI instead of top left.

**Comment by KillianKirilenko** [comment]
Help/Harm intents already cover this, and SS13 already has enough layers of fiddly, unintuitive shit as it is. Don't think this one's a good idea in the long run.

**Comment by lolman360** [comment]
it'd be fine if there was a eris-style safety selector switch over the swap hands bar but this solution is pretty ugly and serves little purpose since help/harm intents already exist

**Comment by Shadowtail117** [comment]
PR has been updated with a new keybind to toggle the safety of a gun in either hand, defaulting to C.

**Pull request merged**
