### PR TITLE
Adds Leafeon Stuff

### PR DESCRIPTION
**Pull request by king5327**
Requested by mysterious Stranger#5024 on Discord

Yes I tested this.

### CODE REVIEW

**Comment by king5327** [comment]
We have tentacle monsters. These are just another option of tail/ears/whatever.
There's no ckey lock on them.

**Comment by Andromeda-K22** [comment]
My issue more lies within the fact that it encourages bad characters, but alright.

**Comment by RagingTestosterone** [comment]
actually made an account to comment on this, (mysterious stranger) 
Bhijn (deathride58)10/18/2018
also, ay, just wondered out of curiosity. you guys are taking into account that the main and rp servers are supposed to be interconnected lore-wise, yeah?
I put the Eevee species in main more than a year ago, are leafeon body parts Really that much of an issue?

**Comment by nik707** [comment]
I'm putting a fat veto on this unless both other maintainers say it's fine, the lore doesn't need to be interconnected, and that would infact be impossible. Literally. Unless we rewrote the entirety of the NT/Syndicate shit on RP.

**Comment by deathride58** [comment]
Eevees aren't a part of the server's canon on main. This PR is just extra fluff for customization, all of the non-standard species are more or less non-canon, and can be handwaved with "genemodding"

**Comment by kevinz000** [comment]
While Jay has specified he wanted main and RP to share common lore, there's no canon lore of our own on Citadel as of yet.
I do not feel like enabling pokemon species is the best of moves.
I will not be lending my support to this PR.

**Comment by kevinz000** [comment]
Like Nik said, rename this to something that doesn't make it a pokemon part and greyscale.

**Comment by nik707** [comment]
conflict

**Comment by RagingTestosterone** [comment]
ill give king a poke to see what the issue is

**Comment by king5327** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/commit/0416acdeadcdfa6020de159a1d1a5f467ddabf40

I like Lilly but I'm reasonably sure she uses Notepad for coding.

**Pull request merged**
