### PR TITLE
Updating some sprites

### PR DESCRIPTION
**Pull request by Enzo-Leon**
## About The Pull Request

Adding new sprites for the advanced trauma and burn kits for medical

## Why It's Good For The Game

QOL love

## Changelog
:cl:
add: new sprites for trauma kits.
/:cl:

### CODE REVIEW

**Comment by AnalWerewolf** [comment]
I like these new sprites, looks like modified versions of the armor kit Toriate made for me a while back for my map. 

Good stuff, glad to see them used for more things if that is the case. 

image
image

**Comment by Enzo-Leon** [comment]
Aye. I wanna bring a lot of our sprites up to a more clean look like that. But that'll be a long overtime situation hah.

**Comment by Nethaufer** [comment]
I really rather don't like the new sprites, tbh.

**Comment by Enzo-Leon** [comment]
Working on reverting wrench and crowbar sprites back to pre-change.

**Pull request closed without merging**
