### PR TITLE
The PR for Pussys

### PR DESCRIPTION
**Pull request by TheLordME**
## About The Pull Request
grafik

Apparently our players are to afraid of ruining the round for everyone, so why not just get rid of the engine entirely?
Lets become a completely scene based server.

## Why It's Good For The Game
Makes setting the engine optional

## Changelog
:cl:
fix: fixed Our Players to be to afraid of setting the engine
/:cl:

### CODE REVIEW

**Comment by LeadOnTaste** [comment]
Ayo, dude, wtf? April is two months later!

**Comment by TheLordME** [comment]
yeah, but apparentlly of our players 3% are only willing to play engineering, and of those 3% half cant be assed to learn engineering and want to stay in their box of static setups they know

**Comment by TheLordME** [comment]
wtf, I spend 20 minutes on this

**Comment by LeadOnTaste** [comment]
Just suck a fat one and go play engineer by yourself.

**Comment by TheLordME** [comment]
Hmm, i wonder who is one of the engineering mains on the server, oh right it's me! 
Maybe I'll just leave y'all alone to die in the toxic hole you nurgle worshippers dug yourself.

**Comment by LeadOnTaste** [comment]
> Hmm, i wonder who is one of the engineering mains on the server, oh right it's me! Maybe I'll just leave y'all alone to die in the toxic hole you nurgle worshippers dug yourself.

I am the one who joins as CE and sets the N2 SM up for you almost every day before shouting at people for not playing Main.

**Pull request closed without merging**
