### PR TITLE
Mid-Point Beautification. Otherwise known as, woah check out the cool sky and this pretty room.

### PR DESCRIPTION
**Pull request by Enzo-Leon**
## About The Pull Request

Adding an adjustment to the mid-point tether map with a cafe to serve drinks and coffee.

## Why It's Good For The Game

Once more, the old QOL love to the server. While we have the cafe on the first floor. This might be moved out in a future update for something else. Either that, or a different adjustment can be done to the tether cafe to allow people to feel like its a space they can chill out in.

## Changelog
:cl:
tweak: Made midpoint not 100% useless. Now.. 90% useless *snap
image: https://cdn.discordapp.com/attachments/686843631084372000/691892011124523049/Test.png
Current design of the adjustments.
/:cl:

### CODE REVIEW

**Comment by Mewchild** [comment]
Screenshots of the change?

**Comment by nik707** [comment]
Use map merge

**Comment by Enzo-Leon** [comment]
This is with the mapmerge though. I can run the program again and re-push a commit to make sure it's good to go.

**Comment by Enzo-Leon** [comment]
First commit had an invalid map merge. Closing and reopening to ensure map file isn't borked.

**Pull request closed without merging**
