### PR TITLE
[WIP] vchat port

### PR DESCRIPTION
**Pull request by Zandario**
## About The Pull Request
This PR is going to be a full port of VOREStation/VOREStation#6592 with some minor edits for our needs

I'm also putting this up as a draft so I can't pussy out.

## Why It's Good For The Game

Better Chat, has tabs (hot af), dark theme, etc. just view the main PR referenced.

## Changelog
:cl:
add: vchat
imageadd: loading animation
code: lots and lots and **LOTS** of **CODE**
/:cl:

### CODE REVIEW

**Comment by LetterN** [comment]
duplicate of my pr

**Comment by silicons** [comment]
not a fan of vorechat unless tg uses it tbh but whatever

**Comment by Zandario** [comment]
> nevermind, but goonchat is far better. (#2085)
> 
> also i **will** be axing nanoui in favor of tgui3/4

Started this because your port went radio silent for a while, now looks like I don't need to do this anymore then.

**Comment by ShadowLarkens** [comment]
@LetterN Sorry to necropost, but I wanted to note that I've been working on TGUI-4.0 upstream, in case that makes it easier for y'all.
https://github.com/VOREStation/VOREStation/pull/8422
https://github.com/VOREStation/VOREStation/pull/8440
https://github.com/VOREStation/VOREStation/pull/8444
https://github.com/VOREStation/VOREStation/pull/8471

**Pull request closed without merging**
