### PR TITLE
Canonizes the LiquidFood Straw, Adds Opening Proc to Foods For Snack Purposes, Seals Snack Foods

### PR DESCRIPTION
**Pull request by Captain277**
## About The Pull Request

1. **LiquidFood and Subtypes Now Have to Be Manually Opened via Integrated Straw.**
2. **Retypes LiquidFood and Subtypes.**
3. **Adds Opening Proc and Mechanics to Food Type.**
4. **Seals Packaged Snack Foods Based On Type.**

## Why It's Good For The Game

1. _For a long time I've emoted Kat as snapping a straw into place on food pouches to suck the protein out. It just seems like a reasonable way for the system to work. So I finally got tired of just emoting it to myself and I've decided to force my little bit of food packaging headcanon on everyone! This adds a boba-tea styled straw to protein pouches, which must be snapped into the foil to eat from them. It's literally the same code as opening a bottle or a can, but I love it._
2. _Eventually during the process, I realized that instead of duping the same procs for everything, LiquidFood, Protein, and Vitamin should all be the same types. So I made Protein and Vitamin subtypes of LiquidFood. Had to update paths on two POIs and some other files as a result. Low impact tweaking._
3. _THEN I realized that instead of just making the procs bespoke to LiquidFood, I should in fact just make them procs for food itself, since food works on a similar principle to drinks already. This way, we can make it so that other snacks have to be opened first too. Like chip bags, for instance. I know that we have canned food sprites that have unused "closed" icons. We can now utilize those here! How fun._
4. _AND THEN I decided I'd just pull the trigger and make all pre-packed snack food items...well, packaged. I eventually divided it into four categories: Wrapped (ie: Candy Bars), Bagged (ie: Chips), Boxed (ie: Raisins), and Unorthodox (Br-ad T-be). This resulted in my adding in an update_icon check for canned items that adds closed sprites so now it looks like you actually opened the can, etc. I'm pretty sure I caught everything, but adding other snacks to the system is pretty easy so it shouldn't be that hard if I missed some!_

Also I almost forgot. I made a little diagram for how the straw works, to prevent confusion.

## Changelog

:cl:
add: Adds Check to Open LiquidFood Pouches.
tweak: Retypes all LiquidFood into subtypes of the parent.
tweak: Gives Food in general an opening proc for manually opening snacks.
/:cl:

### CODE REVIEW

**Comment by yourdoom9898** [comment]
The ultimate Capri-Sun

**Review by TheLordME — CHANGES_REQUESTED** [review]
Bagged, wrapped and boxed should probably be abstract subtypes and candy should be a subtype of that, not the typ that everything else subtypes off

**Comment by Captain277** [comment]
> Bagged, wrapped and boxed should probably be abstract subtypes and candy should be a subtype of that, not the typ that everything else subtypes off

Yeah I considered doing that, but I try to avoid using abstracts. I can probably change that though.

**Comment by TheLordME** [comment]
Abstract classes are what you want, they help keep code clean

**Comment by Captain277** [comment]
> Abstract classes are what you want, they help keep code clean

Yeah I already sorted it out. This one's good to merge.

**Comment by TheLordME** [comment]
I'll review it again and merge when I am home (~10h)

**Review by TheLordME — APPROVED** [review]
its been 12h

**Pull request merged**
