### PR TITLE
 hello please relay the message that i would like for kevinz to code a toggle to eye glow so that proteans can have the edgy glowing eyes

### PR DESCRIPTION
**Pull request by silicons**
here @zeroisthebiggay

### CODE REVIEW

**Comment by zeroisthebiggay** [comment]
can we fuck yet

**Comment by silicons** [comment]
proteans have no eyes :/

**Comment by lolman360** [comment]
@silicons add this to the regular glowing eye trait and xenochim too you fucking retard

**Comment by KasparoVy** [comment]
I have no eyes but I must glow

\👀,.`👁️'.,👀/

**Pull request closed without merging**
