### PR TITLE
moves emotes to /living/

### PR DESCRIPTION
**Pull request by lolman360**
wow! now the living simple can emote. HUGE dub for admins playing mercs during events and prometheans/proteans.
image

### CODE REVIEW

**Review by TheLordME — CHANGES_REQUESTED** [review]
I violently disagree with having two seperate emote files that essentially do the same

**Comment by lolman360** [comment]
i did it relatively quickly because blu is rewriting emotes apparently

**Comment by lolman360** [comment]
i closed it because i wanted to do it properly but it turns out it wasnt that hard to just not duplicate everything

**Review by TheLordME — CHANGES_REQUESTED** [review]
Okay as a temporary solution until the emote system is reworked

**Comment by silicons** [comment]
hi, bodytemp was done first,p lease let that testmerge & merge before doing this.

**Comment by BlueWildrose** [comment]
Apparently while this was testmerged, the *roll command that a lot of players have been using stopped working.

**Comment by lolman360** [comment]
> Apparently while this was testmerged, the *roll command that a lot of players have been using stopped working.

i literally fixed this its just that nobody updated the testmerge for like 5 rounds

**Pull request closed without merging**
