### PR TITLE
massively nerfs security/buffs carp/simples

### PR DESCRIPTION
**Pull request by lolman360**
simplemobs no longer take burn damage from halloss

### CODE REVIEW

**Comment by VailTheWolf** [comment]
How about no? Warden, HOS, CD are never 100% on shift all the time. Lethal distribution should be limited to threats that require lethals, like the blob or event characters. Security would have absolutely no ability to respond to incapacitated miners in the underdark unless they powergamed into the armory.

**Comment by lolman360** [comment]
security shouldn't be responding to incap miners in underdark, paramedics should. Why shouldn't carp/grubs/etc require lethals? If they happen on lowpop one secoff probably won't be able to handle it all even with a taser.

**Comment by VailTheWolf** [comment]
I do not have to bear the burden of proof in this, it's not my PR. All you've done is make the change in the code and asked "Why not?" You haven't followed the format, and you sure as hell haven't given a proper explanation to why this needs to change. Nonetheless I'll humor you for the moment. 

Security is a proper department to help secure miners in a hostile environment. Carps and grubs do not warrant a code change worthy of lethal deployment, thus letting security respond with their normal gear is fine. These are two minor level threats. I'm going to bring up an old argument here as well. "Expedition team shouldn't get ballistic lethals because they Blue on blue too often." If that argument was allowed to stand, then security responding to simple mob threats with "non-lethal to crew" weapons should too. If we gave out lasers for every runtime event, then tasers, stun revolvers, etc, would become mute except for roleplaying. 

"Lasers don't get enough use as it is." Then change that by other means. Get events going. Maybe make it so that certain sub-types of simple mobs require lethals instead of blanketing the entire simple mob stats. (I.e. fix and then PR xeno events.)

**Comment by lolman360** [comment]
actually yeah hold on i can just override the proc on protean blob level

**Pull request closed without merging**
