### PR TITLE
Expedition Equipment Update

### PR DESCRIPTION
**Pull request by Kazkin**
##About The Pull Request
This update adds expedition vendors for explorers, SaRs, pathfinders, and pilots who spawn with vouchers made specifically to issue out equipment such as armor/weapons/medicine/ammo/etc. In addition it contains a few bug fixes and adjustments to improve over all quality.

##Why It's Good For The Game
Who doesn't love a wider variety of shooty shooty bang bang? This broadens the load out and choices of an expedition team member to give them a wider selection of weaponry to choose from and add some replay value to expedition. It's the first step in making expeditions far more interesting compared to spawning and using the same equipment every shift. 

Side note: Using git hub is an ass for first timers and I did a whole bunch of test commits with a mob from long ago called metal head. They're slated for use with the new map Werewolf is working on so they can be committed as they are currently working but missing sprites.

## Changelog
:cl:
add: Expedition vouchers with which all expedition related jobs spawn with.
add: Expedition vendors with loaded gear supplies taken from suggestions of people on the discord.
add: Custom names and descriptions for existing combat belts and armor.
add: Expedition las-rifle, see code entry comments for details.
add: Expedition 'bolter', see code entry comments for details.
add: Expedition las-burster, see code entry comments for details.
add: Expedition 'melter', see code entry comments for details.
add: Expedition revolver, see code entry comments for details.
add: Expedition uzi, see code entry comments for details.
add: Expedition pistol, see code entry comments for details.
add: Expedition pump shotgun, see code entry comments for details.
add: Expedition carbine, see code entry comments for details.
add: Expedition sniper, see code entry comments for details.
tweak: The expedition shuttle now only takes 20 minutes to fuel, down from 40, since explorers can now gear up much quicker.
balance: The expedition frontier phaser/pistol has its damage reduced to 15 (down from 40) due to its hilariously overpowered nature given it has unlimited ammo.
fix: The dragonuv rifle now loads and uses the correct ammo.
/:cl:

### CODE REVIEW

**Comment by ForFoxSake** [comment]
Okay, haven't really had a chance to look in detail at the changes here, but one immediately sticks out to me.

Why does this remove the entirety of tether's 5th z-level?
I don't think that's an intentional change, is it?

**Comment by Kazkin** [comment]
Literally what? No that isn't intentional. When I ran the tests the floor
was there. All i adjusted was putting in 2 vendors.

**Comment by Kazkin** [comment]
I'm not sure how it happened but the small map edit I made a massive chunk of map code for... some reason. I'll have to look at it tomorrow and figure out what fucked up because I didn't intentionally or unintentionally delete anything in the map code.

**Comment by Kazkin** [comment]
Closing this for now to figure out what fucked up.

**Pull request closed without merging**
