### PR TITLE
Shadekin and Crewkin changes

### PR DESCRIPTION
**Pull request by MediHound**
--Do not testmerge yet! PR was made so Kev can work on it as well.--

## About The Pull Request

After a discussion with the lore team, changes were proposed to Shadekin, both for their lore and their mechanics. This PR will do the necessary changes.

## Why It's Good For The Game

These changes are tied to the lore of the species, as well as to the wishes and limitations that the lore team asked for them.

## Changelog

:cl:
add: Pocket Dimension ability for Shadekin and Crewkin, a small storage.
change: Adjust all lore texts in code to fit the new Shadekin lore.
/:cl:

### CODE REVIEW

**Comment by timothyteakettle** [comment]
I cannot in good faith approve a PR that adds jaunting to a crew species - it is **incredibly** disruptive to gameplay and should never be something tied to a species, whitelist or not.

**Comment by MediHound** [comment]
> I cannot in good faith approve a PR that adds jaunting to a crew species - it is **incredibly** disruptive to gameplay and should never be something tied to a species, whitelist or not.
> 
> Adding the most relevant label I can find in the list - I would rather discussions start now instead of waiting until development work has been done just to say "actually we don't want this".

At the lore meeting on 16.03., those concerns were brought up by me as well. The lore maintainers decided that it would be alright, reminded me that only whitelisted people would have access to it, and we can hold whitelisted people to a higher standard. As such it was decided to give jaunting to players. My initial idea of keeping only Black-Eyed Shadekin to be whitelisted and other Shadekin to be admin only was discarded, in favor of trying to make Shadekin as a whole more accessible while giving them a gimmicky power.

Since most of the cases where a jaunt would break the game are revolving around events, the role ban for Shadekin will likely be expanded to also include Explorer, Field Medic/Search and Rescue, and (Exploration) Pilot. This is in addition to the already existing ban on Command and Security.

The 2 second timer for the jaunt came from the following calculation: 0.5 server lag leniency, 0.5 human reaction time, 1.0 time to move.

**Comment by silicons** [comment]
jaunting was removed

**Comment by MediHound** [comment]
Testmerge has been successful, functionality and description text (where visible) was updated.
Some minor cosmetic things that can be fixed in future PRs, since this one is already very stale.

**Pull request merged**
