### PR TITLE
Renames Daemon to Dremic

### PR DESCRIPTION
**Pull request by Shirumic**
## About The Pull Request

Renames the Daemon name to Dremic in compliance with lore discussions, ffixes the description, and changes the color of the language to a different purple shade.
## Why It's Good For The Game

Brings the Dremachir language up to lore standards.

## Changelog

:cl:
spellcheck: Renames and reflavors the Daemon language to Dremic
/:cl:

### CODE REVIEW

**Review by silicons — APPROVED** [review]
please stop using the webeditor

**Comment by Shirumic** [comment]
i hate VCS i hate VCS!!! i will NOT wear the long socks!!!!!

**Review by silicons — CHANGES_REQUESTED** [review]
do not change ids

**Comment by Shirumic** [comment]
fixed with the help of lohikar!

**Review by silicons — APPROVED** [review]

**Pull request merged**
