### PR TITLE
Enables the off-duty CO position

### PR DESCRIPTION
**Pull request by PolymorphBlue**

### CODE REVIEW

**Comment by CameronWoof** [comment]
Not super thrilled with the idea of giving an Off-Duty position bridge access. The bridge is a high-security location and staff assistants shouldn't be in there.

**Comment by kevinz000** [comment]
Eh we can remove bridge if there's issues

**Comment by CameronWoof** [comment]
Do you not feel that "greyshirts having access to all the consoles in the bridge" is an issue? That's a lot of power to give someone with zero responsibility.

**Comment by Useroth** [comment]
Gotta side with Cameron here, tbh.
It should be only cosmetic, imo, like all other off-duty roles

**Pull request merged**
