### PR TITLE
Ports Goonchat, Asset Cache System, and refactored examine

### PR DESCRIPTION
**Pull request by LetterN**
## About The Pull Request
see title

## Why It's Good For The Game
Goonchat, and no need for resending cached assets when reconnecting (or restarting)

## Changelog
:cl:
add: Fully enables goonchat
add: Asset Cache System
add: loud mode on radios (command and clown gets them free)
tweak: Sorts the game UI buttons
tweak: Updates the radio nanoui
tweak: Clickcatcher resizes instead of looping 15*2 times
tweak: Updates client verbs
tweak: Electropack now works outside monkey gamemode
tweak: forces ALL remote music to be on HTTPS protocol
admin: play internet sound works.
fix: toggle sound verb now stop the sound that they're toggleing
/:cl:

### todo
- [x] fix conflict
- [x] make lobby music work

# THIS TOUCHES SAVEFILES, BE WARNED

## This also fucks with the radios too, **STOP VV'ING IT IN MAP-EDITOR AND MAKE SUBTYPES OF IT**

### CODE REVIEW

**Comment by LetterN** [comment]
hello taggerbot?

**Comment by Enzo-Leon** [comment]
Heyo, how's the progress coming along on this so far? Is there any still glaring merge issues/bugs that need to be fixed before we can do the doom test/full merge and worry about save files?

**Comment by LetterN** [comment]
recommend backing up savs before testmerge, though doubt it would nuke savefiles

**Comment by Zandario** [comment]
Closing this since it's outdated and working on #2317 now

**Pull request closed without merging**
