### PR TITLE
Exploration Hangar Rework

### PR DESCRIPTION
**Pull request by KillianKirilenko**
## About The Pull Request

An extensive rework of the exploration hangar area. Behold!

image
A little outdated, but it gets the main points across.

To summarize;
* As a whole, the exploration area is less 'barebones'. This overhaul isn't as complex as Virgo's current setup, but I'm not trying to integrate the currently nonfunctional gateway.
* Prep room significantly expanded, and more voidsuits are provided to match the number of lockers (and job slots), along with seperate medical suits and a medical cycler. The pilot suits and cycler have been moved into the prep room. It also has a basic drill, a shovel, an anomaly detector, and a cyborg analyzer.
* The pathfinder's office is larger, better lit, has its own fax machine, and includes its own recorder and omnitranslator. The PF's locker contains a new belt that holds a wider array of useful items like cells, ammo, medical supplies, tools, small melee weapons, and so on, limited to NORMAL size items.
* The entry hallway now has a space set aside for crates that comes with anomaly containers and empty crates.
* The showers are now a seperate room with more privacy, and the shower room contains more washing machines (there was previously only one washing machine, in the briefing room).
* There's a new exploration-crew-only 'ready room' that explorers can idle in, rather than sitting in the shuttle or the briefing or prep rooms. Includes vendors and a spare charger.
* The shuttle itself includes a hidden GPS beacon for explorers to follow with GPS units, if they get lost. It also has lightswitches.
* The hangar has cosmetic blast doors along the north wall.
* The atrium has been modified slightly, with the small ponds removed in favor of a full-size fishtank that replaces the bland sandscape in front of the bridge.

## Why It's Good For The Game

Quality of life improvements, mostly: exploration teams will be slightly better supplied for their adventures, without handing them everything they need to win. They'll have more room to prepare in, extra gear for additional explorers, the ability to more easily deal with any anomalies they find, that kind of thing.

I realize this might be a little contentious (espec. the PF's fancy bandolier) so feedback is welcome. Chances are I might end up reducing the bandolier to five or six pockets so that it holds less to make up for its greater flexibility.

## Changelog
:cl:
add: Added a special bandolier for the Pathfinder's use, found in their locker. Holds a wide variety of useful items such as tools, medical supplies, batteries, ammo, small melee weapons, misc. gadgets (gps, geiger, recorder, camera), and so on. It can only hold NORMAL or below size items, so larger drills/etc. will not fit.
del: Cleaned up some bits of Station 2 that are seen only by ghosts or curious people with meson scanners.
tweak: Removed the mini-ponds on the Station 1 Atrium and replaced the weird boring sandscape in front of the bridge with a fish-tank. Now the koi have more room to swim!
tweak: Remapped the exploration hangar/area pretty extensively, seperating the showers for privacy and adding a seperate ready room adjacent to the hangar that holds vendors and a table.
tweak: Minor changes to the abandoned observation lounge on station 1; made it its own new area, added vent/scrubber/apc/emergency shutters, and added a wall block to fix an odd spot introduced by the addition of the club.
/:cl:

### CODE REVIEW

**Comment by Tename** [comment]
Ok I got a few issues with this.

- The equipment room is way to big and should be cut down by 4 tiles
- I dont really see the need for a break room and a meeting room, especially if the break room isnt really private anyways.
- Break room is too empty and can probably be cut down 1 tile south or north
- Shower room could probably be cut down a bit to the left aswell and maybe add some toilets to the south to make it less empty.
- Way too many washing machines in the shower room, looks repetitive
- The area has a total of 3 borg chargers when the shuttle is docked, this area really only needs the shuttle one and meeting room one.
- Random and in consistent use of monotiles in multiple areas. 
- Floor decals are lacking in the equipment room, especially by the suits
- Tables in the equipment room should be plastic and the benches steel maybe
- Move the equipment room double door up one tile and move that crate down to the south.
- Cut out the crate in the main hanger, and the one by the bottom right in that little entry room.
- No cameras in the equipment room.
- No cameras in the pathfinders office.
- No air alarms in the equipment room EVA suit areas
- No fire alarms in the entrance room
- No vents/scrubbers in the equipment room EVA suit areas.
- If you plan on keeping the break room I would add a disposal.
- Put the chargers in the equipment room instead of the meeting room

I'd recommend completely redesigning the equipment room then replacing the break room with the meeting room, moving the pathfinders office where the meeting room was, then scraping the break room and make some sort of special S&R area to the south of equipment.

**Comment by KillianKirilenko** [comment]
I appreciate the thoughts.

* Yeah, it's a bit big, but I wanted there to be plenty of room for people to move around whilst gearing up.
* It's mostly there as a space-filler, I'll admit.
* Any wall of washing machines is going to look repetitive though? Not sure I can elegantly squeeze in toilets, but I'll see what I can do. The showers being mounted to the wall under the curtains makes them fiddly as shit to use, so I might rotate the room layout a bit.
* Definitely need to go back and redo the floors. I also want to redo the vent/scrubber placement anyway.
* Same as the current equipment room, but I'm definitely not against doing touchups here.
* Equipment room benches have always been wood, for whatever reason. Not that it doesn't strike me as an odd choice, thinking about it.
* Cameras: I knew I'd forgotten something.
* Air Alarms: Current setup doesn't have them either, believe it or not. I'm gonna go set up vents and scrubbers for the subrooms though.

That all said, I do like the idea of a medical/SAR station. At this point the presence of the S1 Lounge is getting in the way of what I'd like to do here.

Some definite food for thought. Now to see if I can wrangle mapmerge again.

**Comment by KillianKirilenko** [comment]
image

Flipped the placement of the prep and briefing rooms, overhauled the prep room and added a lot more floor decals, replaced the readyroom with an emergency medical station, rotated the bathroom showers around and added a toilet stall.

The EMS is not open to regular personnel (requires one of medical, pilot, explorer, or pathfinder access) and has far more limited capabilities so that it isn't used as a quick replacement for proper medbay usage given that it's closer to the elevator. I am open to suggestions for other equipment it might need though.

Not in this shot; moved the briefing room door into the center, fixed a couple of misplaced alarm panels, added a NanoMed vendor to the EMS, added fitness/coffee/NIF vending machines into the 'inset' by the bathroom/showers, fixed the two walls by the EMS, changed the area icons for the areas involved to make the map more readable.

**Comment by Tename** [comment]
Looks a lot better few more issues though.

- S&R Needs vents and scrubbers
- Duplicate chargers in S&R
Also I still think that the equipment room and S&R room looks a bit awkwardly big but it's way better now. If you don't want to make the room smaller you might want to consider moving the sleepers to the center like medbay proper to make it look less empty

**Comment by KillianKirilenko** [comment]
* Vent and Scrubber in the EMS are under the nanomed & bench. I should probably fuss with their positioning so they're closer to the center of the room for general atmos purposes.
* I don't think I can do too much to reduce the size of the equipment room without having to make it some kind of awkward shape, or without overhauling the layout again.
* I might move the scanner+sleepers away from the walls, then try doing the same floor designs as seen in the treatment center, but I feel that it's important people have plenty of room to move around.

Longer term (post hardsync, or if/when the gateway functions by itself again), I'm thinking we move the Chapel to where the Library was (Ast1, near the Bridge), and then we can put the Gateway above the hangar, accessed by stairs that'll take the place of the spot with the crates in the foyer.

**Comment by Tename** [comment]
> 
> 
>     * Vent and Scrubber in the EMS are under the nanomed & bench. I should probably fuss with their positioning so they're closer to the center of the room for general atmos purposes.
> 
>     * I don't think I can do too much to reduce the size of the equipment room without having to make it some kind of awkward shape, or without overhauling the layout again.
> 
>     * I might move the scanner+sleepers away from the walls, then try doing the same floor designs as seen in the treatment center, but I feel that it's important people have plenty of room to move around.
> 
> 
> Longer term (post hardsync, or if/when the gateway functions by itself again), I'm thinking we move the Chapel to where the Library was (Ast1, near the Bridge), and then we can put the Gateway above the hangar, accessed by stairs that'll take the place of the spot with the crates in the foyer.

If you move the S&R suits into the S&R room you should be able to cut down some space, Here let me show an example, give me a few

**Comment by Tename** [comment]
I rushed this because I have to bounce soon, I can make a better example later but here is a shitty general layout https://i.gyazo.com/7c609eba98774d343fca2c129c1f5fb7.png

**Comment by KillianKirilenko** [comment]
I'd rather keep everyone's outfitting in the same area, and I'd also rather avoid having the racks/cycler blocking the view from the PF's office. Yes, I know they don't block the view in ingame/mechanical terms, but they absolutely would in a sane universe.

Gonna focus on touching up the EMS bay for now. Also working on SAR-variant exploration voidsuit sprites.

**Pull request merged**
