### PR TITLE
if you cannot code your air traffic spam right it does not deserve to exist

### PR DESCRIPTION
**Pull request by silicons**
someone please fix this when they can be bothered to, this is causing runtimes every trigger.

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
Culprit is #2782. Enzo apparently removed the "NO" state from that line without understanding that the system would shit itself.

Revert
```
		"a current system time sync" = list("sending time sync ping to you now"),
```
to
```
		"a current system time sync" = list("sending time sync ping to you now", "your ship isn't compatible with our time sync, set time manually"),
```

**Comment by Captain277** [comment]
Hey @silicons I'm ready to fullmerge this, but would you look over Killian's comment to determine whether it just needs to be tweaked first for me?

**Review by Captain277 — CHANGES_REQUESTED** [review]
"a current system time sync" = list("sending time sync ping to you now"),

To:

"a current system time sync" = list("sending time sync ping to you now", "your ship isn't compatible with our time sync, set time manually"),

**Comment by silicons** [comment]
ah thanks!

**Review by Captain277 — APPROVED** [review]
It isn't showing the original request thingy. This should clear that I think? Git is weird.

**Comment by KillianKirilenko** [comment]
Score one for `git blame`. 👌

Shit like this is why I always gave the system several multi-hour runs to catch possible issues.

**Pull request merged**
