### PR TITLE
Mining Softsuit Armor and Suit Slot

### PR DESCRIPTION
**Pull request by MediHound**
## About The Pull Request

After complaints from some miners, Blue told me to give the Mining Softsuit the same armor as the Voidsuit had.
In addition, I added some commonly used mining tools to the list of items the Mining Softsuit can carry in its suit storage.

## Why It's Good For The Game

It's really nice for the Mining Suit to be able to carry some Mining tools on its suit slot!
Regarding the armor changes, I'm sure those who complained have their reason, and we hope those complaints get addressed with these changes.

## Changelog
:cl:
tweak: Expanded the Mining Softsuit storage list for some mining tools
balance: Gave the Mining Softsuit the protection the Mining Voidsuit had
/:cl:

### CODE REVIEW

**Review by Captain277 — COMMENTED** [review]
Heya. In fact, I only wanted the melee armor changed. The Laser, Energy, Bomb, and Bio armor ratings shouldn't be updated. For the suit, body_parts_covered should not include the feet and hands, as well. The softsuit doesn't cover these areas.

**Comment by MediHound** [comment]
> Heya. In fact, I only wanted the melee armor changed. The Laser, Energy, Bomb, and Bio armor ratings shouldn't be updated. For the suit, body_parts_covered should not include the feet and hands, as well. The softsuit doesn't cover these areas.

Can change the Laser/Energy/Bomb/Bio armor back again. But the specific complaint that made you tell me to give it the same armor as the Voidsuit included the lower bomb armor.
The other reason for the complaints, is that unlike the Voidsuit, the Softsuit does not protect the feet and hands. Because of that, a single hit to the feet can instantly decide combat (broken foot, prone and stunned for multiple seconds while the enemy keeps hitting you. Escape impossible with the broken foot.) and this was, from what I've experienced myself, and from what I've been complained to about, one of the things that was problematic.

If you show me how to do so, I can edit the sprite to include boots.

**Comment by MediHound** [comment]
Testing showed that many boots, like the Jackboots, already come with armor. Having both boot and suit armor would create a very high resistance for feet specifically. Removing the foot covering because of that.
Raising the Bomb armor of the Mining Suit and its hood to adress concerns.

**Comment by TheLordME** [comment]
Is this still undergoing play testing?

**Comment by MediHound** [comment]
> Is this still undergoing play testing?

From what I can tell, it's fine to merge. I've tested it both ingame and local, and went over the changes with Cap.
So, after a review, I think it's ready for a merge.

**Review by TheLordME — APPROVED** [review]

**Pull request merged**
