### PR TITLE
Removes the Virgo Hardsuit Nerf

### PR DESCRIPTION
**Pull request by jakeramsay007**
Simple change but necessary for the switch to SC

### CODE REVIEW

**Comment by Poojawa** [comment]
Engineers don't need SWAT armor tho. there's a reason it was nerfed

**Comment by jakeramsay007** [comment]
This isn't the engineer hardsuit, this is the mining hardsuit

**Comment by Poojawa** [comment]
>armor = list(melee = 60, bullet = 50, laser = 30,energy = 15, bomb = 30, bio = 100, rad = 50)

is what you're buffing it to.

**Comment by jakeramsay007** [comment]
I'm not buffing anything, I'm removing the virgo nerf and putting it back to polaris levels.

**Comment by pantherpusher** [comment]
I don't understand why the mining hardsuit has any bullet protection. Melee protection makes perfect sense because that can be explained as protection from debris while mining. Like a hard hat would.

**Comment by nik707** [comment]
Closing due to inactivity, reopen if you'd like it reconsidered.

**Pull request closed without merging**
