### PR TITLE
adds taur loafing

### PR DESCRIPTION
**Pull request by timothyteakettle**
## About The Pull Request
its only enabled for drake taurs currently as they are the only ones with sprites for it

basically when people with the drake taur sprite rest they loaf instead, as shown in the following set of images:
image
image
image
image

the front and back sprites look weird but that's to do with 1. layering 2. taurs always look ridiculous from front/behind compared to sideways

cygnusb made the sprites they just asked me to do the coding

## Why It's Good For The Game
its cool i guess

## Changelog
:cl:
add: adds taur loafing
/:cl:

### CODE REVIEW

**Comment by LordSaladin** [comment]
Loaf

**Comment by Verkister** [comment]
Did it ever occur to you that moving the loafing icon to the bottom of the frame instead of keeping it where it normally is aligned on the human sprite was a completely unnecessary mistake because the mob's pixel_y change there would move the loafing taur to ground level anyway, and with everything coded to accommodate that mistake instead of correcting it, it has become a "load-bearing" fuckup which will bring the rest of the code tumbling down to a rewrite stage when fixed.

**Comment by Zandario** [comment]
> Did it ever occur to you that moving the loafing icon to the bottom of the frame instead of keeping it where it normally is aligned on the human sprite was a completely unnecessary mistake because the mob's pixel_y change there would move the loafing taur to ground level anyway, and with everything coded to accommodate that mistake instead of correcting it, it has become a "load-bearing" fuckup which will bring the rest of the code tumbling down to a rewrite stage when fixed.

First of all, This is a year-old PR by a dude who mainly does stuff for CitMain, not CitRP, so this is probably a port of something they did there.

Second of all, we are going to rewrite such things, it's what we do at CitadelRP, complaining here is pointless.

**Comment by silicons** [comment]
i'm sure it didn't occur for the newer coder who was trying to contribute to the codebase and make it better instead of complaining a year later on the github

if you wanna do it better than do it better we frankly don't care
you don't see me coming to your turf to harass people about their shit design designs and inefficient code from the past
welcome to open source

if you want something done better, do it better
don't complain other people had the gall to contribute.

**Comment by Verkister** [comment]
> if you want something done better, do it better

Already on it and adding sprites for all the other taurs as well. Feel free to port it over once I'm done.

**Pull request merged**
