### PR TITLE
Switchtools

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

Adds switchtools, a type of hybrid tools distinct from advanced tools. While advanced tools are faster and two-in-one, switchtools are 4-in-one at worst (basic surgery switchtool) and can do more things than advanced tools at best (CE's holotool can clean and work as a flashlight.).

Basic switchtools are **slower** than their regular counterparts, but make up for it with their compactness.

Holotools are slightly faster than their base equivalents.

This PR introduces 4 of these devices.

Basic switchtool. Screwdriver wrench crowbar wirecutters multitool. 1.2 toolspeed on all, small item.
From R&D, same time as advanced tools.

Surgery switchtool. Scalpel, haemostat, retractor and bone setter, 1.2 toolspeed on all, small item. From R&D, probably before IMS but after laser scalpel.

CE's holotool. Screwdriver wrench crowbar wirecutters welder flashlight soap. 0.9 toolspeed on all of them, small item, limited availability.

Admin holotool. All surgery tools except FixOVein and bone gel, all tools except cable coil, flashlight, soap. 0.9 toolspeed. Bus only.

re:balance - might make holotool variant of switchtools, make them printable but make them use cells.

todo: 

- [x] get them working
- [x] switch to radials for selection
- [x] balance
- [ ] tier inbetween CE and switch?

## Why It's Good For The Game

someone asked for them, i'm code man

## Changelog
:cl:
add: switchtools. They're tools, that switch what they do.
/:cl:

### CODE REVIEW

**Comment by drofoljaelisglis** [comment]
🆒 Idea

**Comment by JLinari** [comment]
Give the adminbus one an esword, it's a good idea I swear

**Comment by lolman360** [comment]
it already has one

**Comment by Mewchild** [comment]
Engineering Switchtools can't fit into engineering toolbelts, as a note

**Comment by lolman360** [comment]
intended, i'll add it if its wanted

**Comment by Mewchild** [comment]
I've heard a small number of people in round complaining how they won't fit. I know I personally find it annoying, but I understand why it's done. It seems odd, though, since the advanced tools can fit in the belt, and they're hybrids.

**Pull request merged**
