### PR TITLE
Excursion Shuttle: V3b Surface

### PR DESCRIPTION
**Pull request by KillianKirilenko**
## About The Pull Request & Why It's Good For The Game

The excursion shuttle can now be flown to and from the surface-3 hangar/pad. This means it can be used for emergency evac and has a safe place to land after expeditions if tesloose or delam utterly ruins station-1 whilst everyone is out.

uss-mad-lad

Mostly this means the excursion team can very easily ~~jump straight to getting shitfaced because the rookie got eaten alive by a deathclaw~~ deliver and collect stuff to/from Science without having to fuck around with the elevator. Handy if you bring back a Ripley or something.

As a side-effect this also runs MM on the tether_ships map (I had to add a new transit zone to avoid weirdness) and fixes two old appliances on the small cruiser that were repathed but never replaced. Not that anyone uses the small cruiser but whatever.

Strictly speaking I don't think this is *"lore friendly"* because of V3b's spicy purple atmosphere but who really gives a fuck? If you care, go fix the flight risk mechanics and the broken/unusable backup shuttle.

Also accidentally includes the same changes as #1593 because I fucked up a bit. Oops. Thanks past me.

In case anyone needs a guide; simply fly to the (formerly dead-end) "Skies of Virgo 3B" waypoint from the near-station waypoint and you should have an option to fly down to the surface from there.

## Changelog
:cl:
add: You can now fly the excursion shuttle down to the surface and back to orbit again.
/:cl:

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Active edges for z level 18 related to railings? 

> Active Edge /connection_edge/unsimulated (/connection_edge/unsimulated)
+--- Connecting Turf the railroading @ 124, 1, 18
+--- Connecting Turf the railroading @ 125, 1, 18
+--- Connecting Turf the railroading @ 126, 1, 18
+--- Connecting Turf the railroading @ 127, 1, 18
+--- Connecting Turf the railroading @ 140, 24, 18
+--- Connecting Turf the railroading @ 140, 25, 18
+--- Connecting Turf the railroading @ 140, 26, 18
+--- Connecting Turf the railroading @ 140, 27, 18
+--- Connecting Turf the railroading @ 140, 23, 18
+--- Connecting Turf the railroading @ 140, 22, 18
+--- Connecting Turf the railroading @ 140, 21, 18
+--- Connecting Turf the railroading @ 140, 20, 18
+--- Connecting Turf the railroading @ 140, 19, 18
+--- Connecting Turf the railroading @ 140, 18, 18
+--- Connecting Turf the railroading @ 140, 17, 18


You didn't even touch this file, though. Hmm.

**Comment by KillianKirilenko** [comment]
"railroading" is the unbreakable perimeter fencing... I'm not sure which z #18 is though. I think it might be the caves?

Either way just travis being travis, as usual.

**Comment by TheFurryFeline** [comment]
You'll be able to find out where the active edge can get caused by if you
jump to the coordinates with admin commands in a test server. Something
somewhere is causing Atmos movement, thus the active edge screeching

On Nov 9, 2019 20:00, "Killian" <notifications@github.com> wrote:

"railroading" is the unbreakable perimeter fencing... I'm not sure which z
#18 <https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/18>
is though. I think it might be the caves?

Either way just travis being travis, as usual.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/1601?email_source=notifications&email_token=AJGMTYZNSOXK5DWRMMPGTY3QS5MJXA5CNFSM4JLICTP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDUSXFA#issuecomment-552151956>,
or unsubscribe

**Comment by Tename** [comment]
@TheFurryFeline  Your like Email unsub link ended up in that comment

**Comment by KillianKirilenko** [comment]
Under normal conditions (read: maploader actually worked) this appears to correspond with the south-east corner of the Virgo 2 Surface.

Not much I can do about it either way. Out of scope for this PR and not my fault.

**Comment by TheFurryFeline** [comment]
Strange. Travis being Travis, I guess.

**Comment by TheFurryFeline** [comment]
And now There's a conflict from a merged pr. Oof

**Comment by KillianKirilenko** [comment]
It might be having some kind of hiccup around the bar remodel. Not too hard to fix, I'll just have to repaint the destination area I think.

**Comment by KillianKirilenko** [comment]
Manually resolved, navcheck done. Should be OK now.

**Comment by TheFurryFeline** [comment]
Conflicts are easy enough to fix manually via the conflict thing on browser for .dm files with .dmm files being trickier with all those things in the diff but still doable. .dmi files? You're better off grabbing a new version and reuploading the new additions. Can do the same with the others, too.

**Comment by nik707** [comment]
gonna testmerge just in case

**Comment by KillianKirilenko** [comment]
I think this has been testmerged for a while now? I've not tested it personally though.

**Pull request merged**
