### PR TITLE
Projectile Tweaks, Autolathe Tweaks, etc

### PR DESCRIPTION
**Pull request by VailTheWolf**
##About The Pull Request

Re-commiting ammo clips into the autolathe code, updating the Phase weapons' projectile to reflect resent adjustments to 

## Why It's Good For The Game

Ruskit did the good boy and made Hunter bullets do what they are supposed to actually be effective at killing. He forgot to make Phase weapons do the same. 

Honestly most of this is prep work for new additions to the game that I'm sure most of you will enjoy. 

## Changelog
:cl:
add: Sniper and Sniper Hunter Ammo to projectile folder
add: Sniper Hunter Ammo Clip to Autolathe
tweak: Energy.dm in projectiles folder
fix: Ammolathe is back to full capacity
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
Tweaks. The word is spelled tweaks.

**Comment by VailTheWolf** [comment]
I don't know why travis is crying. This complied and worked fine on my end.

**Comment by Hatterhat** [comment]
>hitscan ballistics

**Comment by VailTheWolf** [comment]
> > hitscan ballistics

As said many times before including in code comments, Discord, and Github alike, hitscan ballistics are and should only be intended for scoped weapons like the SVD. Now that I think about it, I forgot to add something into the code. Stand by.

**Comment by VailTheWolf** [comment]
Resolving errors that shouldn't exist. New PR to come.

**Pull request closed without merging**
