### PR TITLE
Minor Werebeast Clothing Fix

### PR DESCRIPTION
**Pull request by SpartanKadence**
## About The Pull Request
This puts some of the clothing from the old system into the new system, along side with making it so said clothing fits properly onto the werebeasts.  Clothing that was put into the new system was deleted from the old. 

**Suits:**
Bomber Jacket (“old”)
Varsity Coats (Blue, Black, Red, Brown)
Military Jackets (Normal, Alternative, Tan, Navy, Grey, Black, White, Dark Green)
Hazard Vest

**Shoe:**
Jackboots (Normal, Toeless)
Swat Boots
Combat Boots
Brown Shoes
Black Shoes 
Galoshes
Clown Shoes

**Gloves:**
Fingerless
Black
Insulated
Fake Insulated
Latex

**Undersuits:**
Jeans (Black)
Pants (White)
Yoga Pants
White Shorts
Jumpsuits(White, Grey, Orange. Yellow, Black, Robotics. Engineering, Janitor, Hephaestus)
Swept Skirt
Nurse Suit
Old Man Suit

Reference to a few of the sprites.
image

## Why It's Good For The Game
While I don't exactly believe the benefits will be noticeable at the start, I know someone wanted to use the werebeasts for a new concept species, and I'd like to get them prepared for as such if it is ever brought to light. At the very least, some clothing has been ported over to the newer, more favorable system.

## Changelog

:cl: Kade
add: Added clothing sprites  into the new system.
del: Removed clothing spites from the old system into the new system.
fix: Fixed a few clothing items that did not fit correctly onto werebeasts.
/:cl:

### CODE REVIEW

**Comment by TheLordME** [comment]
why are most of the jumpsuits topless?

**Comment by SpartanKadence** [comment]
> why are most of the jumpsuits topless?

That's how they were when I found them in the files. Nearly all of them are topless besides a select few. I didn't sprite them.

**Review by TheLordME — DISMISSED** [review]
should be fine to testmerged

**Comment by Lohikar** [comment]
While discussed on Discord already, this should not be merged as-is — general-purpose clothing should not be >32x32.

**Pull request closed without merging**
