### PR TITLE
Adds meme gun

### PR DESCRIPTION
**Pull request by TheLordME**
and moves size gun to the other guns in files

## Changelog
:cl:
add: Adds the stripper gun, same effect as the cell, just as a normal gun
refactor: Sizegun and stripper gun file moved to the other gun files
/:cl:

### CODE REVIEW

**Comment by MalricB** [comment]
i believe this is somehow causing size changes (100% > 200% at least) to default to 'fuzzy' scaling mode instead of 'sharp' if you have it selected
spawning at 200% doesn't give you fuzzy scaling
but using size gun / NIF's size program does

**Comment by Captain277** [comment]
Temporarily removing Testmerge to troubleshoot. Will confirm whether PR tangentially affects size scaling.

**Comment by MalricB** [comment]
uhh guess i was wrong, my bad
not a clue wth is causing the issue then

**Comment by TheLordME** [comment]
Nicc and me already trouble shoot that issue, its definitly not cause by the PR, it doesnt happen on my local, even after spawning in as fuzzy and then changing it back

**Pull request merged**
