### PR TITLE
update to vulp+unathi voidsuit sprites

### PR DESCRIPTION
**Pull request by VarkaSelyn**
## About The Pull Request

I decided to brush off my spritehacking "skills" and have a couple of resprites as a warmup;
1) vulpkanin pilot suit has the proper tail and a new "high visibility" helmet design based on the medical voidsuit. now includes the alternate blue schema.
2) vulpkanin explorer suit likewise now has the proper tail, with the "new" design based off a mashup of the vulp security suit and human explorer suit with a larger, neutral-colour visor
3) vulpkanin captain's suit, to go with the others added in #656 
4) unathi explorer's suit, hacked together from the unathi riotsuit and human explorersuit

Scaled-up Preview;
vulp_newsuits_full_x3

## Why It's Good For The Game

Makes pilot and explorer voidsuit sprites visually-distinct for vulpkanin/unathi and vulpkanin/unathi-subtype customs, as they not only used taj sprites but were also completely identical (that is, explorer voidsuits turned from black+purple to grey+red when equipped).

## Changelog
:cl:
tweak: sprites! as mentioned.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Looks really good, inheriting the high-vis dome from the medical helmet makes a lot of sense.

**Comment by VarkaSelyn** [comment]
Updated with Captain & Alternate Pilot for Vulpkanin and Explorer for Unathi/Lizard.

Progress sheet:
newsuits_full

**Comment by Novacat** [comment]
You are missing the Vulpkanin Captain and Alternative Pilot Voidsuit sprites, did you forget to add those?

Also, going to be yoinking these for upstream, since, the sprites you are replacing were just placeholders _anyway_

**Comment by VarkaSelyn** [comment]
Yeah I totally forgot. Easy enough to fix though, and I'm not sure the alt. pilot suit is actually used anywhere right now?

**Comment by Novacat** [comment]
Alt pilot suit was disabled in pilot suit cyclers because of a few gaps in the sprites. If those gaps are corrected, they can be re-enabled again.

**Comment by VarkaSelyn** [comment]
(Finally) created #1305 to fix the missing sprites on this one

**Pull request merged**
