### PR TITLE
Adds the 'Antiseptic Saliva' trait

### PR DESCRIPTION
**Pull request by CameronWoof**
Adds a new neutral trait, Antiseptic Saliva. Characters with this trait can use a verb in the Abilities tab to bandage and salve the wounds of an adjacent character, using nutrition as fuel. The purpose of this trait is to stand up to heal bellies as a way to provide healing to others without needing to use vore.

### CODE REVIEW

**Comment by king5327** [comment]
I stand by my request that this verb only heal a single wound instead of an entire limb at once, for a cheaper cost.

**Comment by CameronWoof** [comment]
That would require it to be coded differently and I don't know why you'd want to only heal one of several wounds.

**Comment by king5327** [comment]
Not really. All you have to do is make the loop break once an unsalved and/or unbandaged wound is salved/bandaged. And obviously skip the salved/bandaged ones.

**Comment by king5327** [comment]
High stress scenario where being at max hunger can get you killed is a good example, like on expedition. The last thing you want is a deathclaw charging your ass while you're moving slower than molasses. Being able to choose how many wounds get licked to conserve resources is way better.

**Pull request merged**
