### PR TITLE
KMine: Mining Dogborg

### PR DESCRIPTION
**Pull request by Holdelta**
## About The Pull Request

Adding a Mining dogborg to the list of dogborgs since I found it odd that Cargo was the only department without one.

Functionally the same as a normal mining borg, save for the Supply Satchel belly module which contain the reagents:

   - Glucose
   - inaprovaline
   - tricordrazine

(I also re-added the Vale Pupdozer sprites back in because that was lost in the hardsync)

## Why It's Good For The Game

As mentioned before, Cargo was the only department without a dogborg model, so adding that in along with its own belly feature.

## Changelog
:cl:
N/A
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
unknown

**Comment by Holdelta** [comment]
@thestubborn 
Mind telling me why you keep posting the same picture on my PR?

**Comment by yourdoom9898** [comment]
Can the KMine get Hyronalin so they have a way to treat Xenoarch RNG fucking miners?

**Comment by Holdelta** [comment]
@yourdoom9898 
I can add that in, yes.  Just want to make sure I'm not taking Medical's job, the current chems are from what I'm told, chemicals that miners can purchase from the vendor, so I didn't stray away from that.  If you think that would be beneficial then I can tack that on.

**Comment by Holdelta** [comment]
Will remake this PR in the future, as I have added more sprites/fixes upon getting feedback from upstream.

**Pull request closed without merging**
