### PR TITLE
protean rigs/protean fixes

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request
protean survival gear fixed
proteanblob pickup fixed
proteanblob putting themselves in other people's hands fixed

proteans no longer vore people regardless of `can_be_drop_prey` (vorestation oversight)
protean blobs can attack items in grab intent to vore them

proteans can transform into rigs now

wow, this race is powercreeped to shit and still there are only like,  1-2 regular players.

## Why It's Good For The Game
image

re:balance
the only :\ thing i see about this is it's technically roundstart rigs
but you can't use them on yourself soo it's not terribad, especially beause proteans are whitelist anyway

## Changelog
:cl:
add: Proteans are also fully functional rigsuits now. 
fix: proteans and being picked up, mostly
/:cl:

### CODE REVIEW

**Comment by Enzo-Leon** [comment]
This is to remain un-testmerged until the following issues are addressed/removed
- RIG suit mode needs to have -25% resistance to everything as this being a combat capable thing is beyond mary sue and is only to be for fluff/scenes.
- Nutrition values should be the same as every other race for balancing purposes.

**Comment by Zandario** [comment]
I'd say remove the armor or tone it down heavily and reroute the armor dmg to the protean as they're the RIG.

**Comment by lolman360** [comment]
@Enzo-Leon @BlackMajor  told me to do the nutrition things

@Zandario rerouting the damage would probably involve me implementing the entire DCS

**Comment by Enzo-Leon** [comment]
Unsure why BM gave the nutrition things, but the adjusted to the armor is good now for me personally. If you can tone it down then by 50% on nutrition then I'll give this the big pass if he has valid notes on why the increased IS needed.

**Comment by Zandario** [comment]
code/modules/clothing/spacesuits/rig/rig.dm:996:error: inconsistent indentation

**Comment by BlackMajor** [comment]
> Unsure why BM gave the nutrition things, but the adjusted to the armor is good now for me personally. If you can tone it down then by 50% on nutrition then I'll give this the big pass if he has valid notes on why the increased IS needed.

I assume you're referring to making synths have a max nutrition.

I told him to do that so that you couldn't have an infinite power RIG by having them vore a bunch of mobs.

**Comment by lolman360** [comment]
also this doesn't directly affect the nutrition values synths get from vore, this literally just stops them from having infinite power (as they have no downside to being fat) also the infinite rig power thing

**Comment by Enzo-Leon** [comment]
That's all good then. I'll give the full proper blessing on this to move forward then since all the issues and worries I have are either addressed, or information was given to me to resolve said worries!

**Pull request merged**
