### PR TITLE
bandaid fix - cult/rat signals no longer do anything if it's not the main ship triggering because exploration shuttles causing a cult invasion on the actual station due to bad piloting on THEIR shuttle is STUPID

### PR DESCRIPTION
**Pull request by silicons**
## Why It's Good For The Game

SIGH

## Changelog
:cl:
fix: exploration can no longer end the round with bad piloting skill
/:cl:

### CODE REVIEW

**Comment by buffyuwu** [comment]
you have to submit another commit to make travis **actually** run

**Comment by Captain277** [comment]
Shuttles still trigger ionospheric anomaly tiles when crossed.

**Comment by Captain277** [comment]
Travis is reporting:
`code/modules/events/cult.dm:95:error: /obj/effect/overmap/visitable/ship/triumph: undefined type path
code/modules/events/hostile_migration_vr.dm:101:error: /obj/effect/overmap/visitable/ship/triumph: undefined type path
vorestation.dmb - 2 errors, 0 warnings (1/16/21 4:45 am)
Total time: 1:13
\033[0;31mSome POIs appear to contain map-specific objects or code. Please isolate map-specific items/code from POIs.\033[0m`
As the error keeping this from being fullmerged.

**Comment by Captain277** [comment]
I've copied the changes in this PR. I'm just gonna close this branch and push those changes in one of my standing branches. That should clear the conflict and get this into the main repo finally.

**Pull request closed without merging**
